### ISSUE TITLE
jspm bundle-sfx fails in jspm@0.16.0-beta.6

### ISSUE THREAD

**Issue by helios1138** [jspm/jspm-cli#1010]
command: `jspm bundle-sfx app/main build/app.js --minify --skip-source-maps` fails with
```
Message:
    Command `jspm bundle-sfx app/main build/app.js --minify --skip-source-maps` failed with exit code 1
```
```
err  Expected operator before build/app.js
```

**Comment by guybedford** [comment]
Thanks, fixed in https://github.com/jspm/jspm-cli/commit/11ad880a90cb0f2cc2477bd8891684ebee7dd8e8.

**Comment by riddla** [comment]
I seem to be facing the same problem, although I am (presumably) using the fixed version: 

    jspm --version
    0.16.0-beta.7

    jspm bundle-sfx --amd src/index foo.js
   
    err  Expected operator before src/index

    jspm bundle-sfx src/index foo.js --amd

    err  Expected operator before foo.js

**Comment by guybedford** [comment]
@riddla try using `jspm bundle-sfx test foo.js --format amd` here.

**Comment by riddla** [comment]
@guybedford: Thanks a lot, that did the trick. Do you plan to update `https://github.com/jspm/jspm-cli/blob/0.16.0-beta.7/docs/production-workflows.md#creating-a-self-executing-bundle` and `jspm --help` with that information?

(By the way: you built a great infrastructure with jspm. It is really a breath of fresh air, as I was using the Bower/npm/RequireJs triangle for so long, with my module configuration held in two or three places. Since listening to http://devchat.tv/js-jabber/115-jsj-the-es6-module-loader-polyfill-systemjs-and-jspm-with-guy-bedford I really got your "browser first" idea.)

**Comment by guybedford** [comment]
@riddla sure no problem! It's still sort of an undocumented feature as its very new, but the docs will be updated yes as soon as it is deemed stable.

Thanks, glad to hear that discussion made some sense! If you're ever interested in contributing to the project at all do let me know.

**Comment by riddla** [comment]
@guybedford: Maybe I could spare some hours from time to time – but I'm just a frontend dev with profound knowledge of CSS/JavaScript on the client, I only tinkered with Node now and then. How can I help?

**Comment by wgorder** [comment]
@guybedford 

Seeing this when using the latest beta.  How do you specify the destination?
```
jspm bundle-sfx src/app/app .tmp/scripts/app.js --runtime                                        
     Building the single-file sfx bundle for src/app/app .tmp/scripts/app.js...

err  Expected operator before .tmp/scripts/app.js
```

**Comment by guybedford** [comment]
@wgorder `--runtime` isn't a valid flag here, so leaving it out should make this work.

**Comment by wgorder** [comment]
@guybedford Doh!  I am not sure where I picked that up from but removing it worked.  Thanks!
