### ISSUE TITLE
Multiple package definitions in config.js

### ISSUE THREAD

**Issue by danhalliday** [jspm/jspm-cli#1012]
I'm struggling with what probably is a really simple issue. I have two intermediate build folders that contain javascript files:

    build/development/
    build/production/

I can't work out how to write `config.js` to build both of them. The basic setup is:

    System.config({
      "defaultJSExtensions": true,
      "transpiler": "none",
      "paths": {
        "*": "*.js",
        "*": "build/development/*.js",
        "github:*": "jspm_packages/github/*",
        "npm:*": "jspm_packages/npm/*",
        "development": "build/development",
        "production": "build/production"
      },
      "packages": {
        "development": {
          "main": "app",
          "defaultExtension": "js"
        },
        "production": {
          "main": "app",
          "defaultExtension": "js"
        }
      }
    });

But I have to change the line `"*": "build/development/*.js"` when switching between development and production. Is there any way to override this from the `jspm` command?

**Comment by guybedford** [comment]
I'd suggest something like the following here:

```javascript
System.config({
  "defaultJSExtensions": true,
  "transpiler": "none",
  "paths": {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*",
    "app/*": "build/development/*"
  },
  "packages": {
    "app": {
      "main": "app",
      "defaultExtension": "js"
    }
  }
});
```

And then yes, just manually changing that path configuration when switching environments. Perhaps setting that up with a local script.

If you really don't want to do that, then create a custom build script (instead of using `jspm bundle`) which sets up your path correctly when instantiating the builder (`builder.config({ paths: { 'app/*': '...' } })`). Then including the path with a custom config in the browser as well.

**Comment by danhalliday** [comment]
Ok thanks, I think I'll go the custom build route then.
