### ISSUE TITLE
Copy/preserve properties in package.json's jspm section to config.js

### ISSUE THREAD

**Issue by klausbayrhammer** [jspm/jspm-cli#1014]
When we bundle our app using jspm we have to set the property `"buildCSS": false`. Unfortunately we maintain our jspm config in the jspm-section of our package.json. Until now we have created the config.js during buildtime so we dont have a config.js in our VCS.
The problem with this setup is, that I don't see any way of getting like the `buildCSS` property from the package.json to the config.js via jspm install.

My desired scenario would be:
* Do not modify the jspm-section of the package.json (covered by #428)
* Copy all properties in the package.json's jspm-section, which have no specific 'handler', into a new `System.config({ ...})' block in config.js

With the example above the package.json would look like this:
```javascript
{
  ....
  "jspm": {
    ....
    "buildCSS": false,
   ....
  }
}
```

By executing `jspm install -y` the following config.js would be created
```javascript
System.config({
  "buildCSS": false,
  ....
});
....
```

**Comment by guybedford** [comment]
Firstly maintaining `config.js` in version control is highly encouraged because that is the only way to have a predictable install of your app via version lock. If you really don't want to do that, then setting up custom build options is fine. But the recommended way to do this is by managing your own build and not calling `jspm bundle`. Custom build scripts are the recommended way to take control of your build any way. See https://github.com/jspm/jspm-cli/blob/master/docs/api.md#class-builder.

**Comment by guybedford** [comment]
Just let me know if you have any further questions here at all.
