### ISSUE TITLE
Support installation of packages from local folders and archives

### ISSUE THREAD

**Issue by subesokun** [jspm/jspm-cli#102]
Sorry that I come up with this topic again in another issue but this one is really important to me so I've created a separate issue to talk specifically about that. The ability of installing a package out of local folder or archive is an important feature to me. Like if you are not at home or at the office and for some reason you deleted your jspm cache you still want to be able to install packages which you downloaded beforehand.

Something that should be avoided is of course the implementation of some complex logic into the cli to just support this feature. So I was thinking about a solution which doesn't require huge changes. Potentially the following described installation process could be a first step towards a solution for this problem.

Scenario: User wants to install `github:proj/repo1=1.0.0` which depends on `github:proj/repo2=2.0.0` from a local archive.

``` bash
jspm cache github:proj/repo1=1.0.0 ../path/repo1.tar.gz --skip-dependencies 
jspm cache github:proj/repo2=2.0.0 ../path/repo2.tar.gz --skip-dependencies 

jspm install --offline github:proj/repo1=1.0.0
```

Calling `jspm cache github:proj/repo[=version]` without a file path associated should just download and build the package so that it's available in the cache. If a file path gets passed then jspm cache should skip looking up and downloading the package from the endpoint and just use the extracted content of that archive instead. That after the usual build operations should be performed on the package and store it into the cache. If the version gets omitted in the `jspm cache` call then jspm should try to read out the version number out of the package.json contained in the archive.
By passing the `--skip-dependencies` flag you can tell jspm that it shall skip caching the dependencies of that package.

Not sure if the `--offline` flag is really needed but it maybe helps to tell jspm that it shall use only the cache during installation and skip calling the version lookup and download function of the associated endpoint for a given package.

Would that be feasible or am I missing an important point?

**Comment by gabor-farkas** [comment]
I think jspm is not a good solution for this requirement. Let me explain.
Suppose I have something called a "multi-module project" in terms of maven. That means that my application has multiple frontends (let's suppose it's a user frontend and an admin), which are separate web applications, but I'd like to reuse code between them. Thus I have folders:
* myapp-common-components
* myapp-web
* myapp-admin
Both myapp-web and myapp-admin are indivudal web applications, with an own package.json, own dependencies and stuff. But they would both like to use code from myapp-common-components.

On my development machine I can of course use linking to ensure that the locally built latest myapp-common-components will be used by both apps.

This makes dev environment setup and automatic building more difficult, because I need to create a build script that does this linking.

But due to the fact that the link registry is global, we cannot use this solution with CI environments (jenkins for example), where multiple parallel builds of different branches of the same project must be supported. Builds would just randomly fail due to differing versions between branches.

If installing from a folder or achive was supported, a cleaner scenario would be:
* the build script builds myapp-common-components that properly creates the distribution as if myapp-common-components was an individual github repo (but we don't have to commit, push, tag, etc...)
* then when the script builds myapp-web, the 'jspm install' command should update the dependency from the local folder (with maven, -SNAPSHOT versions are automatically updated, while released versions are never updated)

What do you think?

**Comment by guybedford** [comment]
@gabor-farkas if and when we support offline installs, the local cache of the package could be used as the source of truth for installing local packages that have been rebuilt and published "locally", allowing to skip the network stage. Perhaps that would work with this workflow.

**Comment by gabor-farkas** [comment]
@guybedford sounds cool, that would be quite similar to how java maven projects are built.

**Comment by duranmg** [comment]
was there ever a solution for offilne installs?  i ran into a situation where i'm trying to install to several offline servers... an offline option would be great
