### ISSUE TITLE
0.16.0: jspm build command fails

### ISSUE THREAD

**Issue by OrKoN** [jspm/jspm-cli#1030]
In a new jspm project:

```
$ jspm build
Transpile ES6? [yes]:
Minify? [yes]:no

err  AssertionError: rimraf: missing path
         at rimraf (/home/alex/.npm-packages/lib/node_modules/jspm/node_modules/rimraf/rimraf.js:47:3)
         at lib$rsvp$node$$tryApply (/home/alex/.npm-packages/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1376:11)
         at lib$rsvp$node$$handleValueInput (/home/alex/.npm-packages/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1476:20)
         at fn (/home/alex/.npm-packages/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1464:18)
         at /home/alex/.npm-packages/lib/node_modules/jspm/lib/core.js:93:23
         at runMicrotasksCallback (node.js:337:7)
         at process._tickCallback (node.js:355:11)
````

P.S. is it documented somewhere?

**Comment by guybedford** [comment]
This used to be used to provide transpilation, but has been left to deprecate. We can get this function going again for 0.17 though.

**Comment by jatsrt** [comment]
So, as a new user, that is getting this same error, is there a workaround?

**Comment by whistler** [comment]
@jatsrt you probably want to use the jspm bundle command instead

**Comment by masaeedu** [comment]
@whistler Yes, but that command no longer asks you whether you want to compile ES6, it just chokes when it encounters it. How do I compile my ES6?

**Comment by whistler** [comment]
@masaeedu It doesn't ask the question again because it generates configuration files(package.json/config.js) that save your selection. 

The original bug report uses the `jspm build` command which I am not sure should still be used, I was not able to find documentation for it, but running `jspm bundle` to build produces the above error if the command is not provided further arguments i.e. the names of the source file and the destination file: `jspm bundle app/main build.js`.

**Comment by jperl** [comment]
Does bundle optimize with rollup? The [docs say](http://jspm.io/0.17-beta-guide/static-builds-with-rollup-optimization.html) to use `jspm build` for that?

**Comment by jperl** [comment]
Never mind -- this bug does not happen for me in `0.17.0-beta.29`.
