### ISSUE TITLE
Bundled output generates `System is not defined error`

### ISSUE THREAD

**Issue by lookfirst** [jspm/jspm-cli#1032]
I reverted to b6 and I'm still seeing this error regardless of v16.0 or b6.

This is some of the minified/bundled code. I used chrome devtools to make it readable. I have to replace the `System` with `$__System` and things work fine.

```
	$__System.registerDynamic("58", ["7e"], !0, function(require, e, t) {
		var n = this
		  , r = n.define;
		return n.define = void 0,
		t.exports = System._nodeRequire ? process : require("7e"),
		n.define = r,
		t.exports
	}
	),
```

**Comment by emirotin** [comment]
Yeah got the same error

**Comment by lookfirst** [comment]
I'm using gulp-replace and this to `fix` it...

```
			.pipe(replace('exports=System', 'exports=$__System'))
			.pipe(replace('module.exports = System', 'module.exports=$__System'))
```

**Comment by lookfirst** [comment]
Handles both cases of minifcation

**Comment by guybedford** [comment]
@lookfirst is this an SFX or normal bundle?

**Comment by lookfirst** [comment]
```
import {Builder} from 'jspm';
let bundler = (app) => {
	let builder = new Builder();
	return builder.buildSFX(`js/${app}/app`, `${path.war}/js/${app}/${app}-bundle.js`,
		{minify: situation.isProduction() || situation.isDemo(), sourceMaps: false});
};
```

**Comment by guybedford** [comment]
Why do you need a handle to the System object in your sfx build?

**Comment by lookfirst** [comment]
I don't! That code is inserted somewhere... it isn't mine.

**Comment by lookfirst** [comment]
Looks like something related to `process`?

**Comment by guybedford** [comment]
@lookfirst I've pushed an experimental fix in https://github.com/systemjs/builder/commit/472a8c891068decea289479d54fcee292ea8c621, let me know if that works for you?

**Comment by OrKoN** [comment]
I have this issue too,

**Comment by guybedford** [comment]
Thanks, I've released the fix for this, let me know if you have any further issues at all.

**Comment by lookfirst** [comment]
@guybedford confirmed

**Comment by michaelfranzl** [comment]
I get the same error with jspm version 0.16.53 for the following use case. I _intentionally_ want to load (big) scripts on demand, and rather not bundle everything together, so I load the big scripts in my code like this:

    System.import('blah').then(blah);

After running `jspm bundle-sfx`, the generated build does not define `System`, so I get the error mentioned in the title of this issue.

If I additionally include `system.js`, it works, however then the bundle can no longer be considered "self extracting".

Since I am new to jspm, maybe I am missing something?
