### ISSUE TITLE
jspm install npm:... installs redundant node packages

### ISSUE THREAD

**Issue by neothemachine** [jspm/jspm-cli#1067]
When I do `jspm install npm:leaflet` I see that it automatically adds a bunch of dependencies which get installed:
```
    "fs": "github:jspm/nodelibs-fs@^0.1.0",
    "zlib": "github:jspm/nodelibs-zlib@^0.1.0",
    "process": "github:jspm/nodelibs-process@^0.1.0",
    "buffer": "github:jspm/nodelibs-buffer@^0.1.0",
    "crypto": "github:jspm/nodelibs-crypto@^0.1.0",
    "path": "github:jspm/nodelibs-path@^0.1.0",
    "util": "github:jspm/nodelibs-util@^0.1.0"
```
When I do `jspm install github:Leaflet/Leaflet` this is not the case.

I think this should not happen by default for any npm package. npm != Node Package Manager! If any of the node packages are required then they should be specified in an override.

**Comment by guybedford** [comment]
These files are downloaded because there are requires to them in the npm:leaflet package test folders or other folders. We can use an override to restrict the dependencies to just those needed via `jspm install npm:leaflet -o "{dependencies:{}}"`. Let me know if that works for you here? If so we can check it into the registry for others to benefit as well.

Pending https://github.com/jspm/jspm-cli/issues/345 which will come with 0.17, we can actually handle this process with an easier override like `jspm install npm:leaflet -o "{files: ['dist']}"`.

**Comment by neothemachine** [comment]
Ah I see, and when it's installed as `github:Leaflet/Leaflet` then it doesn't scan for those built-in node modules since it doesn't assume it is a npm package.
I tried `-o "{dependencies:{}}"` but it didn't change anything.

By the way, I really like that a `jspm uninstall ..` also uninstalls all obsolete dependencies, very clever!

**Comment by guybedford** [comment]
Ah ok, it's because it's detecting the dependencies I guess. The `files` version will work pending 345, which I guess is the blocker for this then.
