### ISSUE TITLE
Ignore ENOENT when depcache

### ISSUE THREAD

**Issue by toddwong** [jspm/jspm-cli#1080]
They maybe dynamic modules which injected at runtime

**Comment by guybedford** [comment]
Some type of ability to automatically skip externals when tracing could be useful and is being tracked in https://github.com/systemjs/builder/issues/269.

**Comment by OliverJAsh** [comment]
I believe I am also having this issue:

```
~/Development/frontend oja-xwords-missing-clue*
$ jspm --version
0.16.2
Running against local jspm install.

~/Development/frontend oja-xwords-missing-clue*
$ jspm depcache bootstraps/app
     Injecting the traced dependency tree for bootstraps/app...

err  Error: ENOENT, open '/Users/OliverJAsh/Development/frontend/static/src/javascripts/projects/common/views/international-message.html.js'
         at Error (native)
	Error loading file:///Users/OliverJAsh/Development/frontend/static/src/javascripts/projects/common/views/international-message.html.js
```

**Comment by guybedford** [comment]
@OliverJAsh it's saying error loading `file:///Users/OliverJAsh/Development/frontend/static/src/javascripts/projects/common/views/international-message.html.js`, without any plugin syntax at all present, which means it would be an import like `import 'international-message.html'` surely instead of `import 'international-message.html!'` here? Let me know if that is not the case though.

**Comment by OliverJAsh** [comment]
I am importing `text!common/views/international-message.html` which gets normalized to `common/views/international-message.html!text`. `text` is this plugin: https://github.com/systemjs/plugin-text

**Comment by guybedford** [comment]
@OliverJAsh it would really help if you can share a replication here. A naive `jspm depcache 'test/message.html!text' works fine for me.

**Comment by OliverJAsh** [comment]
This seems to be happening because of my normalization step:

If I do `jspm depcache` on `import foo from 'bar.html!text';`, it works. If I try the same on `import foo from 'text!bar.html';` where I have a normalization function that transforms this into `bar.html!text` (see below), then it fails.

Here is my normalize function:


``` js
    function reversePluginFormat(name) {
        var destructuredName = /(.+?)!(.+)/.exec(name);

        if (destructuredName) {
            var pluginName = destructuredName[1];
            var moduleId = destructuredName[2];
            var newName = moduleId + '!' + pluginName;

            return newName;
        } else {
            return name;
        }
    }

    var systemNormalize = System.normalize;
    System.normalize = function (name, parentName) {
        var newName = reversePluginFormat(name)

        return systemNormalize.call(this, newName, parentName);
    };
```

**Comment by guybedford** [comment]
Did you try using the `System.pluginFirst` feature that handles this reversing internally now? It comes with its own build support which seems like what is lacking here.

**Comment by OliverJAsh** [comment]
Nope, I didn't see that. I will give it a go.

In any case, shouldn't depcache honour the normalize function?

**Comment by guybedford** [comment]
@OliverJAsh how are you setting the custom normalize function? It may not be applying to the builder properly without having a custom build script to ensure you're patching it in?

**Comment by OliverJAsh** [comment]
Ah! Of course, I've just realised there's no way jspm depcache would know
about the normalise. I am indeed patching it in for my builds.
