### ISSUE TITLE
re-generate config.js

### ISSUE THREAD

**Issue by chovy** [jspm/jspm-cli#1088]
My config.js is all messed up. Had a merge conflict on every line. Can I delete and re-generate it? My package.json is fine.

**Comment by guybedford** [comment]
@chovy the config can regenerate fine, but you will be running a new best version solution to your package install ranges instead of your original proven version lock. This is what npm does by default, and in most cases it will be fine, but if there are bugs you can restore the config file and run `jspm install` to revert.
