### ISSUE TITLE
sass.js can not be bundled

### ISSUE THREAD

**Issue by screendriver** [jspm/jspm-cli#1100]
If I try to bundle [sass.js](https://github.com/medialize/sass.js) and try to run the bundled code in the browser I get a 404 in my error console

```
http://localhost:3000/jspm_packages/npm/sass.js@0.9.2/dist/libsass.js.mem
```
It seems that sass.js tries to dynamically download this file at runtime and jspm has not bundled it. Is there an option in `jspm bundle` or in my `config.js` where I can include this? Or I am completely wrong here and there is something different wrong?

You can easily reproduce this. Just make a simple script like this one and bundle it:

```js
import sass from 'sass.js';

sass.compile('body { background-color: red }', result => {
  console.info(result);
});
```

**Comment by guybedford** [comment]
It looks like you made some progress here? Let me know if this is still an issue.

**Comment by screendriver** [comment]
Yes I did it. But not as mentioned above. If you make a bundle I do not include `sass.js` for runtime. I transpile all SASS files first to CSS and only include that CSS in the bundle.

The issue above however still exist if some library reload something dynamically without `require()` or `import` it.

BTW: I really made a lot of copy and paste on existing plugins because there is no documentation for how to write code for bundling (e.g. `if (typeof window !== 'undefined')` and `exports.bundle` and `"System\.register('" + load.name + "', [], false, function() {});";` and so on) :disappointed:

**Comment by guybedford** [comment]
How would the request to `sass/dist/libsass.js.mem` have been made if not via `require`? It might have been a compatibility issue with SystemJS not detecting the require correctly during dependency tracing? In which case that can be fixed by explicitly adding it with deps metadata.

Glad to hear you worked out the `bundle` hook. Usually plugins only use a `transpile` hook to return a valid module, which will then get automatically set as a `System.register` named module. Returning an empty module in `translate` and then just returning a sass injection in the `bundle` hook should allow you not to need to output your own `System.register` code.

Just let me know if you have any further questions on this stuff at all.

**Comment by screendriver** [comment]
Unfortunately I don't know how they make a request for `sass/dist/libsass.js.mem`. I haven't looked into their source code. But if you are interessted it is really really easy to reproduce that. Just make a simple js file with that code snippet above and you get the error.

Stuff like that should be in the docs I think. The `transpile` hook is only for languages that are transpiled to JavaScript, right? So for any other plugins like managing styles, fonts, images and so on you have to use the `bundle` hook, right? If yes then there should be a lillte hint in the docs for "writing plugins" :wink:

**Comment by guybedford** [comment]
@screendriver this sounds like a problem with the `sass` override. I've posted a registry issue at https://github.com/jspm/registry/issues/562 for this. The `bundle` hook is undocumented as it is still somewhat experimental. It should be documented though when stable certainly.

**Comment by screendriver** [comment]
:+1: thank you for your help
