### ISSUE TITLE
Bring back `jspm compile`

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#1107]
Ideally it should have some caching magically being stored somewhere too, so it can be linked into a watch task on the app folder.

**Comment by stoiet** [comment]
Hy!

I am trying to set up a React project with JSPM. I would like to use browser-sync and gulp in my project for development and automation. Refreshing with browser-sync is slow unfortunately, but if i bundle babel + babel/polyfill, my application module dependencies (app/**/*.js - [app/**/*.js]) and my application modules ([app/**/*.js]), reload is much better. Browser just load 3 minified javascript files. (not using HTTP/2 supperted server yet)

I use a gulp task to watch my application modules, without its library dependencies and re-bundle it.
So i would like to my browser-sync task only to watch "application" bundle ([app/**/*.js]) file, because only this bundle changes many times.

Unfortunately, re-bundling without minification is still slow, so it would be nice some caching magic to reinject the changed file to the bundle, than write it to the disk.

Will it be possible with this feature or just give up my crazy plan?

Thanks!

**Comment by lookfirst** [comment]
@stoiet https://github.com/jspm/jspm-cli/issues/872#issuecomment-122990647

**Comment by stoiet** [comment]
@lookfirst Thanks! I tried your solution before, but it didn't work for me. Tested with Chrome and Firefox Developer Edition, cache enabled in both of them. Browser-sync's version is 2.9.1. I don't understand either. I bundle babel and dependencies, only load own modules one by one, but browser reload everything after every changes.

Any tip what am i doing wrong?

**Comment by lookfirst** [comment]
Show me the proof. Did you uncheck 'Disable cache (while DevTools is open)'?

**Comment by stoiet** [comment]
My browser-sync config:
```
server: {
	baseDir: './client',
	index: 'index.html',
	proxy: {
        proxyRes: [expireHeaders]
    }
},
	files: './client/source/javascript/**/*.js',
	browser: ["firefox-dev"],
	minify: false
```

![Image of Network](http://s7.postimg.org/9kmjzq22z/network.png)

**Comment by lookfirst** [comment]
Please answer the question and that screenshot is hardly proof of anything.

What you need to prove is that you only see 200 responses from the server on a page reload and do not see the cache headers doing their magic.

**Comment by stoiet** [comment]
Yes, I unchecked the 'Disable cache', but javascript files doesnt come from cache: ![Network](http://postimg.org/image/t4ux4bgxl/)
And the Response headers doesnt seem to be right: ![Headers](http://postimg.org/image/ua1wbkzy3/)

I believe i missed something, just try to find out what.

**Comment by stoiet** [comment]
Pictures again:
![Network](http://i58.tinypic.com/suvj3r.png)
![Headers](http://i58.tinypic.com/302caid.jpg)

**Comment by lookfirst** [comment]
Bingo, proof it is working. 304 not modified means it is pulling from the browsers cache.

**Comment by stoiet** [comment]
I see, thank you. But 9 seconds reload delay is still too long, any suggestion to reduce it?

**Comment by lookfirst** [comment]
Buy a faster computer? This is what I'm getting for a single page of my app that has WAY more files than yours... http://take.ms/Wtjeb

**Comment by lookfirst** [comment]
I'm on a  2.6ghz 15" late 2013 macbook pro with builtin ssd and 16gb ram.

**Comment by lookfirst** [comment]
From your screenshot, it looks like bundle-dependency is taking 1.41s to return a 304 not modified header which is kind of absurd given that it is a 221byte response. 

Something is wrong with your computer.

**Comment by lookfirst** [comment]
What version of node are you running?

node --version
v0.12.7

**Comment by stoiet** [comment]
Nice! I am using iojs v3.3.0. I will try it on another, stronger computer.

**Comment by lookfirst** [comment]
Last time I tried iojs it failed miserably for me in random strange ways... Maybe 4.0 is better? That said, I'm just sticking with normal nodejs for a while... at least I know the ways it breaks... =)

**Comment by stoiet** [comment]
Hm, i don't know. I just started to use JavaScript on server side nowadays, i am a rookie in programming, too. But back to my original question, is it possible to manage bundling like i said?
I found ![this](https://github.com/systemjs/builder/blob/master/test/test-build-cache.js) on systemjs/builder repository, but it seems to me not well documented.

Moreover Dan Abramov's video about redux-tools and react-hot-reload is really interesting. (because i would like to use redux as flux implementation). https://www.youtube.com/watch?v=xsSnOQynTHs Can we achieve the same with JSPM in the future? (I think react-hot-reload is a hack and only works with Webpack, but something similar with JSPM?)

**Comment by guybedford** [comment]
Yes the separate file workflows are still being optimized by browsers. For example, I found recently just updating to Chrome canary a full 1s improvement in separate-file load time.

Hot reloading workflows in-browser and development server workflows are all on the roadmap, it will just take time for these to mature.
