### ISSUE TITLE
Bundle error when using substract arithmetic

### ISSUE THREAD

**Issue by Gu1** [jspm/jspm-cli#1128]
I did a small test case there:
https://github.com/Gu1/jspm-issue-1128-test-case
(just run "make" to execute it)

Basically, when trying to use arithmetic to create a bundle that won't contain libraries included in another bundle (entrypoint.js - existing_bundle.js), I get an error:

`err  TypeError: Cannot read property 'createElement' of undefined
	Evaluating file:///home/bla/jspm-issue-1128-test-case
/a_bundle.js`

I tried it with jspm 0.16.2 (systemjs-builder 0.13.5 and 0.13.6).

**Comment by guybedford** [comment]
Thanks so much for posting this test case, this is actually already fixed in the SystemJS 0.19 release pending, and can be tested by installing SystemJS to master within jspm/node_modules/systemjs-builder/node_modules/systemjs.

Hoping to post out the 0.19 SystemJS release with a jspm patch very soon.

**Comment by guybedford** [comment]
I added a fix in SystemJS for an edge case here in https://github.com/systemjs/systemjs/commit/af02c2392847874f739ccddab5e9a24a7c092df5, and have included a test case as well in https://github.com/systemjs/builder/commit/d2e7878cd919b12e86729ef6b829c3182a748c28.

This should definitely be working against the SystemJS master now.

**Comment by guybedford** [comment]
Released in 0.16.3.
