### ISSUE TITLE
Can't load file from branch with escaped "/"?

### ISSUE THREAD

**Issue by peteruithoven** [jspm/jspm-cli#1153]
I'm trying to use the `feature/no-dom` branch of `github:Legitcode/tests`, but SystemJS can't load it's files. 
I've installed it using `jspm install legit-tests=github:Legitcode/tests@feature/no-dom -o "{ main:'src/no-dom.js'}"`. I'm importing it with `import Test from 'legit-tests'`. Now it's trying to load the following url
```
http://localhost:3000/jspm_packages/github/Legitcode/tests@feature%2Fno-dom.js
```
But it can't find the file, maybe because of the `%2F` part?

I could probably also skip the main override and load import `legit-tests/src/no-dom.js` but that doesn't seem to fix the problem.

**Comment by guybedford** [comment]
Thanks, the original work at https://github.com/jspm/jspm-cli/commit/1d6ac38afef88cad65107928a90a54370951f3be isn't sufficient because URL encoding obviously doesn't work for the browser.

I'm thinking of altering the scheme to be percent-encoding, but subbing the percent for `~`. The thing is, we need to ensure better separation of escaped and unescaped version strings here in the Registry API for this to work out.

**Comment by peteruithoven** [comment]
It's doesn't fix this issue, but I've been able to load [legit-tests](https://github.com/Legitcode/tests) using a specific npm tag: https://github.com/Legitcode/tests/issues/14#issuecomment-142908028

**Comment by guybedford** [comment]
Tracking at https://github.com/jspm/jspm-cli/issues/1153.
