### ISSUE TITLE
Why install packages with jspm?  Can't npm do everything it can already?

### ISSUE THREAD

**Issue by jedwards1211** [jspm/jspm-cli#1169]
I have been using npm as my browser package manager for almost a year.  Why has this idea that a browser-specific package manager is necessary persisted?

**Comment by guybedford** [comment]
It sounds like you're feeling pressured into learning about jspm when you don't want to. I'd strongly suggest ignoring the project if that is the case, unless you are genuinely interested in it.

It's basically building package management around a fine-grained module registry that does dynamic linking driven by the browser instead of the static linking at build time to move Node code into the browser.

**Comment by jedwards1211** [comment]
It's true, I do feel anxiety that I'll constantly have to change my workflow.  On the other hand, I haven't yet found a truly enlightening discussion of what benefits jspm/SystemJS has over Webpack, or what jspm can provide above and beyond npm, and I assume you have good reasons to spend time on this, so I'm trying to get a deeper understanding

**Comment by arthurmuchir** [comment]
@jedwards1211 You can see https://github.com/jspm/jspm-cli/issues/33 for more informations. I was asking myself the same question.
