### ISSUE TITLE
use a jspm.json file

### ISSUE THREAD

**Issue by rolandjitsu** [jspm/jspm-cli#1178]
I really do not understand why it does not use a `jspm.json` file, like all the other package managers. Because I do not want to pollute `package.json` with things that are not npm specific, that file belongs to npm and nothing else should be in there.

**Comment by guybedford** [comment]
The argument against this is that having lots of separate `.json` files is littering packages as well. Note that `package.json` is a CommonJS spec and Node and npm don't discourage other projects adding properties to it.

**Comment by lookfirst** [comment]
:+1: @guybedford !!!!

**Comment by rolandjitsu** [comment]
@guybedford I understand, I suppose it's a matter of dev preference to keep things separate. I prefer to have more files that serve a single purpose :)

Anyway, it would have been nice to have the feature and then let the developer decide whether the config should go along `package.json` or in it's own file.

**Comment by GongT** [comment]
+1

in 0.17.0-beta.32, more properties added into package.json, and "overrides" field is so big.

**Comment by aluanhaddad** [comment]
@GongT As you know, the default behavior is to prefix everything under a single property `"jspm"` property in package.json. As most text editors support collapsing blocks within JSON files, I don't see the additional overrides as a problem.

One thing which JavaScript lacks is a well defined _project_ system. Adding more individual files do not help with that they actually make things more complex.

Anyway, here is an example of why this is good (tooling)
![image](https://cloud.githubusercontent.com/assets/5034656/22061537/5745f4ce-dd43-11e6-9f3b-7f19d91cca38.png)

Note I can leverage the Version Lens plugin for VS Code. It was easy for the authors to add JSPM support because the deps are defined in package.json. This plugin is seriously useful.
