### ISSUE TITLE
Unable to calculate canonical name to bundle file

### ISSUE THREAD

**Issue by alvipeo** [jspm/jspm-cli#1238]
I think my issue is not very original. I have a VS2015 project with React + Typescript, etc. Since VS can automatically compile typescript to js automatically on save I use it. And my project has the following folder structure:
- root
  - wwwroot (*what will actually be served by iis*)
    - js (__[3] bundled__ *code should go here*)
      - vendor (*where all jspm packages go*)
      - config.js (*jspm config*)
    - index.html
  - build (*all __[2] transpiled__ js*)
  - scripts (*all* __[1] typescript source code__)
  - gulpfile.js, package.json, etc

So here's the workflow: **1)** .ts file changes in scripts folder -> **2)** gets compiled to .js and put to build folder -> **3)** gulp_jspm task runs and should put bundled js code into wwwroot/js.

Now, here's my package.json:
```
{
  "version": "1.0.0",
  "name": "ASP.NET",
  "private": true,
  "devDependencies": {
    ...
  },
  "jspm": {
    "directories": {
      "baseURL": "wwwroot",
      "packages": "wwwroot/js/vendor"
    },
    "configFile": "wwwroot/js/config.js",
    "devDependencies": {}
  }
}
```
When I run gulp task:
```
gulp.task("jspm", function () {
	return gulp.src("./build/**/*.js")
		.pipe(gulp_jspm())
		.pipe(gulp.dest(paths.webroot + "js/"));
});
```
I get the following error:
*Unhandled rejection Error: Unable to calculate canonical name to bundle file:///[path]/../build/main.js*

Can I do something about it or should I put the build folder inside wwwroot? Which I wouldn't want to do because when website is published all these files would go out to the server.

**Comment by guybedford** [comment]
jspm can only bundle modules that are contained within the baseURL itself. Try setting the baseURL to a folder that includes the build folder within it.

**Comment by guybedford** [comment]
Just let me know if you need further help here at all.

**Comment by thecotne** [comment]
@guybedford i have same issue and as i understand i need to have bundled/transpiled code and source code in same directory and there is no other way
and i can't have src and dist folders?
i don't want to have source in web root

**Comment by guybedford** [comment]
@thecotne the baseURL just needs to be a reference path. If you serve your public folder as say `/static/...` to the browser, then your baseURL can be set to the folder below the public folder. The point is that the paths match up. jspm 0.17 will come with more flexibility here.

**Comment by mi2oon** [comment]
Hi there,

My package.json looks something else this:

```
"jspm": {
    "directories": {
      "baseURL": "Website/Content",
      "packages": "Website/Content/Scripts/Vendor"
    },
    "configFile": "Website/Scripts/system.config.js",
}
```

After I run jspm install my config file looks something else this.

```
System.config({
  baseURL: "/Content",
  paths: {
    "npm:*": "Scripts/Vendor/npm/*",
    "github:*": "Scripts/Vendor/github/*"
  }
}
```

I am a core.js file that needs to be bundle so I use the similar gulp setup is described above. Which gives the errors as titled. I understand it's because the it can only bundle modules that are inside baseURL. Since my baseURL is `Website/Content/` it can't find the core.js there and no bundle can be made.

If I then change the jspm config baseURL from `Website/Content` to `Website` the bundle is created but the systemjs config now has paths that looks something like this: `Content/Scripts/Vendor/npm*`

I have tried to change my systemjs config baseURL to just `/` then it seems like the modules get bundled but systemjs still fetches the modules from the content folder.

I think all this could simply be solved it I you set a root path in my systemjs config. So if the path could have a slash in front like this `/Content/Scripts/Vendor/npm*` but whenever I add this slash and run jspm install it ends up removing it. 

Anyway, hope you guys can help me out. Let me know if you need more info. Thanks :smile:
