### ISSUE TITLE
config path in command line

### ISSUE THREAD

**Issue by djindjic** [jspm/jspm-cli#1257]
Is it possible to pass config file path by command line to override package.json? Something like:

`jspm bundle app/main bundle.js --config 'path/to/custom/config.js' --inject --minify`

**Comment by ssljivic-vicert** [comment]
I also need this option in order to override configuration for specific build targets.

**Comment by guybedford** [comment]
Nice idea. I was thinking of doing a `jspm.build.js` or something like that, but inline could work too.

**Comment by douglasduteil** [comment]
:+1:

**Comment by douglasduteil** [comment]
And is it possible to output a new file from it ? Sot the config I use is not rewritten 
`jspm bundle app/main bundle.js --inject --minify --out-config 'path/to/new/injected/config.js' `

**Comment by cAhmad** [comment]
:+1: 
I have that kind of directory tree. 
```
-src/main/webapp
    |----admin
         |----admin.js
         |----index.html
         |----admin-config.js
    |----client
         |----client.js
    |----index.html
    |----config.js
    |----jspm-packages
-package.json
```
Maybe there is a better way to achieve this, (any hints is appreciated) but my `admin-config.js` is a copy of `client-config.js` with `baseURL: "../"` instead of `"./"` 
So bundling by giving a specific config file name may solve my issue for `admin` directory

**Comment by guybedford** [comment]
Supported in jspm 0.17 beta.
