### ISSUE TITLE
jspm install --offline

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#126]
Now that we have a full local registry, override and package cache, the last steps to an offline install are:
- Store the lookup result cache under `.jspm/lookup/endpoint/package/name.json`.
- Have `offline` as a global mode that can be enabled through an `--offline` flag for all commands.

**Comment by guybedford** [comment]
Closing as there hasn't been demand for this.

**Comment by subesokun** [comment]
Hi, actually I would require this feature now. I ran lately into the issue that you can't link packages in case you're offline.

**Comment by rojaro** [comment]
That would be an awesome feature. I am spending two hours and twenty minutes commuting every day and normally i use this time doing some programming. Unfortunately the internet connection in the trains is extremely bad and unreliable and i am offline for most of the distance. It would be awesome if i could run something like `jspm init --offline` and `jspm install --offline` and it would install only from the caches...

**Comment by m4r71n** [comment]
Offline installation would also be awesome for speeding up build times on ci-buildagents.

**Comment by Gu1** [comment]
Also interested by this.

**Comment by dguerizec** [comment]
Interested too, since we have to deal with strict proxies.

**Comment by guybedford** [comment]
Reopening as it finally looks like there is interest for this. It is not currently being prioritised. If anyone is interested in sponsoring such a feature that would certainly help motivate development as well.

**Comment by ErikGrijzen** [comment]
Thanks for reopening this issue. I would definitely like to see this functionality in the near future. In my opinion it doesn't make sense that build break or you can work on a project without an internet connection.

Please let me know how the sponsering works. I couldn't find anything about it in the wiki. Or let me know if I could help develop this feature.

**Comment by giovannicandido** [comment]
This is interesting, my ci server is broking sometimes

What would be nice is a locking mechanism combined with offline cache resolve.

This is the behaviour of some package managers I have worked. The workflow is like that:

* When installing, the package manage create a .lock file that simple contains the packages and versions it installed
* Successive installs will first look at the .lock file, and compare with the current installed packages, and will install only the ones that differs (simple to say, I don't think is so simple to implement)
* Another command like update, will ignore the lock file and update all dependencies using internet, and then rewrites the lock file again

I think that instead of make a file system lookup in jspm_packages directory to build the dependency version hash, it could be use the package.json file. The drawback is that the file need to be in sync with jspm_packages, maybe in some occasions this is not the true.

That way it solves two problems: Unnecessary internet connections, and continuous building. The cli server could run `jspm install` and be sure that it will only connect to internet if the .lock file change, namely, if the commit install or upgrade new stuff.

That combined with a offline cache for new installs and multiple project share, is, I think, a perfect solution/workflow

**Comment by giovannicandido** [comment]
Ok, I think jspm already have a lock mechanism, but my jspm install is trying to update the versions because of *^* in *package.json* version numbers. Example: *npm:aurelia-history@^1.0.0-beta.1*

Is that correct?

**Comment by teohhanhui** [comment]
@giovannicandido `jspm install` does not try to update anything. But currently it still needs to send HTTP requests (apparently)...

**Comment by guybedford** [comment]
`jspm install` will check the hashes of all installed packages to verify with certainty that the install is correct. If you want to skip hash checking you can use the `--quick` flag - `jspm install -q`.

**Comment by guybedford** [comment]
(of course there is more to offline support than just these requests though)

**Comment by Pleasurazy** [comment]
+1 👍 

BTW I have a opinion about

as @guybedford commented at https://github.com/jspm/jspm-cli/issues/1393#issuecomment-169011854
> Sure, I've just reopened #126.
> Note that in jspm 0.17 the CI limiting issues go away as well.

I think, the <kbd>deploy</kbd> process shouldn't depend with internet connections if our <kbd>deploy</kbd> didn't upgrade any package.

😓

**Comment by duranmg** [comment]
I would like the --offline option as well.

**Comment by abhipanda** [comment]
Hi @guybedford -  do we have a way forward on this ?

**Comment by code-d** [comment]
+1

**Comment by guybedford** [comment]
This is now supported in jspm 2.0.
