### ISSUE TITLE
jspm bundle / bundle-sfx `--exclude-external` flag

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#1277]

**Comment by vperron** [comment]
I would be SO fond of this !!!! :)

**Comment by siulung4073** [comment]
+1 this would be really cool

**Comment by guybedford** [comment]
@siulung4073 what would you expect this to exclude?

**Comment by siulung4073** [comment]
Hi @guybedford . As a external dependency I would say every package that is installed throw jspm, that has a version number, at least at first sight.

May be I'm wrong in why I want or need this. I was thinking about using the browser cache for external dependencies (jspm packages at least) and only bundling my code.
Because if I bundle everything together the browser has to download everything everytime. And what about if you have multiple dependencies like 10, you would end up with a bundle of 2 mb probably.

Do I have the concepts wrong? Is this not the right way to go? I tried to research about this, try to find any doc about this, but I wasn't lucky.
Thanks!

**Comment by guybedford** [comment]
@siulung4073 thanks for the feedback. So it may be better to do this the other way around - creating a bundle for external dependencies that stays the same, and then only dynamically loading your own code. This can be done via:

```
jspm bundle app/**/* - [app/**/*] external-deps.js -i
```

Which means bundle every dependency of every module in the app folder, except for every module in the app folder.

You can then use `external-deps.js` as a subtraction itself in further arithmetic to do an app bundle as well:

```
  jspm bundle app/**/* - external-deps.js app-bundle.js -i
```

Perhaps just carefully documenting these steps would be the best way for now.

**Comment by siulung4073** [comment]
@guybedford thanks for the rapid response. I'm not an expert on this, and I was trying to find the best way to bundle this thinking about performance and cache. Thats why I was confused about why this feature didn't exist and I couldn't find info about browser cache, bundling, performances and best practices.

So as a best practice you think its better to bundle everything together and let the browser cache one file, or to bundle all the external dependecies separately and have two bundles like you said or to let them undunble? What would be the way to go or the stardard?

thanks again! I think a better doc about this, would be great

**Comment by guybedford** [comment]
Development and production have different needs, and there aren't standard workflows in jspm yet to handle these cases.

For development workflow, you might want to try https://github.com/capaj/systemjs-hot-reloader.

**Comment by siulung4073** [comment]
ok great, thanks. And for production workflows what would you say is the ideal approach?
sorry for so many questions, but i'm very new to bundling and thats why I'm kinda lost.

**Comment by guybedford** [comment]
Sure, just make sure everything is in a bundle for production.

**Comment by mgamsjager** [comment]
This doesn't really seem to work with Angular2 beta. The bundle is created and inject but every single js file is still loaded.
