### ISSUE TITLE
Should config.js be deleted before any update of package.json

### ISSUE THREAD

**Issue by adriatic** [jspm/jspm-cli#1306]
Assume the situation where `config.js` already exists, meaning that the `jspm install` command was run at least once.

In this situation, I update the jspm section of the 'package.json' file and run `jspm install` command and as a consequence, jspm updates the config.js file. Is it safe to expect that the updated `config.js` is consistent with the current `package.json` - or am I better off if I delete `config.js` before running `jspm install` command.

I am pretty sure that without deleting `config.js` before each update of `package.json` my app misbehaved.

**Comment by OrKoN** [comment]
@adriatic Run `jspm update` after you modified `package.json` instead of running `jspm install`. `jspm install` will not install newer versions - it only installs what's listed in the `config.js`. `jspm update` will install newer versions as per `package.json` and it will update `config.js`. You can also update a single module using `jspm update moduleName`. E.g. `jspm update jquery`.

**Comment by adriatic** [comment]
> instead of running jspm install. jspm install will not install newer versions - it only installs what's listed in the config.js

Perfect answer - based on own experience, I should have thought that there is something like `update` argument :-). However seeing how many people in my Aurelia neighborhood do not know about this option, I wonder whether `jspm-cli` should make this feature more obvious.

Thank you @OrKoN !!
