### ISSUE TITLE
Need for dependencies when bundling?

### ISSUE THREAD

**Issue by peterjuras** [jspm/jspm-cli#1323]
Hi!

I'm having a hard time understanding the differentiation between dependencies and devDependencies for jspm.

For node modules it's simple: dependencies are actively used by the node modules when they are executed, whereas devDependencies are only needed to build, lint or test the node modules.

For jspm however, a bundle command will put all required dependencies by the entry point into the bundle (regardless whether devDep or normal dep) anyways. So what's the use case for devDependencies?

I could see where it would be useful if you are writing a jspm module that should be used in another module, to e.g. not have lodash bundled into my module but also required by another. However, I'm currently building a website with jspm which will not be used as a module and the output will be bundled. Does it make any difference for my case to use dependencies over devDependencies? (or vice versa)

Thanks so much, jspm really has really come a long way! =)

**Comment by jackfranklin** [comment]
I'm obviously not the authority on this but it's mainly for organising code. As you said, because the bundle is generated by tracing the tree it doesn't really make much difference.

As of https://github.com/jspm/jspm-cli/pull/1320, once that makes it into a release you'll be able to do `jspm install --production` to only install dependencies, not devDeps, which may be occasionally useful if you want to only install dependencies to quickly run the app locally, or if you're running the app on a CI server, etc.

**Comment by peterjuras** [comment]
I was also thinking about a similar example, but this is exactly a case where your code often wouldn't run properly anymore since e.g. babel is a devDependency by default.

As soon as you import any module with a import x from y statement it will look for the babel compiler which hasn't been installed in a --production install.

**Comment by screendriver** [comment]
Babel and other transpilers will be seperated into external jspm [plugins](https://github.com/systemjs/systemjs/issues/579) so they will treated differently in the future. For example: [plugin-babel](https://github.com/systemjs/plugin-babel)

**Comment by guybedford** [comment]
`devDependencies` is exactly the same as the npm meaning though - that which is needed only for development. Ideally we would have a production mode where everything is already precompiled and there is no need to use the transpiler, but I understand that since all workflows need the devDependencies today it may not seem like an obvious distinction.
