### ISSUE TITLE
disable flat dependencies

### ISSUE THREAD

**Issue by dominictarr** [jspm/jspm-cli#1335]
Is it possible for this to not support flat dependencies?
In on the website it says:
"Shares versions between dependencies, upgrading or downgrading dependency resolutions within their supported ranges to minimize forks during install."
by forks are you refering to multiple versions of one dependency? are these still supported? What happens if it can't find a version that all the modules can agree on?

Downgrading a dependency because it depends on another dependency very surprising when it happens to you. Developers do not test their module with all the versions the range says it accepts, so no gaurantee that works.

Flat dependencies to get you less code to download, but it's better to have more code that works rather than less code that is broken.

The only time you actually need a flat dependency tree is when you have modules that need to be singletons. (for example they do `instanceof` checks) However in that case you it would probably be better to have single out the modules that need to be treated as singletons and ensure there is only one version of that module rather than force every module to be a singleton.

**Comment by guybedford** [comment]
Thanks for checking it out. Yes forks refer to multiple version of the same package. We distinguish though between "primary" installs (that I've explicitly installed myself), which are never downgraded from the latest range, and "secondary" installs (a dependency that is not a primary install), which are allowed to downgrade if something else also uses it but can't use the latest version due to say `~1.2.3` style locks. Dependencies are always kept within their allowed ranges though.

The result is we minimize package duplication roughly similarly to npm, and then support multiple versions of the same package to run together in the same app, because the flat folder structure uses versioned folder names (`jspm_packages/npm/lodash@2.3.4/`).

Singleton style modules can be supported via peer dependencies, which are not allowed to fork, just like in npm (supported in jspm 0.17).

**Comment by dominictarr** [comment]
oh, so you do actually support multiple versions? that is good news. If the architecture supports that, I'm happy. It means it would be easy to disable downgrading if it does turn out to be a bad idea.

**Comment by guybedford** [comment]
Yes exactly. There is also an option `--latest` on install which tells jspm to always install the latest version of everything regardless of duplication.

**Comment by dominictarr** [comment]
I assume you mean the latest version in the acceptable range?

**Comment by guybedford** [comment]
Yes, ranges are always respected, unless you manually edit the config.js resolution file.
