### ISSUE TITLE
Version locking and upgrade paths

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#1400]
When a dependency upgrades from one version to the next, we lose any custom lock that was existing for the previous version. Say I had set dependency `x` to a local custom map instead of its expected range.

The way to handle this would be to alter the "upgrade" process to maintain any out-of-range locks in the new version.

Version pinning is a little harder. Say for example I pin dependency `x` to `1.2.3`, while the latest version is `1.2.5`. When `y` which depends on `x` updates, we would still lose the version pin of `x` to `1.2.3`.

Without introducing custom syntax for the version pin, the only way to handle this would be via always maintaining the locks from the previous version of an updated library.

If we do that though, we have a chance of introducing forks, but these would resolve with an `update` command. Perhaps update pinning could then mitigate changes `jspm update y --lock x`.

**Comment by guybedford** [comment]
Perhaps upgrade path version pinning to exact install ranges isn't that important though, and the out-of-range adjustments are the main thing to capture as described first.

**Comment by mikz** [comment]
I might be totally off topic, but I'd like to say that using [Bundler](http://bundler.io/) for many years, is a pleasant experience.
It has a `Gemfile` that contains your dependencies, but not the peer. To lock peer dependencies, you can add them there and set a version constraint. After installing, it creates `Gemfile.lock` which has the whole dependency tree locked to specific versions.
Now when doing update, you can update all or just one dependency (but still maintaining the constraint in Gemfile, because that one is not automatically rewritten).
When you bump dependency in `Gemfile` and do install, it will automatically try to install just that dependency. You also have a `--deployment` option that prevents installing any other version, than in the lockfile. Hope it is useful :)

**Comment by guybedford** [comment]
@mikz jspm works exactly like that. Just replace lockfile with `jspm.config.js`.

**Comment by mikz** [comment]
@guybedford then I don't understand what is the problem in this issue. If want to lock peer dependency, just add it to as my dependency and lock the version. I probably don't know enough about jspm/systemjs internals to see the issue.

**Comment by guybedford** [comment]
@mikz this is specifically about cases for respecting locks of dependencies while upgrading the parent.
