### ISSUE TITLE
Expose config load / save APIs

### ISSUE THREAD

**Issue by ahmedshuhel** [jspm/jspm-cli#1407]
This is formatting of the `config.js` after jspm creates it. The top-level keys are not quoted (`".."`). 

``` javascript
System.config({
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "es7.decorators",
      "es7.classProperties"
    ]
  },
```

Is there any specific reason for that? The code below looks more consistent and the option object is a valid JSON.

``` javascript
System.config({
  "defaultJSExtensions": true,
  "transpiler": "babel",
  "babelOptions": {
    "optional": [
      "es7.decorators",
      "es7.classProperties"
    ]
  },
```

**Comment by guybedford** [comment]
Yes, jspm alters the config file for readability. The config file is not a JSON format.

If you're trying to load the config, the way to do this in jspm is through the API at https://github.com/jspm/jspm-cli/blob/master/docs/api.md#class-builder which will handle config loading for you, rather than using SystemJS builder directly.

Also SystemJS builder comes with a loadConfig method which can be used to load these style of files as well.

**Comment by ahmedshuhel** [comment]
We are actually using systemjs-builder directly. As systemjs-builder does not support bundle injection, we had a [simple implementation](https://github.com/aurelia/bundler/blob/master/lib/config-serializer.js) for that. We are doing the serialization via `JSON.stringify()` and de-serialization via `vm` module. (Ultimate goal was to make a PR for `systemjs-builder`)

We are having these quotes around the  top level keys  because of the way `JSON.strignify` works. And, this creates some unnecessary  `git diff` issue as `jspm` does not quote the top level keys.

Could you please suggest any other way to do this without using jspm/jspm api and still be compatible with `jspm`?

**Comment by guybedford** [comment]
@ahmedshuhel this is actually a good argument for opening up the config file save and load API through the jspm API.

With `config.save` and `config.loader.baseURL` etc access. I've updated the issue to reflect this.

In the mean time, the config rewriting we do is simply this line - https://github.com/jspm/jspm-cli/blob/master/lib/config/loader.js#L373.

**Comment by ahmedshuhel** [comment]
Thank your for your time.

**Comment by salfield** [comment]
This would be very useful. I currently want to be able to alter the config file from a gulp process, before bundling and injecting. I'm left with two options:
a) Use `jspm.bundle`, in which case I can't alter the configuration without using something similar to @ahmedshuhel .
b) Use `jspm.Builder` which doesn't allow me to inject the bundle into config.js.

It seems to me that an equally good solution to exposing load/save APIs would be to abstract out the bundle injection code from `jspm.bundle`, so it is usable with the `jspm.Builder`/`systemjs-builder`.  It also might makes sense for this functionality to be a part of SystemJS.

**Comment by guybedford** [comment]
For custom tools, the best approach in the mean time is probably just config concatenation - concatenating the config file with other production configs.

**Comment by salfield** [comment]
Maybe I miss the point, but I can only concatenate the config if I can read it - and since it is not JSON and it is all wrapped in `System.config` call it is pretty awkward to read.

I've used a similar approach to @ahmedshuhel and the problem is solved for now, but would be better if the load/save API or bundle injection was exposed.

For the record I want to change a "config.map" variable, so it is possible for my plugin to load an override  file from a different location depending on the site. Here is the plugin:

https://github.com/wikifactory/plugin-yaml/blob/master/yaml.js

**Comment by guybedford** [comment]
@salfield configs merge, so you could concatenate into a file like:

```javascript
System.config({
  // ... jspm config unchanged ...
});

// concatted:
System.config({
  map: {
    // ... custom map ...
  }
});
```

**Comment by peteruithoven** [comment]
This would enable us to programmatically add for example plugin configuration or babelOptions? 
That would be awesome! Especially if this would be possible with cli commands. For comparison, I'm currently using [json](https://www.npmjs.com/package/json) to automatically add a npm start script:
```
json -I -f package.json -e 'this.scripts.start = "jspm bundle src/index.js -wid & serve & chokidar-socket-emitter"'
```
