### ISSUE TITLE
Load individual files in production

### ISSUE THREAD

**Issue by ineentho** [jspm/jspm-cli#1409]
[production-workflows.md](https://github.com/jspm/jspm-cli/blob/master/docs/production-workflows.md) does not describe a workflow for transpiling and minifying each file indivudually.

"Creating a Dependency Cache" solves a part of the problem, so I'm finding it strange that there's no mention on how to run the transpiling part.

Isn't serving individual files supported yet? If not, I'd think it's time soon since nginx has supported http2 for a few months, and browser support for http2 isn't bad at all.

**Comment by guybedford** [comment]
@ineentho good point. The reality at the moment is still unfortunately that browser can not load HTTP/2 as fast as bundles due to the way browsers themselves handle JS execution not being optimized for this. That is, despite HTTP/2 adoption, we still need to wait and see how well browsers can optimize these cases (and I'm hopeful that now they are aware of the importance of the use case, they may be able to consider moving in these directions).

As for the separate file workflow in jspm, yes a `jspm compile dir` is very much the idea here, pending prioritisation.

**Comment by bronzehedwick** [comment]
I'm a little late, but I was also interested in serving individually bundled files for http2, but I didn't realize browsers did not load individual files over http2 as fast as a single bundle yet. 

Is the most performant option to serve the single bundle over http1.1 or http2?

**Comment by ineentho** [comment]
As far as I am aware there are no downsides to http2 compared to http1.1 - it's just not as big of an improvement it could be.

With a single file you probably won't see any significant gain with http2, but if your server is set up for http2 go for it.

**Comment by bronzehedwick** [comment]
Got it, thanks for the fast response!

**Comment by ghempton** [comment]
Has any more energy gone into this? This seems like a natural step for JSPM to "precompile" resources for production (and might speed up development as well).

**Comment by lcannon** [comment]
Has any work been done on this in jspm 0.17 beta? I read through the docs right now but didn't see any mention of this.

Cheers.

**Comment by ineentho** [comment]
I don't think much has been done yet (though I haven't been following that
closely). Guy's talk here http://guybedford.com/systemjs-alignment is
defenitly worth watching, but I think it's mostly ideas at this point
