### ISSUE TITLE
Is it possible to have a Dev and a Prod config for package?

### ISSUE THREAD

**Issue by AlexisBarta** [jspm/jspm-cli#1442]
What is the way to load a package `main.dev.js` while developping and 'main.prod.js` in production?

It could be nice to have an `--env` option with value "dev" and "prod" (default could be "prod") while building with ` jspm bundle` and `  jspm bundle-sfx` to define the environment. And based on that jspm will find the right source to use in config.js which will look something like that: 

```javascript
 map: {
   "whatever:module@0.0.1": {
        "main": {
            "dev": "path/main.dev.js",
            "prod": "path/main.prod.js"
        }
    }
}
```

**Comment by typhonrt** [comment]
@delux75  I know you came to JSPM via backbone-parse-es6. I solve this issue with TyphonJS repos using [typhonjs-core-gulptasks](https://www.npmjs.com/package/typhonjs-core-gulptasks) and specifically the `jspm-bundle` gulp task. Check the documentation and post an issue over on that repo if you need any additional help. Essentially you can setup an extra config file or directly include the overrides to load where you can redirect to a production version when bundling. 

Also check out the [backbone-parse-es6-todos-improved](https://github.com/typhonjs-demos/backbone-parse-es6-todos-improved/blob/master/indexSrc.html#L76) which shows loading extra JSPM config data when running in the browser. You could load additional dev or production mapped paths for testing and when bundling load the production paths. 

What you want to pull off is possible now without changes to JSPM / SystemJS.

**Comment by delux75** [comment]
Thanks for the tips @typhonrt ;) 

It's a shame that we have to use gulp for this. I feel that JSPM should handle prod/dev environment with the possibility to have at least one config file for dev and one for prod.

**Comment by typhonrt** [comment]
You don't have to use Gulp; I just happen to be doing that. This is a SystemJS / SystemJS Builder concern and not JSPM. With the Builder API you can load additional config files that provide different mappings or anything you'd put in `config.js`. I recommend the additional config loading approach rather than modifying the main `config.js` file. Here is an example on how to do it with the Builder API using `config` or `loadConfigSync` -- https://github.com/typhonjs/typhonjs-core-gulptasks/blob/master/tasks/jspm.js#L332-L350. When it comes to loading in the browser from non-transpiled sources you just load additional config files as necessary from script tags and would create an "indexDev.html" and "indexProd.html" files to load. I'm sure there are other ways to solve this problem as well. Documentation can be improved in general when it comes to production workflows.

**Comment by delux75** [comment]
Yes the documentation is really poor about "Production Workflows".

And while creating your own JSPM Builder seems to be a very good solution, it removes all the charm of JSPM and why most people used it in first place: "Simplicity"!

And I really think that having a dev and an prod environment is a requirement for a lot of developper and I feel that something should be done to make it easier.

Anyway, thank you for all the help ;)

**Comment by typhonrt** [comment]
The Builder API allows loading extra configuration files which provides any remapping. Doing that one can conditionally load dev or prod config data. I suppose one has to view JSPM and SystemJS as libraries versus a platform or fully featured framework. I can't speak for Guy et al or his long term intentions, but to me it seems a standard dev / prod option fits the latter (framework or platform). JSPM & SystemJS gives you very powerful libraries to mold into a thorough solution. And yes documentation could be better and likely will be in the coming year. It's worth the pain though! :D

With my efforts w/ TyphonJS (not released yet) I support various targets for deployment including a standard dev / stage / production setup including transferring assets directly from stage to production with a push of the button so to speak, but I've created a framework on top of JSPM / SystemJS.

**Comment by guybedford** [comment]
There is also a new `jspm bundle x --config ...` flag in jspm 0.17 allowing for inline JSON or a json file like with overrides.
