### ISSUE TITLE
0.17 source maps issue

### ISSUE THREAD

**Issue by frankwallis** [jspm/jspm-cli#1464]
I have been upgrading the plugin-typescript example projects to 0.17.0-beta.3, things have gone fairly smoothly and the angular1 and react projects are building & running fine. However, I am seeing an issue with the source maps 'jumping' and being unable to set breakpoints etc, which was not happening with 0.16.

The issue can be seen when running the ```react``` or ```angular``` examples in the [plugin-typescript](https://github.com/frankwallis/plugin-typescript/tree/0.17.0-beta#example-projects) repo. I will continue to investigate, but if you have any pointers for where the issue might be then please let me know.

Thanks for all your work.

EDIT: The updated examples are in the [0.17.0-beta](https://github.com/frankwallis/plugin-typescript/tree/0.17.0-beta) branch of that repository.

**Comment by guybedford** [comment]
Thanks, I will aim to have a look at the source maps, although do want to prioritise getting the release guide out first.

It may work differently outputting ES6 instead of System.register? If the plugin returns ES6 modules for builds (`this.builder === true`in the plugin hooks, where `this` is the loader instance for the plugin hooks), it will then immediately support the Rollup optimizations.

**Comment by guybedford** [comment]
I've just gone through the source maps can can confirm they're all working correctly in the browser and the builder, although the bulider source maps definitely seem to have incorrect offsets. From my testing it looks like this is somehow due to Traceur's handling of input source maps, which may have changed internally in Traceur. I think the best way to fix this is actually to switch internal transpilation transformers to all use Babel which we know handles input source maps correctly. Unfortunately I don't have time for this now, but it is tracking in https://github.com/systemjs/builder/issues/489.
