### ISSUE TITLE
0.16 to 0.17 beta upgrade total failure: jspm init loses all config

### ISSUE THREAD

**Issue by teohhanhui** [jspm/jspm-cli#1475]
Running `jspm init` (without the `-p` flag) creates empty (default) jspm.config.js and jspm.browser.js

:disappointed:

**Comment by teohhanhui** [comment]
Somehow, this was not triggered in my case:

https://github.com/jspm/jspm-cli/blob/0.17.0-beta.5/lib/config/index.js#L128-L134

**Comment by teohhanhui** [comment]
What is the proper upgrade procedure?

This is what I did:

1. `npm install --g jspm@"^0.17.0-beta.5"`
2. Bump `"jspm": "^0.17.0-beta.5"` in package.json
3. `npm install`
4. `jspm install` (Blame Docker... Could this be the cause of the problem? I actually expected this to fail, but it didn't...)
5. `jspm init`

**Comment by teohhanhui** [comment]
Tried it again without the `jspm install`, and with `jspm init --prompts`.

Still the same result... :disappointed:

**Comment by peteruithoven** [comment]
@teohhanhui, I'm afraid you're missing some npm basics.

`npm install` with the `-g` argument will install it globally, to update it specially for your project you should also install it without the `-g` argument. Then if you use the `--save--dev` / `-D` arguments, this automatically updates your package.json. 

`npm install` and `jspm install` are probably unnecessary, since this installs the dependencies mentioned in your package.json, which probably already happened. 

`jspm init` is usually only necessary when you're creating a new project and you want to use jspm in that project. 

You can more easily install the latest jspm-cli beta with `npm install -gjspm@beta`
https://github.com/jspm/jspm-cli/releases/tag/0.17.0-beta.4

Tip; check `jspm --help` and `npm --help`.

**Comment by teohhanhui** [comment]
@peteruithoven Thank you for your condescending tone. That's very helpful indeed!

/sarcasm

**Comment by teohhanhui** [comment]
For the record, I've already tried this:

1. `npm install --g jspm@"^0.17.0-beta.5"`
2. `npm install jspm@"^0.17.0-beta.5"`

And no upgrade process was triggered during the postinstall hook.

I'm still trying to figure out how to trigger the upgrade process.

**Comment by guybedford** [comment]
@teohhanhui your bug reports have been well explained and they are much appreciated, but please don't insult others in the issue queue, especially when they are trying to help. 

So the 0.17 upgrade will happen when:
* The package.json shows that the package is already jspm-aware by having a `registry` or `jspm` property.
* The `config.js` file is not empty
* You run `jspm install` or `jspm init`

If the above isn't triggering it, perhaps you can share the contents of your `package.json` and `config.js` file?

**Comment by teohhanhui** [comment]
@guybedford It was unfortunate that his comment came across the wrong way. My apologies...

My `package.json` and `public/config.js`: https://gist.github.com/teohhanhui/4002111fe55c0604dbc9

**Comment by guybedford** [comment]
@teohhanhui sure no problem. I think I've fixed this in https://github.com/jspm/jspm-cli/commit/6050e497360491c7ae0a06218fb8074578b017c4.
