### ISSUE TITLE
Question: Distinction between JSPM & SystemJS?

### ISSUE THREAD

**Issue by hannahhoward** [jspm/jspm-cli#1506]
Hi project maintainers,

   I've searched the internet and I'm having trouble understanding exactly the distinction between SystemJS alone and SystemJS + JSPM. I ask cause:

1. I'm converting an Angular 1 app to Angular 2. Angular 2 docs seem to use SystemJS, but not JSPM. I think.
2. I've been using NPM as my main package manager up till now and I'm pretty happy with it. The only thing I really need is something to load up all the files asynchronously in the browser (or bundle them up for production).

I get the feeling all I really need is SystemJS + SystemJS Builder. But can you give any feedback on why I might want to use JSPM as well? Maybe the answer will be helpful for future developers.

**Comment by lookfirst** [comment]
jspm is the package manager. It reads a package.json file for dependencies and writes out a config.js file of where those dependencies were installed. It also munges the files that are installed into jspm_packages in order to make them dependency aware if they aren't already. It does a bit more, but that is a good enough summary for now. =)

npm fails as a package manager for the web right now because it doesn't know how to relate dependencies together well enough or handle the differences between different module loaders. For example, let's say you write an angular directive in ES5. It obviously depends on angular, but there is nothing to say 'import angular before importing this directive'. jspm provides that functionality by adding a hint to the top of the file... `"deps angular;"` that SystemJS can use.

SystemJS provides the `System` object, which makes `import` statements work under the hood through transpilation. It also handles the hints that jspm added. =)

SystemJS bundler can read the config.js file and all your source code `import` statements and then bundle everything together into a single file (in the right dependency order) as well has handle minification and other fun stuff along the way.

**Comment by guybedford** [comment]
Thanks @lookfirst for the explanation here, that covers a lot of the main points - jspm wires SystemJS up for you so that it will load modules in the correct order and build without needing any custom config (ideally!).

It is absolutely fine to use SystemJS and npm with SystemJS builder, but you will hit issues where the SystemJS resolution does not correctly load npm packages that aren't browser globals. Then you need to work out how to manually configure packages with the right SystemJS configuration which quickly gets hairy. It can be a really good learning path though to stick to the browser globals that work on npm and gain a deeper understanding of SystemJS in the process, although it may be frustrating at times too working out how to load everything correctly.

**Comment by guybedford** [comment]
Docs and architectural explanations are a priority this year, but let me know if there is anything more I can do to clarify.
