### ISSUE TITLE
JSPM package - AMD bundled main file issue

### ISSUE THREAD

**Issue by stephenlautier** [jspm/jspm-cli#1507]
Hi,
I'm trying to create a library which I'd like to have installed by JSPM.
When I install my library it doesn't work because of the main file which is generated, if i simply point to the actual file directly instead it will work e.g.

```javascript
// from
"ssv-core": "github:sketch7/ssv-core@0.1.4",

// to
"ssv-core": "github:sketch7/ssv-core@0.1.4/amd/ssv-core",
```
Currently using JSPM v0.16.27 + systemjs v0.19.18, my library is build as AMD bundled (using TS 1.8 `--outFile`).

#### JSPM Config with package.json (library)
```json
  "jspm": {
    "registry": "jspm",
    "main": "amd/ssv-core",
    "format": "amd",
    "directories": {
      "dist": "dist"
    },
	"dependencies": {
		"lodash": "^4.0.0"
	},
    "peerDependencies": {}
  },
```

```typescript
// simple usage of library in order to test if needed.
import {utils} from "ssv-core";
console.log(`>> calc: ${utils.math.add(5,2)}`);
```

Am I doing something wrong?

p.s. just in case you wanna look anything specific within the lib its on github https://github.com/sketch7/ssv-core

**Comment by guybedford** [comment]
Can you clarify what you mean by "wont work" here? Are you saying that `import x from ''ssv-core"` works but `import {utils} from "ssv-core"` doesn't or something along those lines?

**Comment by guybedford** [comment]
Ok the problem is that the single file there contains named AMD defines, which means your main entry point is a **bundle**. Bundles are treated as empty modules that define into the registry, and you then need to load the underlying modules separately from the registry. It is only in the case where the name of the bundle happens to match the name of the bundle that it works, which may be your edge case scenario here. This sounds like the same thing as https://github.com/systemjs/builder/issues/495 which is currently being looked at for ways of making consistent.

**Comment by guybedford** [comment]
(that is even in the case where you got it to work it likely won't build properly, so we're looking at stopping the case that "worked" from working)

**Comment by stephenlautier** [comment]
Sorry, by showing a sample would be best however i dont have access for computer currently i can attach a small app. 

But no, basically the import syntax i dont change it in order for it to work or not. Only the map within systemjs i have to change in order for it to work (as i showed in my first snippet). So it seems that the generated "main" file from jspm is causing it not to work. By not working i mean it imports it however an empty object is returned at runtime

**Comment by stephenlautier** [comment]
Hey sorry for the late reply.

I'm not quite understood, is it a bug with SystemJS or am I doing something wrong?
Is it good to load a bundled "plugin", or its best if they are not bundled at all, what do you suggest?

**Comment by guybedford** [comment]
Try treating it as a global `jspm install github:sketch7/ssv-core@0.1.4 -o "{format:'global'}"`

**Comment by guybedford** [comment]
Sorry I didn't realise this was your library. The point then is that https://github.com/sketch7/ssv-core/blob/0.2.0/dist/amd/ssv-core.js is not a module, it is an AMD bundle. What that means is that each of the define statements is writing into the module registry. But that means that the named defines are assuming the name format of the registry, which is not compatible with jspm because it has its own naming format.

The correct way to have these modules work would be if they included a mini AMD build that then treated the bundle itself as an AMD module:

```javascript
(function() {

var SVC = (function(define) {
define('colelction.svc', ...)
define('svc', ...
})(function(name) {
  // mini AMD implementation, returning the "value" of the module
  return registry['scv'];
});

// THIS is now an anonymous define which can be read by jspm
if (typeof define != 'undefined')
  define(SVC);

})();
```

**Comment by guybedford** [comment]
And if that was all a little bit too much, just make it work as a global.

**Comment by stephenlautier** [comment]
Yes it is my library, mainly the whole point of it at the moment trying to create a good workflow for developing a library with TypeScript and delivery it as a JSPM package.

Thanks for the help, I highly appriciate! I will try to global one and if that works I think the best is to include a package-overrides within JSPM registry right?
Still unsure if providing a bundled library or unbundled is the best way, do you have any suggestions on that?

Btw, keep up the good work on these libraries, <3 SystemJS + JSPM! :+1:

**Comment by stephenlautier** [comment]
update: By treating it as a global via `jspm install github:sketch7/ssv-core@0.1.4 -o "{format:'global'}"` it doest not work. 

It says `define is not a function.`

![2016-02-20 21_35_36-sketch7 aurelia dojo](https://cloud.githubusercontent.com/assets/3908723/13199049/3c3ab1b2-d81a-11e5-81ef-d9c9a4def6d2.png)

**Comment by guybedford** [comment]
Right that would be because it can't be loaded as a script tag (which is what the global format emulates).

Basically, you either want to provide a single module, or multiple module files. Providing a named bundle is not a distribution format. So either compile each file separately into a folder that then maps them out - `amd/main.js`, `amd/depa.js`, amd/another/dep.js` etc etc each one an anonymous module in its own file, OR build the entire module into a single file build like a browserify build that doesn't expose internals (what the wrapping above is sort of trying to show).

**Comment by stephenlautier** [comment]
Ok thanks, I've decided to split them into multiple files and reference a main/index file instead as the way to consume it with JSPM or so.
