### ISSUE TITLE
Erratic formating in jspm.config.js after installing/uninstalling packages.

### ISSUE THREAD

**Issue by MeoMix** [jspm/jspm-cli#1519]
Hey Guy,

Ever since I upgraded to 0.17 I've noticed some odd behavior with my `jspm.config.js` file. Nothing is breaking, but it's a PITA for development.

Sometimes (not every time) when I install or uninstall a package... the config file's indentation expands heavily as if it were tabbed out multiple indentations. It doesn't respect my previously set spacing.

Additionally, the keys in map swap between being wrapped in double-quotes and being unwrapped when possible.

Here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/1380995/12992464/7709698a-d0c9-11e5-9238-fc5cee1b2668.png)

then I fix all my indentation.. uninstall another module... and the indentation resets, but this time the map keys are all wrapped... but the config option keys are all unwrapped. Weird, right?

![image](https://cloud.githubusercontent.com/assets/1380995/12992489/a043992e-d0c9-11e5-8c42-450423c71f4d.png)

Any ideas what might've introduced this?

**Comment by guybedford** [comment]
jspm needs to full serialize and then deserialize the configuration file.

In order to replicate the style of the configuration file it uses detection to work out the style of indentation, quotes, newlines etc.

If you have an exact config file test case for a config file that incorrectly detects and reserializes the wrong indentiation that would be good to look at.

For this case of quotes, individual per-property quoting is not tracked as part of the style. It will always unquote base-level properties, and quote second level properties.
