### ISSUE TITLE
Decentralized distributrion (IPFS/Torrent) and Package Ownership (BlockChain)

### ISSUE THREAD

**Issue by formula1** [jspm/jspm-cli#1522]
Going off of this here - https://github.com/nodejs/NG/issues/29

### Downloading
[This](https://github.com/formula1/decentralized-package-resolving-example/blob/master/plugins/torrent/index.js) is my simple example of downloading from what I was showing before

With IPFS I likely can implement something similar using the [client they've created](https://github.com/ipfs/js-ipfs-api)

#### BlockChain

Luckily instead of trying to reimplement it, Link is available - https://github.com/tsavo/link
- publish example - https://github.com/TSavo/Link/blob/master/lib/linkPublishTest.js
- read example - https://github.com/TSavo/Link/blob/master/lib/linkReadTest.js

So its to my understanding that mining is what verifies transactions and keeps the 0 trust concept alive. By providing an insentive to miners, they now have an interesting in verification. Unless there is coin associated to our own or (as the video pointed out toward the end) use bitcoin's, giving miners an insentive to keep mining would be an issue.

Something else that is a bit troublesome is onename explained that lookups are inherently slow so they ended up having to parse out the ones that they cared about and make modifcations to an external kv store. This likely would need to be reimplemented in our cases and/or centralized registries will have to be used (slightly defeating it in the first place).

Heres some information that helped me understand what was going on
- Presentation on decentralized Identification - http://blog.onename.com/experiences-with-scaling-blockchain-based-data-stores/
- This is the generic kv project (written in python) - https://github.com/blockstack/blockstore
- Article on mining (helped me alot) - http://qz.com/154877/by-reading-this-page-you-are-mining-bitcoins/
- Generic Decentralized Transaction - https://ethereum.org/#get-ether
- Creating a new Block chain - https://erisindustries.com/

**Comment by guybedford** [comment]
Yes these are exactly the principles, and certainly it's not straightforward to come up with something truly trustworthy.

I'm not sure I fully get the approach with Link, is it generating a bitcoin receiving address based on a payload then? I didn't know it was possible to do receiving address generation? Or is it just using something like the OP_RETURN approach in Bitcoin to include a custom payload in the transaction?

Yes when data is linked to a blockchain, that then requires locally syncing the full blockchain, and then creating a good local index in order to get quick lookups, but that initial download and indexing will be very restricting. If it wasn't Bitcoin but a custom blockchain just for this purpose, then it would work due to the smaller ledger, but that would then require creating mining incentives.

There's another problem that is mentioned at https://github.com/blockstack/blockstore/wiki/Design-Decisions by Onename and that is that registration itself is an insecure operation.

Once cracked though, the idea was that you publish versions as transactions that contain a payload of the version number and hash for that version. Then when downloading a version I can verify that is the correct hash by the trusted publisher and use that as the IPFS or a similar protocol hash of the file I want to download. That is, the trust problem is all about the trusted name owership, and version to hash publishing problem as far as I can tell.

The principles here are very much the same principles of buying a domain name. The cases of transfer etc need to also be considered so it's a tough problem. I'm not sure what the best reduction of it would be or edge to tackle first, but just to share the full ideal scope first.

**Comment by formula1** [comment]
Yeah, I saw that too. The presenter was saying that onenname had a huge squater problem initially. Since first implementation would likely not be associated to any big names, this won't be a problem at first. But the second a name like node or npm is associated to this protocol/blockchain I fear the worst. They I believe they mentioned part of their solution was through 'multi-factor' forms of verification which requires centralized authentication servers to revalidate the individual. This in a sense invalidates the idea of a 'zero trust' system as it now depends on external resources to validate the individual.

Correct me if I'm wrong but here is an object oriented approach to it

- Class: Package Identifier
  - Owner: { type: user/org } - A way a blockchain to identify who has permission to change the package. This is the most difficult aspect
  - State: { type: enum } - Active Use, Available for Purchase, Removed (
  - Name: { type: string } - The package name
  - Version: {type: Array<Byte>, length: 3, } - Package version
  - validation - Would be used for validating what ever was downloaded. In case the mechanism (http, tor, etc) delivered insecure packages, we would never know unless we had some way to predict what we should expect. This is it.
    - sha: { type: string } - The net validator that is created with a combination of a checksum and size
    - checksum : { type: string } - predicts the value of the contents
    - size: { type: Int } - if somehow someone figured out how to create an identical sha with different contents. They would additionally how to ensure the contents fit the same size constraints.
  - uri: { type: string } - This would feature the protocol and etc. Ideally when publishing, it would make the project available publicly as well.

Transactions that we would implement are
- register(Name, Owner) - I'm wondering if its possible to make bitcoins 'disapear' or tie bitcoins to a particular resource. Hypothetically, an individual could add to the ledger 'This bitcoin is now considered <Virtual Commodity>', trade this virtual commodity then redeem the virtual commodity for the initial value it would be what we are looking for.
- publish(Name, Version, Uri) - need to pass in Owner for validation purposes
- transfer(Name, newOwner) - This would be more associated the the virtual commodity aspect

Similar to how bitcoin ownership can be associated to individuals, the virtual commodity would be considered associated to individuals. As a result, verifying that a user has sent or used the bitcoin is without consequence to us.

Ok... so...
- The way bitcoin's 'wallets' work is as so.
  - No one has a bitcoin unless they mine it or recieve it
  - All of their actions get added to the ledger
  - Wallet.amount is actually a getter
    - `()=>{ return this.transactions.reduce((sum, t) -> { sum + t.amount }, 0) }`

We cannot 'mine' package names... maybe? No... mining gives a generic amount package names are unique. Etherium seems interesting

- https://github.com/slothbag/EthHypeDns
- https://www.ethereum.org/token
- http://etherid.org/

Also [Spore](https://github.com/mhhf/spore) seems interesting. Basically exactly what you were talking about. Requires a full node though he mentions a 'lightwallet' which I have no idea what it is but seems like [one has been built in js](https://github.com/ConsenSys/eth-lightwallet)

**Comment by guybedford** [comment]
This is always an interesting discussion to have. Practicalities have taken over for now, but hopefully it can be picked up in future.

**Comment by formula1** [comment]
Eh, wasn't much of a discussion. Probably won't be picked up in the near future (maybe distant). But thank you for entertaining my interest, jspm is a quality peice of software and the javascript community is lucky to have someone like you involved.
