### ISSUE TITLE
jspm Error: read ECONNRESET

### ISSUE THREAD

**Issue by steamonimo** [jspm/jspm-cli#1564]
Environment: Windows
npm: v5.7.0
jspm-cli: 0.16.23
Network Hardware: FritzBox Router <> Juniper Firewall <> Computer

Issuing jspm update in my aurelia project will very often fail with the following message:

     Looking up npm:babel-core
     ...
     Looking up npm:jquery
     
     warn Error on lookup for npm:aurelia-bootstrapper
     Error: read ECONNRESET
     at exports._errnoException (util.js:856:11)
     at TLSWrap.onread (net.js:550:26)
     
     err  Error looking up npm:aurelia-bootstrapper.

After several update attempts with different Lookups failing with ECONNRESET the update will finally succeed. To me this looks like jspm-cli is very sensitive to timing issues in the network due to Firewall or Proxy related delays. Perhaps even an additional timeout parameter will help here.

This problem is not related to my specific hardware and others have asked about this in the aurelia git as well: https://gitter.im/jspm/jspm/archives/2015/09/24 (search for ECONNRESET).

**Comment by guybedford** [comment]
It's very difficult to say exactly how this is happening as it is entirely at the HTTP and network layer. I've added https://github.com/jspm/npm/commit/bfe338fd46be067ff957394194d24f0740b0c17d to ensure that these are automatically retried within jspm so you don't need to manually rerun the command, but the underlying issue is still simply connection instability.
