### ISSUE TITLE
can i install pkg from bower?

### ISSUE THREAD

**Issue by izengliang** [jspm/jspm-cli#157]
can i install pkg from bower?

e.g.

```
jspm install bower:pkg@0.0.1
```

**Comment by jonathanmarvens** [comment]
:+1: … Bower compatibility would be great. I wish I had enough time to implement the Bower location service myself. It’d be really awesome if the JSPM CLI could consume the “bower.json” files in bower packages. Currently, I’m pulling from GitHub and using overrides, and it really sucks having to do this over and over again :disappointed:.

@briandipalma
The same could be said about NPM. Most NPM packages can be installed from GitHub.

\- Jonathan

CC: @guybedford.

**Comment by guybedford** [comment]
@jonathanmarvens what bower.json info do you need? The GitHub endpoint supports reading the bower.json main.

**Comment by jonathanmarvens** [comment]
@guybedford

Ah, I wasn’t aware of that. Does it understand bower dependencies, too? Also, how do I make instruct JSPM to use __bower.json__ instead of __package.json__?

Thanks.

\- Jonathan

**Comment by guybedford** [comment]
@jonathanmarvens jspm won't install dependencies for GitHub repos by default because there is no guarantee that bower dependencies will load through jspm, while we can make this work completely for npm due to the correlation between require and dependencies.

What do you mean by instructing to use `bower.json` instead of `package.json`? For the `main` or another package property?
