### ISSUE TITLE
overrides property ignored in linked depository

### ISSUE THREAD

**Issue by domagojk** [jspm/jspm-cli#1570]
In my link repository I have defined

```
"dependencies": {
    "sharejs": "npm:share@0.6.3"
},
"overrides": {
  "npm:share@0.6.3": {
     "format": "global"
  }
}
```

But when I make a link in my main repository I need to manually append the same overrides property in order for this to work
Is this desired workflow or should overrides property be copied in main packgage.json ?

Thanks!

**Comment by guybedford** [comment]
Yes overrides do not apply from installed dependencies (which includes linking). The only way to share overrides is either to check them into the jspm registry, or manually have them in your installation project.

There has been discussion about allowing this before, and I might still be open to it, but the problem is just that we then need to handle conflict scenarios as overrides are effectively breaking package changes.

**Comment by domagojk** [comment]
I see.. I suppose this conflict scenarios would be complex to process? I was thinking that maybe user should decide for himself if he wants to apply this overrides and resolve conflicts?

**Comment by guybedford** [comment]
It's not just the conflict prompt complexity which is actually quite easy to handle, it's also the fact that we don't want to encourage public packages to include their own overrides, as it's a step closer to an ecosystem where everyone is using different overrides. The whole point about overrides is that we need a central registry to ensure we are all agreeing on them. Otherwise in the process of creating overrides for packages, there's the chance of having different interpretations and manual selection prompts occurring too much. So it's mainly that this isn't something we want to make easy because of the potential ecosystem issues.

**Comment by domagojk** [comment]
I understand... But, one last thing then... Could this maybe be applied only for linked packages? Because, that is actually the same application and I am the who wrote the overrides, its just seems a bit strange to write this in two places. 
Especially when application is "plugin-based" and is getting more complex with multiple developers working on it (which is true in my case). For example if one developer for his plugin needs some library installed in "format:global" or similar, I need to be aware of this and resolve it manually and place this information in main package and later If I wish to remove this plugin, I need to mind this override as well.
This is not a problem for me now, but I fear it could become in time...

Is there some other workaround I could use?

**Comment by guybedford** [comment]
If you are writing the package yourself, there's no need to use overrides - just include the package configuration in the package.json file, as this is where it is supposed to live anyway. Will that work for you here?

**Comment by domagojk** [comment]
Yes, I'm using it in this way, it is not a big problem but it just seemed strange to me..
Because this linked repository is used in multiple "master" repositories (for now, one for web and one for mobile version) and it can also be used as standalone.
For example, If small team is developing web and mobile applications and linked repository is maintained by developer X, web by Y and mobile by Z, why should Y and Z care about in what way X installed his library?

But I guess we would then go back at problem of handling conflict scenarios you mentioned...

**Comment by guybedford** [comment]
Again, this is what the jspm registry is for. You can also run a custom local registry within the organization.
