### ISSUE TITLE
Importing Index Files

### ISSUE THREAD

**Issue by casesandberg** [jspm/jspm-cli#1580]
Is there an automatic way for JSPM to look for index files when importing something?

`import common from './components/common'` resolves to `import common from './components/common/index.js'`

**Comment by amenadiel** [comment]
Only if said library had:
- a "main" property in its package.json, 
- a local override for the library with a "main" property
- an override with a "main" property in the jspm registry
- a package config for the library in your config.js file with a "main" property

Otherwise, there's no way to know if you wanted index.js, home.js, main.js.
