### ISSUE TITLE
jspm 0.17.0-beta.12: Importing socket.io in the server.

### ISSUE THREAD

**Issue by m-a-r-c-e-l-i-n-o** [jspm/jspm-cli#1676]
I'm using jspm 0.17.0-beta.12 to run my backend server and I'm having a little issue. Has anyone been able to import socket.io on the server?
The following:
`import Server from 'socket.io'`
throws:
`ReferenceError: navigator is not defined`

I've tried the "socket.io-client" version too, they both try to eval the browser variable "navigator", which I'm guessing isn't suppose to happen in the server version. Do I have to import it as a different module format? If so, how do I go about that?

Thank you for your time.

**Comment by guybedford** [comment]
This is due to the jspm configuration in socket.io itself at https://github.com/socketio/socket.io-client/blob/master/package.json#L13, which is stopping the client from loading properly in Node in jspm 0.17.

Editing `jspm_packages/npm/socket.io-client@1.4.5.json` to alter the main from `socket.io.js` to `lib/index.js` then fixes the problem and gets `jspm run socket.io` to work as far as I can tell.

I've posted https://github.com/socketio/socket.io-client/pull/957 to resolve this for the next npm release, and added an override in https://github.com/jspm/registry/commit/9d4f4911e374d109e27a0875d03f1e0f153b9a4b, so it should be working now.

**Comment by m-a-r-c-e-l-i-n-o** [comment]
Indeed, thank you, Guy!
