### ISSUE TITLE
Duplicate files being injected

### ISSUE THREAD

**Issue by kdex** [jspm/jspm-cli#1707]
In #872, see [these](https://github.com/jspm/jspm-cli/issues/872#issuecomment-208313034) measurements and the following three comments for more information.

Also, see @zakdances's description starting [here](https://github.com/jspm/jspm-cli/issues/872#issuecomment-207801965).

**Comment by zakdances** [comment]
You might wanna change the title. The latency is just a sympton...the real problem is the duplicate scripts being loaded.

**Comment by kdex** [comment]
@zakdances Done. :+1:

**Comment by zakdances** [comment]
@kdex thanks, I'm making a test case now.

**Comment by kdex** [comment]
Since I'm not 100% sure that @zakdances and I are having the exact same issue (or it having the exact same cause), I've created [a repository with two test cases](https://github.com/kdex/jspm-test-cases), too.

There's one test case where I'd expect close-to-zero latency and another test case where I'd expect no dependencies being loaded.

**Comment by zakdances** [comment]
Alright, well here's [my test case (with instructions)](https://github.com/zakdances/jspmBundleBug). The more the merrier, I suppose.

(As an aside, I can't believe how annoying and awkward it is to parse a URL with JavaScript.)

**Comment by guybedford** [comment]
@zakdances you're serving the `src` folder to the server, while the bundle command is bundling based on the baseURL being the folder below src. So the bundle is assuming `app.ts` is at `src/app.ts`, while the server is providing `/app.ts`. The two versions are entirely because of that conflation. It's advisable to serve the base-level folder here.

**Comment by guybedford** [comment]
@kdex your test case is giving me the error `Cannot find module 'babel-polyfill'`. Again, this is about carefully ensuring that the module names in the bundle are able to normalize correctly into the same URLs expected by SystemJS. If you're unsure, try inspecting `Object.keys(System.defined)` after running the bundle, to see what URLs the bundle has defined. They should match the expected URLs needed by SystemJS, and if they don't it's about adding the right configuration to ensure they do.

**Comment by kdex** [comment]
@guybedford Which of the two test cases gave you this error, and what were you trying to do when you encountered it?

I've tried to reproduce your issue on all major operating systems, but to no avail. (The source doesn't even import `babel-polyfill`. Are you sure that your setup is alright?) 

Just to be on the safe side: There's no need to run any other commands than `npm install`, `jspm install` and `gulp`. Everything else should be observed in DevTools. This especially means that you **don't** have to run any jspm bundle/build commands!

For me, both of the test cases work as intended on all operating systems. Could you please try again?

**Comment by guybedford** [comment]
I'm using npm 2 and Node 4 and just running `npm install` in the repo. When I run `gulp` I get:

```
 gulp
[02:18:05] Requiring external module babel-register
module.js:327
    throw err;
    ^

Error: Cannot find module 'babel-polyfill'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (gulpfile.babel.js:1:1)
    at Module._compile (module.js:409:26)
    at loader (/Users/guybedford/Projects/test/jspm-test-cases/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/guybedford/Projects/test/jspm-test-cases/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

**Comment by kdex** [comment]
@guybedford My bad! The sources didn't require `babel-polyfill`, but the gulpfile still did. I've fixed it [here](https://github.com/kdex/jspm-test-cases/commit/1a583b3e660b4fab26f9c228b31b426e34940e19). It should now work as intended.

Does this modification make the tests work for you?

**Comment by guybedford** [comment]
@kdex the first case is measuring the execution time (CPU), and I'm getting that at 1.3s to load the 1.6MB bundle of JS code. Note that you need to close the chrome dev tools as there is a dev tools bug causing a slow down if left open during execution (a known SystemJS issue).

In the second case, the duplicates js file contains a bundle-sfx not a bundle of `app/**/*.js - [app/**/*.js]`. SFX bundles do not share dependencies, so that explains why all the modules are being downloaded again.

**Comment by kdex** [comment]
@guybedford The second case makes sense, thanks.

As for the first case: The bundle will have already run through by the time the measurement starts, meaning that the modules should have been `System.register`ed and thus be stored somewhere in memory. The latency isn't as big with DevTools closed, but still measures well over a second. A time of 1–2 seconds for a bundle that has already been downloaded *and* parsed still sounds like an awful lot to me.

**Comment by guybedford** [comment]
Bundles are parsed when executed, but the inner initialisation code is not run until the System.import statement. So what you're measuring there is the linking time + the execution time of the app. One way to measure the execution time on its own is to use the bundle-sfx instead of a normal bundle and run that directly to see how long it takes to execute after parsing, which might be quite interesting to see.

For a 1.6MB code file, the execution time is really about how that code is written. Anything from 100ms to 400ms would be reasonable here, but over a second is certainly not ideal. This is not SystemJS specific though, it's about the init code itself.

The linking time is what SystemJS contributes though, and that is the normalization time + the loader pipeline time. One way of speeding this up may be to try using Bluebird for promises over native promises. This is certainly the key area where performance improvements in SystemJS in future can reduce this time. If you're able to work out what this time is in your app it would certainly be interesting to know.

**Comment by kdex** [comment]
I've just performed a measurement with:

```html
<script>console.time("parse")</script>
<script src="sfx-bundle.js"></script>
<script>console.timeEnd("parse")</script>
```

where `sfx-bundle.js` is a self-executing bundle that comprises the **entire** second test case app (and not only its dependencies). I'm measuring about 290 ms.

Since the bundle should be handled synchronously, doesn't this imply that the initialization time should actually be well under a second?

**Comment by kdex** [comment]
@guybedford I've just performed a measurement with:

```html
<script>console.time("parse")</script>
<script src="sfx-bundle.js"></script>
<script>console.timeEnd("parse")</script>
```

where `sfx-bundle.js` is a self-executing bundle that comprises the **entire** second test case app (and not only its dependencies). I'm measuring about 290 ms.

Since the bundle (and script tags without `async`) should be handled synchronously, doesn't this imply that the initialization time should actually be well under a second?

**Comment by guybedford** [comment]
Interesting. Putting the timing within the build file itself would give the
time excluding parsing as well.

There's definitely a lot of scope for performance improvements here then. A
lot of good work yet to be done here!
