### ISSUE TITLE
Problem running bundle with JSPM 0.17.0-beta.12 and Angular2 2.0.0-beta.8

### ISSUE THREAD

**Issue by KarlPurk** [jspm/jspm-cli#1709]
I'm encountering an error when running a bundled version of an Angular 2 project after updating the project from `JSPM 0.16.32` to `JSPM 0.17.0-beta.12`.  

Without the bundle the app loads without issues.  

The error is a generic JavaScript error from within Angular 2.  However, due to the fact that the app runs fine without bundling I'm assuming this is an edge case with the bundler.

I've created a repository that reproduces the issue:
https://github.com/KarlPurk/jspm-0.17.0-beta.12-bundle-issue

Cheers!

**Comment by guybedford** [comment]
I managed to debug this a little and at least get the following:

The underlying error is actually - "Cannot resolve all parameters for 'ResolvedMetadataCache'(?, ?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'ResolvedMetadataCache' is decorated with Injectable."

Note that execution order can be affected by bundling if dependencies are not setup explicitly.

Perhaps someone from the Angular side can advise better than I can here what exactly the issue might be.

**Comment by KevCJones** [comment]
Seems like it might be related to this issue [on angular](https://github.com/angular/universal/issues/293).

There is some early finger pointing at the the reflect metadata module which might not be doing its job right on the node side (e.g. the bundle).

But the latest post hints at the angular2/polyfills removal as a cause.

> The fix was to remove import 'angular2/bundles/angular2-polyfills'; from the top of my component spec.

Not tried that yet, but its something to look into at least.

**Comment by guybedford** [comment]
Any further progress here?

**Comment by KevCJones** [comment]
Need to revisit it, work got busy. Will keep you posted

**Comment by jonricaurte** [comment]
@KevCJones I have an angular 2 app running with rc1 and typescript with the latest version of jspm and everything works fine on my end. Still having issues?

**Comment by KevCJones** [comment]
That's promising. We've parked the project (an internal seed) for the short
term while we finish of some paid work. That said we will revisit next
month. I fear it will be a lot of updating for us. :/

**Comment by jonricaurte** [comment]
@KevCJones I see :/ the workflow is way better with the latest though. Ok for @guybedford to close the issue?

**Comment by KevCJones** [comment]
Close away, I imagined it was just a question of time before they aligned
again. If we have trouble will get in touch. Cheers
On 27 May 2016 01:27, "Jonathon Ricaurte" <notifications@github.com> wrote:

@KevCJones <https://github.com/KevCJones> I see :/ the workflow is way
better with the latest though. Ok for @guybedford
<https://github.com/guybedford> to close the issue?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jspm/jspm-cli/issues/1709#issuecomment-222031015>, or mute
the thread
<https://github.com/notifications/unsubscribe/AAqe8Jg4wVnX1XdmynJ5C38ebyAhkRA9ks5qFjpXgaJpZM4IEeUO>
.
