### ISSUE TITLE
0.17 -- source maps not fully working

### ISSUE THREAD

**Issue by joeldenning** [jspm/jspm-cli#1723]
A couple questions/concerns with 0.17:
- jspm seems to assume that the package name specified in the package.json, jspm.browser.js, and/or jspm.config.js should be part of the source map URL. To me, it seems a bad assumption that the package name is the same as the directory served by the webserver?. What's the reasoning behind that?
- When there is a package name specified, I usually get a `../../../../package-name/src/....` as the path to the source file. It seems like a bug that there are four `../`'s in the url.
- When I get rid of the package name completely, the source map urls are usually correct. However, the sourcemaps have very low accuracy (even if I use `--hires-source-maps`) and almost no breakpoints work at all. This seems to be the case whether I `--skip-rollup` or not.
- Also it seems that `--source-map-contents` does embed the source files, but the browser still tries to fetch the files instead of using the sources in the .map file itself.

If I get some time, I might look into fixing this myself, but I don't know too much about how where it is going wrong.

**Comment by joeldenning** [comment]
Oh forgot to mention that this is during a `jspm build`

**Comment by guybedford** [comment]
Thanks, this sort of feedback is really useful.

> jspm seems to assume that the package name specified in the package.json

This is because by default we're setting the `main` to be the same as the name of the app right during init? The alternative here would be to use an `index.js` main or something else?

> When there is a package name specified, I usually get a ../../../../package-name/src/.... as the path to the source file

Thanks, I've been able to replicate this. I've created https://github.com/jspm/jspm-cli/issues/1729 to track further.

> When I get rid of the package name completely, the source map urls are usually correct. However, the sourcemaps have very low accuracy

Which transpiler is this using, is it for the build or bundle file, or in the browser?

> Also it seems that --source-map-contents does embed the source files

Try `--source-map-contents --inline-source-maps`. `--source-map-contents` puts the contents in the source map file, inlining is necessary to get it all in the single js file.

**Comment by joeldenning** [comment]
> This is because by default we're setting the main to be the same as the name of the app right during init? The alternative here would be to use an index.js main or something else?

I'm not sure I fully understand your questions here, probably because I don't fully understand the concept of jspm@0.17's new "app name" (found in the package.json under `jspm.name`). My limited understanding of the app name is that it should be something that other projects could potentially reference and/or depend on. So I was expecting it to be a rather arbitrary string, and was surprised when `jspm build my-app` started looking for `my-app`'s main file inside of a directory called `my-app`. I successfully worked around this with `ln -s . my-app`, and also tried another workaround of changing the app name to be `src`. But both of those are workarounds, and I was further surprised when the source map urls always referenced the app name as a directory that the web server would know about. My expectation was that the source maps would reference only real directories instead of the "app-name" as a directory in the source map url.

I think maybe the gap of understanding here for me is the relationship between the app name and my directory structure. If I have the following configuration, why does jspm think there's a directory called `my-app`?
```js
//package.json
{
  "jspm": {
    "main": "my-app"
  }
}
```
```js
//jspm.config.js
{
  "packages": {
    "my-app": {
      "main": {
        "src/main.js",
      }
    }
  }
}
```


> Which transpiler is this using, is it for the build or bundle file, or in the browser?

I'm using plugin-babel as my transpiler, and am doing a `jspm build`

> Try --source-map-contents --inline-source-maps. --source-map-contents puts the contents in the source map file, inlining is necessary to get it all in the single js file.

Thanks, I'll definitely give that a try.

**Comment by guybedford** [comment]
I agree that the init paths workflow is somewhat confusing. I'm going to put some time aside to see if we can make this a simpler init experience.

To explain the app name principle, the idea is that the package should be given a name, and imported by that name when being used. So instead of doing `System.import('lib/app.js')` or `System.import('src/app.js')` you can do `System.import('app')` and the `app` is the package name of the local project (even though it lives in the `src` or `lib` folder). The main entry point setup will then be added automatically, as we are using package configuration for the local project, and instead of having arbitrary meta configuration, that local package can have its own package configuration object in the config file, where all the local configuration can belong in an encapsulated way. This then also serves as an immediate introduction to the SystemJS package configuration system, so that all local configuration is running through this mechanism. There is some confusion here that the package.json and config file both duplicate things like main etc, but the idea here is that if and when publishing, different package configuration may be published than the one used for loading in a test environment.

The source maps stuff is definitely messed up with the backtracking, which needs to be fixed though, thanks for pointing me to that.
