### ISSUE TITLE
bundling vendor library

### ISSUE THREAD

**Issue by thisconnect** [jspm/jspm-cli#1731]
Could you give me any pointer of how to bundle react + redux + others into a single self executable file that exports into global (window.react window.redux or window.React window.Redux etc.)?

Does that need an entry point or just cli ?

`jspm bundle-sfx react redux --format global` does build but not export to window.LibraryName

**Comment by mikeyoon** [comment]
Hmm, not sure how possible it'd be to do this without an application that references your dependencies. AFAIK, in any kind of module loading system, your dependent modules are not executed until imported. So in your example there, you probably just get two module definitions, but since they're not imported the actual code inside them is never executed.

I'd expect that you'd need to create a dummy app that requires these two libraries.

**Comment by guybedford** [comment]
Best would be to build each individually into a global, or to create a custom top-level module file that does the global assignment, and build that top-level module.

**Comment by thisconnect** [comment]
Like that?

```javascript
import A from 'a'
import B from 'b'

window.A = A
window.B = B
```

**Comment by guybedford** [comment]
Yes exactly.

**Comment by thisconnect** [comment]
thank you

**Comment by thisconnect** [comment]
Sorry one more question, if both A and B have a dependecy on C, is it correct that C would only be included once?

**Comment by guybedford** [comment]
Yes, modules define into the module loader registry by name, which allows them to execute once and be shared.
