### ISSUE TITLE
Have jspm warn about linking a package that would modify the package.json.

### ISSUE THREAD

**Issue by zenorbi** [jspm/jspm-cli#1759]
Currently if I have a package installed as

```
"dependencies": {
    "my-lib1": "npm:my-lib1@^1.0.0"
}
```

And I try to link a folder called `my-lib1` (not the distributed npm version), jspm will overwrite the dependencies with

```
"dependencies": {
    "my-lib1": "local:my-lib1@master"
}
```

This causes `jspm install --unlink` to fail, as it does not know where to look for the original package.
### Why I have this problem

I have a directory structure like this:

```
my-lib1/
    package.json //JSPM dependencies
    src/ //original source code
    dist/
        package.json //JSPM and npm stuff to publish to an npm repo
        lib/ //Transpiled sourcecode goes here
```

This directory structure is needed because the sourcecode is written in TypeScript and I have the `lib` populated with `.js` and `.d.ts` files. I push the `dist` folder to npm and leave out the rest of the files. When I install this package like `jspm install npm:my-lib1`, jspm correctly installs it, and TypeScript can discover the `.d.ts` files. However I would also like to do linking when I test this package in another package, and if TypeScript were to discover any `.ts` file in `jspm_packages`, it would try and compile that as well, failing of course to do so, and also messes up the output directory structure. I know I have `directories.dist` config, however that forces me to create a link to the `my-lib1/package.json` inside the `my-lib1/dist` folder. I have 2 problems with linking that file. First, it creates a file which needs to be removed each time I unlink the package, second, in windows symlinking to a file is only allowed to admin users.

With this structure, I can just link do `jspm link ../my-lib1/dist` and everything works just fine, however if I mess up the command and do `jspm link ../my-lib1`, jspm overwrites the location of the package in `package.json`.

**Comment by guybedford** [comment]
Are you saying you have the `name`, `version` and `registry` properties set in the `dist/package.json` file? If you want `jspm link ../mylib1` to not use `local:mylib-1` then you can set the `name`, `version` and `registry` in the `my-lib1/package.json` file.

In terms of warning on such a mistake, the warning doesn't really have any general cause to stick to here unfortunately? At least not one that I can think of?

I'm not sure I quite follow as well why you can't have the `src` and `lib` folders parallel to eachother? These intricate publishing workflows do need some love though, so I'm really interested to hear your experiences here.

**Comment by Zenorbi** [comment]
Almost got it right :), let me clarify a bit. The correct way to link with my library is `../my-lib1/dist` and not `../my-lib1`. The warning would be something along the lines of: 

> You already have "my-lib1" (npm:my-lib1@^1.0.0) installed as a package. Would you like to overwrite "my-lib1" with local:my-lib1@master? (Repository field differs)

The trigger of this warning would be that the package is clearly an npm package but the one I'm trying to link with doesn't have npm registry or even a version set.

I can have `src` and `lib` folders in parallel, but I cannot have one global package.json, because:

1. I don't want to end up having `src` folder in npm, as TypeScript would try and compile the `.ts` files in the `jspm_package` folder when someone uses my library.
2. I could set `directories.lib` in the `package.json`, but during linking, jspm requires a `package.json` in the `directories.lib` folder to know the package's dependencies and jspm creates a file symlink to the main `package.json`. In Windows, you cannot have symlinks to a file, unless you're and admin.

So I separated the development and distributed version, and I can just link to the distributed one. No `.ts` files for npm or link and I can just have `gulp watch` the library and compile to the distribution folder.

**Comment by guybedford** [comment]
Ok I see what you mean. Perhaps we should infer the name from the existing install then? So if you link `my-lib1` when it is already installed, instead of defaulting to `local:my-lib1@master` we just use the existing `npm:my-lib1@1.0.0` information as the guide here? Would that solve your problem?

**Comment by Zenorbi** [comment]
Either that, which would preserve the existing name and you can `jspm install --unlink` to revert the `package.json`, or maybe a better solution would be to look for the `directories.lib` in the `package.json` (`my-lib1/package.json`) and if the folder that it's pointing to already has a `package.json` (`my-lib1/dist/package.json`), use that file and do not symlink to the main (in this case wrong) file.
