### ISSUE TITLE
JSPM bundle does not bundle peer dependencies.

### ISSUE THREAD

**Issue by Zoltu** [jspm/jspm-cli#1768]
```
$ jspm init
$ jspm install aurelia-bootstrapper
$ jspm bundle aurelia-bootstrapper
     Building the bundle tree for aurelia-bootstrapper...

       npm:aurelia-bootstrapper@1.0.0-beta.1.2.0.json
       npm:aurelia-bootstrapper@1.0.0-beta.1.2.0/aurelia-bootstrapper.js
       npm:aurelia-pal-browser@1.0.0-beta.1.2.0.json
       npm:aurelia-pal-browser@1.0.0-beta.1.2.0/aurelia-pal-browser.js
       npm:aurelia-pal@1.0.0-beta.1.2.0.json
       npm:aurelia-pal@1.0.0-beta.1.2.0/aurelia-pal.js
       npm:aurelia-polyfills@1.0.0-beta.1.1.2.json
       npm:aurelia-polyfills@1.0.0-beta.1.1.2/aurelia-polyfills.js

ok   Built into dist\build.js with source maps, unminified.
```

If you look in the `package.json` you can see that Aurelia has a lot of peer dependencies.  However, as you can see in the bundle output those peer dependencies are not bundled in, leading to them all being loaded from the server at runtime (rather than via the bundle).

**Comment by guybedford** [comment]
I don't think this is because these are peer dependencies, but because these dependencies are probably not part of the static module trace, and instead loaded via a custom `System.import(x)` statement. We are looking into adding tracing for `System.import` dynamic requires that can be analysed, tracking in https://github.com/systemjs/builder/issues/452.

**Comment by Zoltu** [comment]
Hmm, I thought that was one of the things that peer dependencies were going to solve?  I guess I was mistaken about that and I'll track the linked issue.
