### ISSUE TITLE
jspm fails to resolve module name correctly for @angular packages

### ISSUE THREAD

**Issue by jamesbs** [jspm/jspm-cli#1782]
It looks like the @ symbol is causing jspm to resolve the module names incorrectly

**command:** jspm install npm:@angular/core
**jspm version:** 0.17.0-beta.14

running the command gives an ok response:

`ok   Installed %% to npm:@angular/core@^2.0.0-rc.1 (2.0.0-rc.1)`

and lists the following in the `package.json` under `jspm.dependencies`

`"": "npm:@angular/core@^2.0.0-rc.1",`

This doesn't seem to be happening on jspm 0.16

**Comment by Vanuan** [comment]
what is "@angular"?

**Comment by frederikschubert** [comment]
That's a npm scoped package. It namespaces multiple packages.

**Comment by guybedford** [comment]
Fixed in https://github.com/jspm/jspm-cli/tree/0.17.

It's better though to just do `jspm install angular-core=npm:@angular/core`.

**Comment by born2net** [comment]
for everyone's reference you will need all these ng2 libs starting rc.0:

```
jspm install angular-core=npm:@angular/core
jspm install angular-compiler=npm:@angular/compiler
jspm install angular-common=npm:@angular/common
jspm install angular-platform-browser=npm:@angular/platform-browser
jspm install angular-platform-browser-dynamic=npm:@angular/platform-browser-dynamic 
```

**Comment by amenadiel** [comment]
Is this because there's an @angular entry in jspm registry, or is it a widely known convention? Is it happening on other modules as well?

**Comment by Vanuan** [comment]
It's a npm feature https://docs.npmjs.com/misc/scope

**Comment by tenninebt** [comment]
Any idea when the fix will be released? (No idea how you handle release as there are no milestones..)
Thanks

**Comment by born2net** [comment]
I am using jspm 0.17 with angular 2, seems to work great, see project here https://github.com/born2net/ng2Boilerplate

**Comment by tenninebt** [comment]
@born2net 
Don't know if you are answering my previous comment (which I deleted because I didn't interpret well what was said here, and the issue I was having wasn't related at all.) 
I had an error like : 
`"Error on fetch for @angular/platform-browser-dynamic at file:///<myappRoot>/@angular/platform-browser-dynamic", `
then I found the issue, for some reason, there was a map for :
    `@angular/platform-browser": "npm:@angular/platform-browser@2.0.0-rc.1`  
but the following one was missing :
    `@angular/platform-browser-dynamic": "npm:@angular/platform-browser-dynamic@2.0.0-rc.1`
Didn't notice it at the start so I thought there was in issue with loading modules starting with an "@".
I'll try to reproduce the issue asap (steps will probably be : install angular.rc1 on a clean env then check if all the maps are well created in the jspm.config), if so I'll log a new issue.

**Comment by born2net** [comment]
got it tx

**Comment by guybedford** [comment]
Released in jspm 0.17.0-beta.15.

**Comment by born2net** [comment]
tx so much Guy for supporting us, just donated $100 and I think more people should donate to jspm as it is awesome ... hope hot-reload gets better and better with ng2 as it is the KILLER application for jspm IMHO.

**Comment by guybedford** [comment]
Thanks so much @born2net! Yes these workflows get better when people put pressure on that, so very much appreciated for your feedback as well.

**Comment by born2net** [comment]
my pleasure...
