### ISSUE TITLE
Performance issues with jspm third-party bundles

### ISSUE THREAD

**Issue by doctyper** [jspm/jspm-cli#1845]
Hi Guy and team,

I work for the National Football League and am the core contributor in our [Wildcat](https://github.com/nfl/react-wildcat) project, a React-based framework using jspm + SystemJS as the underlying architecture for lazy-loading individual routes. For reference, we are using jspm 0.16.34 and systemjs 0.19.27.

I've been hitting a performance wall for the last couple of weeks, and I'm hoping you can shed some light on our bottleneck.

The basic flow we are trying to achieve is this: We're aware that unbundled asset loading is still a ways away, and monolithic bundling is here but comes at a cost of wasted bytes. We'd like to utilize a happy middle-ground where we are bundling all third-party libraries, but lazy-loading all first-party scripts.

We are essentially trying to use your [third-party dependency bundle](https://github.com/systemjs/builder#example---third-party-dependency-bundles) technique in a production environment.

Unfortunately we are seeing a poorly-performing client bootstrap experience using this technique. I'm defining "time to bootstrap" as the time between server render up to the first [Promise chain resolution](https://github.com/nfl/react-wildcat/blob/master/packages/react-wildcat-handoff/src/utils/defaultTemplate.js#L210). You can see a working demo in our [example project](https://github.com/nfl/react-wildcat/tree/master/example) by running `npm run prod-local`. Despite my attempts to reduce bootstrap time, I'm still seeing an initial bootstrap time (cache disabled) of ~0.8s. That's down from an unoptimized time of ~1.5s.

The biggest performance gain I saw came by [remapping third-party package entries](https://github.com/nfl/react-wildcat/blob/master/example/system.config.js#L16-L37) to their minified equivalents. This leads me to hypothesize that the performance sink involves the number of times `System.registerDynamic` is called in the vendor bundle. It appears that libraries with many module imports are wrapping those imports with `System.registerDynamic` and as a result are bloating that initial client bootstrap time.

Is there anything else I can do to improve the initial bootstrap performance?

**Comment by guybedford** [comment]
Hi @doctyper, really nice to see the Wildcat project, sorry to hear the performance has been such a pain recently. Thanks for reaching out on this - I'm happy to help where I can here.

Yes, as you have noticed, every module defined into the registry incurs a performance cost, so using pre-browserified versions of individual libraries is a great way to bring down this cost, ensuring that the optimum build of each dependency is used already. This is the same as using `jspm build` or `jspm build-sfx` instead of `jspm bundle`.

I tried running your example app but got the error - `err  Error on fetch for npm:react-wildcat-handoff@4.1.0/dist/client.js at file:///Users/guybedford/Projects/test/react-wildcat/example/jspm_packages/npm/react-wildcat-handoff@4.1.0/dist/client.js
[1] 	Error: ENOENT: no such file or directory, open '/Users/guybedford/Projects/test/react-wildcat/example/jspm_packages/npm/react-wildcat-handoff@4.1.0/dist/client.js'`. If you can suggest how to get this running that would be great to have a look.

For performance, perhaps try using Bluebird for promises support if you are not already, and see if that helps the load times? Apart from that and the obvious of running less code, there is not a lot we can do apart from working on optimizing the fast paths directly in SystemJS itself (an area of focus that would yield a lot of potential gains still).

**Comment by doctyper** [comment]
Thanks for taking a look @guybedford. I just tried a fresh clone and did not see this error. For reference:

```
cd example
npm install
jspm install
npm run prod-local
```

If all else fails, running `make install` in the project root should hook up all the necessary bits to get the project fully bootstrapped.

I had briefly looked at running `jspm build` but I assumed its use would result in the same number of `registerDynamic` calls. You're saying it would reduce the number of calls?

I was thinking that one way to speed up the bootstrap delay would be to parallelize the loading of vendors. That is, instead of having one mega-bundle, have one bundle per third-party dependency (e.g. `react-bundle.js`, etc). Is there an easy-ish way to do this through the CLI?

**Comment by guybedford** [comment]
Thanks for the updated instructions. Using that I was able to get running.

I just tried adding in Bluebird for Promises just before SystemJS and the load time reduced by around 0.5s for me on a 2s load time. Perhaps see what numbers you get for that there as well?

I'm not sure parallel vendor loading would make that much of a difference actually, as this is execution time that is causing the issues.

Perhaps using a static build of React would help so that it is not implemented as separate modules in the registry.

The other thing would be to dive in on that performance audit in SystemJS itself which is very much due. I expect we can make some significant performance gains very soon now that the project has finally reached stability.

**Comment by amcdnl** [comment]
@guybedford `Bluebird for Promises` really improves it that much??

**Comment by guybedford** [comment]
@amcdnl yes, the pipeline is all promises so that is the first performance target.

**Comment by doctyper** [comment]
@guybedford Another thought: combining all third-party vendors into a single file shaves network requests, but comes at the cost of running `registerDynamic` on all vendors, even if those vendors are not required to render the current view. For example if my vendor file contains `react-foo` and `react-bar`, both will incur that initial eval cost even if `react-bar` is not used in that initial view.

Perhaps there can be some way to 'lazily' register a module. That is, have SystemJS acknowledge the existence of a module, but delay evaluation until it is referenced in an import. This would defer the up-front cost in bootstrap time. Almost like a `lazyRegisterDynamic`.

**Comment by amcdnl** [comment]
@doctyper My team wrote this dynamic bundling tool ( https://github.com/swimlane/systemjs-route-bundler ) that we use at production time but it could easily be used for development too.

**Comment by guybedford** [comment]
Yes exactly as @amcdnl has provided, route bundling is a much better option that a single vendor bundle. Common bundles can then be carved out from route bundles with some optimizations.

**Comment by guybedford** [comment]
(that is, the best performance is always to run the least possible code)

**Comment by amcdnl** [comment]
@doctyper hit me up in gitter if you have ?s

**Comment by doctyper** [comment]
@amcdnl Thanks for the pointer. I gave your tool a try but it doesn't seem to be tailored for precompiled environments (that is, where a build step is not needed). I'll ping you on Gitter with specifics.

>I'm not sure parallel vendor loading would make that much of a difference actually, as this is execution time that is causing the issues.

@guybedford Actually I am seeing improved speeds when chunking vendor loads on 3G speeds (our baseline target). Bundling React + React DOM separately shaves 200ms off bootstrap time on 3G. There is a sweet spot somewhere in here, I believe we can strike a balance between network latency and evaluation costs.

**Comment by guybedford** [comment]
@doctyper great to hear it. Just ping me anytime if I can help further at all.
