### ISSUE TITLE
`undefined added to config bundles` when using inject+baseUrl

### ISSUE THREAD

**Issue by amitport** [jspm/jspm-cli#1855]
- using jspm 0.17-beta.16 
- non default server baseUrl (`{"jspm": {"directories": {"baseURL": "src/somesubpath"}}"`)
- running `jspm bundle main.js out.js --inject` -> outputs `undefined added to config bundles`
- running `jspm bundle main.js src/somesubpath/out.js --inject` works fine

IMHO, the baseURL should be already prepended when using `--inject`

**Comment by guybedford** [comment]
The output file is a file path to the output file. In order to do injection, jspm needs to work out the canonical name of that file from the perspective of the browser loader. I've added a better error message for this case in https://github.com/jspm/jspm-cli/commit/d8fc5192bedc081e9940711d103a49e4ab8aafce.

The fix is `jspm bundle main.js src/somesubpath/out.js --inject`. The reason being that we need file pathing rules to apply first for a file operation.
