### ISSUE TITLE
JSPM Packages runtime dependencies

### ISSUE THREAD

**Issue by kanivenk** [jspm/jspm-cli#1869]
We use bunch of jspm enabled ( we set "jspmNodeConversion": false in package json ) custom packages in multiple apps and whenever we deploy apps we package all jspm dependencies but we want to avoid this for the following reasons 
1. the size of these dependent packages is huge which is around 1.6 GB.
2. want to remove the need for app teams to check-in all their packages with each project.
3. if any change in one jspm package we have to update this package in all app instances

Just checking here if any other approaches to handle these jspm dependencies at runtime.

**Comment by joeldenning** [comment]
Hey @kanivenk I'm actually doing much the same thing in some projects that I'm using. Here's what I'm doing to share dependencies across bundles:

1. Create a common dependencies bundle, something like `jspm bundle react + react-dom + lodash common-dependencies.bundle.js`
1. In your html file(s), `<script src="/common-dependencies.bundle.js"></script>`
1. Use [arithmetic building](https://github.com/jspm/jspm-cli/blob/ff46dbcada4236603649344913aa543011dcfbc1/docs/production-workflows.md#creating-a-bundle-with-arithmetic) to subtract out specific dependencies from each of your apps. This could be done with `jspm build my-app - react - react-dom - lodash my-app.build.js`. Make sure that you `System.import('my-app.build.js')` (or `<script>` tag it) **after** the common dependencies bundle is loaded.

This works really well for me, another thing you can look into is marking dependencies as `external`. This one I don't know as much about because I don't use it, but it's an alternative to arithmetic building

**Comment by guybedford** [comment]
Are you looking to share jspm_packages at install time, or in the web
browser itself?

**Comment by kanivenk** [comment]
we have shared jspm packages repository and jspm cli is configured to get packages from this shared location and so we are good there ( during install ).
we are looking to share these dependencies at run time ( web browser ).

joeldenning,
Thanks for quick reply .. we will definitely try that approach and get back.

**Comment by kanivenk** [comment]
When we are using this bundle technic to handle jspm runtime dependencies we are getting System undefined error

**the bundle command we are using** 
jspm bundle npm:angular@1.4.4 + github:systemjs/plugin-css@^0.1.20 + github:components/jquery@^1.11.3 + github:systemjs/plugin-json@^0.1.0 + github:systemjs/plugin-text@^0.0.4 common-dependencies.bundle.js  

**Error** 
 config.js:1 Uncaught ReferenceError: System is not defined(anonymous function) @ config.js:1
config-buic.js:1 Uncaught ReferenceError: System is not defined(anonymous function) @ config-buic.js:1

apart from adding this common-dependencies.bundle.js to html page do we need to make any other changes.

**Comment by joeldenning** [comment]
@kanivenk Do you have systemjs on the page via script tag? Here is what my project looks like, I've added some comments to hopefully help explain what's going on.

```html
<html>
  <head>
    <!-- We have to script tag system.js for any jspm bundle'd files and for any runtime dependencies -->
    <script src="/system.js"></script>
    <script src="/system-polyfills.js"></script>
    <!-- the jspm.browser.js and jspm.config.js are the ones for my root project (where I built the common dependencies from) -->
    <script src="/jspm.browser.js"></script>
    <script src="/jspm.config.js"></script>
   <!--
         This is the bundle built with jspm bundle react + react-dom + lodash...
         We use jspm bundle because all of the modules are then System.importable.
         Also you <script> tag bundles created with jspm bundle, but you System.import
         bundles that were created with jspm build if you need those bundles to have
         runtime dependencies.
   -->
    <script src="/common-dependencies.bundle.js"></script>
  </head>
  <body>
    <script>
      /* Both of these System.imports are importing files that were built with
       * `jspm build` (not jspm bundle), since `build` creates smaller and more
       * performant bundles. The only drawback is that other bundles cannot import
       * the individual modules that were included in a jspm build. This is why
       * there is a common dependencies bundle which is not created with jspm build.
       * These built files have runtime dependencies that will be retrieved from the
       * common dependencies bundle.
       */
      System.import('/my-project-with-runtime-dependencies.build.js');
      System.import('/my-other-project-with-runtime-dependencies.build.js');
    </script>
  </body>
</html>
```

**Comment by kanivenk** [comment]
Thanks for quick reply! 
added system.js file as specified in the above HTML file and the page is rendering fine but when I hit F12 I see the below error in console tab.

jquery.js:10352Uncaught ReferenceError: System is not defined(anonymous function) 
@ common-dependencies.bundle.js:3(anonymous function) 
@ jquery.js:10352
I tried including jquery too but still the same error.

And also I see some files are downloading fro jspm_packages folder...getting the below error because I re-named my jspm_packages folder to something else.
GET http://127.0.0.1:8080/jspm_packages/npm/angular@1.4.4.js 404 (Not Found)

**Comment by joeldenning** [comment]
It looks like you're using `plugin-text`? Have you done `jspm install plugin-text`? If so, is your code running locally where the webserver has access to the jspm_packages directory? Another option is to put `plugin-text` into the common-dependencies bundle.

**Comment by kanivenk** [comment]
correct, we use plugin-text and its already installed .. i also verified that this exists in jspm_packages folder.
When we have jspm_packages folder then application renders fine .. but when we remove jspm_packages folder then we see that above mentioned error.

the bundle command we are using is 
**jspm bundle npm:angular@1.4.4 + github:systemjs/plugin-css@^0.1.20 + github:components/jquery@^1.11.3 + github:systemjs/plugin-json@^0.1.0 + github:systemjs/plugin-text@^0.0.4 common-dependencies.bundle.js** 

and this bundle command has plugin-text package

**Comment by joeldenning** [comment]
Ah sorry I didn't see how you already provided the command you're using for the bundle and that plugin-text was already in there. I am guessing that this problem happens when you try to `System.import` a bundle that was built with `jspm build`? And you're probably using plugin-text to import html templates into your angular application?

I can't claim that I know exactly what's happening that's causing the problem, but here are the steps I would take to debug:
1. How are you using plugin-text? Are you using `!text` (e.g., `import html from './html!text'`)? If you're using `!text`, then inside of your package.json, is `"text": "github:systemjs/plugin-text@^0.0.4"` in the jspm dependencies?
2. Inside of your `common-dependencies.bundle.js` file, can you find a `System.register` for `plugin-text`? If so, note the exact name of the registered module (probably `github:systemjs/plugin-text@0.0.4`?)
3. Inside the angular app's bundle that was built with `jspm build`, do you see `plugin-text` as an external dependency? Figuring that out will depend on the format that you're `jspm build`ing to. If you're building to AMD, for example, then look for the `define([..., 'plugin-text'])` at the bottom. Be sure to note if the dependency has a version or if it is just `plugin-text`.

Also, what version of jspm are you using?

**Comment by joeldenning** [comment]
Also, another question to think about is why you need plugin-text at runtime? Are you using angular partials to load your templates or something? Why aren't the templates built into the angular bundle so that `plugin-text` is not needed at runtime?

In general, I usually try to build everything into the bundle so that I don't have to have all of my loaders/plugins available at runtime. Especially for plugin-css since it is actually a pretty gigantic library to include in the browser.

**Comment by kanivenk** [comment]
Thanks for the detailed debugging steps. This really helped me to move further in testing.

we are using the plugin-text the way you mentioned and I also verified bundle file and I see references of plugin-text and also verified the version.

I re-bundled adding "app" to my bundle command and magically that worked. not sure if that's the right way to and also not sure if that meets our common runtime dependencies requirement.

The new bundle command 
jspm bundle app npm:angular@1.4.4 + github:systemjs/plugin-css@0.1.20 + github:components/jquery@1.11.3 + github:systemjs/plugin-json@0.1.0 + github:systemjs/plugin-text@0.0.4 common-dependencies.bundle.js 

We may have to do more testing on this to see if any gaps.

**Comment by joeldenning** [comment]
I'm glad to hear that it's working for you now.

One small thing that makes things more convenient when bundling is to use the raw, non-normalized name in your `bundle` and `build` commands. So instead of doing 

```bash
jspm bundle app npm:angular@1.4.4 + github:systemjs/plugin-css@0.1.20 + github:components/jquery@1.11.3 + github:systemjs/plugin-json@0.1.0 + github:systemjs/plugin-text@0.0.4 common-dependencies.bundle.js
```

you can just do

```bash
jspm bundle app + angular + plugin-css + jquery + plugin-json + plugin-text common-dependencies.bundle.js
```

Not only is that way more concise, but you also don't have to update your build script if you update your dependencies. The way that it works is that as long as your `jspm.config.js` file has the correct mapping set up (which jspm takes care of for you), systemjs-builder will be able to use the correct version of the dependencies.

**Comment by joeldenning** [comment]
Yeah you can do that with the client base url configuration option in your package.json. See the client baseURL option in https://github.com/jspm/jspm-cli/blob/ff46dbcada4236603649344913aa543011dcfbc1/docs/getting-started.md#2-create-a-project

**Comment by kanivenk** [comment]
Awesome! We followed that article and now we are able to refer remotely hosted jspm packages from app during runtime.

Thanks lot for all suggestions.
