### ISSUE TITLE
Unable to bundle enzyme in jspm@0.17

### ISSUE THREAD

**Issue by xiankai** [jspm/jspm-cli#1875]
1. ```jspm install enzyme```
3. `jspm install npm:enzyme -o "{map: {'react/lib/ReactContext': '@empty', 'react/addons': '@empty', 'react/lib/ExecutionEnvironment': '@empty'}}"`
  - from https://github.com/airbnb/enzyme/issues/302#issuecomment-215422167, after removing -dev flag as it doesn't work in builds
4. `jspm bundle enzyme`
  - I get the following error message: 
```
     Building the bundle tree for enzyme...

err  Error on fetch for npm:enzyme@2.3.0/build.js at file:///Users/kj/jspm-test/jspm_packages/npm/enzyme@2.3.0/build.js
  Error: ENOENT: no such file or directory, open '/Users/kj/jspm-test/jspm_packages/npm/enzyme@2.3.0/build.js'
    at Error (native)
```

whereas this works fine in jspm@0.16 - any clue?

**Comment by guybedford** [comment]
This was an issue with the main entry point actually, fixed in https://github.com/jspm/npm/commit/bb61d1e586bfb5e26dd23f7fdd44affa8bcbd115.

You can workaround it with the override `jspm install npm:enzyme -o main=build/index.js`

Rather than mapping react individual submodules to empty, the following got me a little further:

```
jspm bundle enzyme --externals react/lib/ReactContext react/addons react/lib/ExecutionEnvironment @empty/server react-addons-test-utils
```

There's still an issue then though:

```
err  Error on fetch for npm:htmlparser2@3.8.3/lib/ at file:///Users/guybedford/Projects/jspm-cli/sandbox/jspm_packages/npm/htmlparser2@3.8.3/lib/
  Loading npm:htmlparser2@3.8.3/lib/ProxyHandler.js
  Loading npm:htmlparser2@3.8.3/lib/index.js
  Loading npm:cheerio@0.20.0/lib/parse.js
  Loading npm:cheerio@0.20.0/lib/cheerio.js
  Loading npm:cheerio@0.20.0/index.js
  Loading npm:enzyme@2.3.0/build/ReactWrapper.js
  Loading npm:enzyme@2.3.0/build/index.js
  Error: EISDIR: illegal operation on a directory, read
    at Error (native)
```

The above bug is a known bug in SystemJS unfortunately at https://github.com/systemjs/systemjs/issues/1164.

This can be worked around by editing both `npm:htmlparser2@3.8.3/lib/ProxyHandler.js` and `npm:htmlparser2@3.8.3/lib/ProxyHandler.js` files and replacing `require("./")` with `require("./index.js")` within them - that then seemed to get this working for me here.

**Comment by xiankai** [comment]
Hey thanks for the follow up, that workaround managed to get me further. However I encountered another roadblock in trying to set up tests - although this time it's more related to running jspm on node.

1) `jspm install mocha`
2) edit `test.js` with
```
var Mocha = new require('mocha');
var mocha = new Mocha();
mocha.addFile('/');
mocha.run();
```
3) `jspm run ./test.js`

**Comment by xiankai** [comment]
Thanks for the workaround, I managed to get past that hurdle. I have encountered another problem though so I have set up a new ticket for it #1878

**Comment by guybedford** [comment]
The above SystemJS issue has also been fixed now so the bundle command is working now in the next 0.17 beta.

**Comment by tamird** [comment]
By the way, why is it that systemJS tries to load these files in the first place? Those `require`s shouldn't execute?

**Comment by guybedford** [comment]
@tamird CommonJS requires are statically traced in SystemJS by a regex detection, to support async browser loading, similar to how Browserify or webpack statically trace requires. So they are loaded regardless of actual execution, unless configured otherwise through metadata. Does that answer your question?

**Comment by tamird** [comment]
Yep, thanks for the explanation.
