### ISSUE TITLE
uninstall does not remove peerDependencies

### ISSUE THREAD

**Issue by sondreb** [jspm/jspm-cli#1901]
Installing for example "lokijs" will populate the peerDependencies with many nodelibs packages. When running uninstall, it does not remove the same packages.

jspm -v: 0.17.0-beta.18

(Tried searching and found no issues open or closed on this)

**Comment by guybedford** [comment]
The issue here is that peerDependencies can be installed at the top level by the user - `jspm install x --peer` so we don't necessarily know who installed it first - a dependency package or the user.

One option might be to not install dependency peer dependencies into the top-level package.json as peerDependencies, and just leave them as top-level map entries in the configuration file. The risk with this approach is that we lose the ability to prune unnecessary top-level maps from the configuration file, but perhaps that's a suitable tradeoff.
