### ISSUE TITLE
Doesn't work on Windows 10

### ISSUE THREAD

**Issue by LFeh** [jspm/jspm-cli#1919]
Hi guys,

I'm with a error to run the jspm on Windows 10.

````
gulp-jspm: Error on fetch for containers/app/index.js at file:///C:/Users/Felipe/Dropbox/Projects/Development/eventos/src/containers/app/index.js
        Loading js\index.js
        Error: ENOENT: no such file or directory, open 'C:\Users\Felipe\Dropbox (Pessoal)\Projects\Development\eventos\src\containers\app\index.js'
    at Error (native)
[10:30:30] Plumber found unhandled error:
 Error in plugin 'gulp-jspm'
Message:
    Error on fetch for containers/app/index.js at file:///C:/Users/Felipe/Dropbox (Pessoal)/Projects/Development/eventos/src/containers/app/index.js
        Loading js\index.js
        ENOENT: no such file or directory, open 'C:\Users\Felipe\Dropbox (Pessoal)\Projects\Development\eventos\src\containers\app\index.js'
Details:
    originalErr: Error: ENOENT: no such file or directory, open 'C:\Users\Felipe\Dropbox (Pessoal)\Projects\Development\eventos\src\containers\app\index.js'
````

In this project - https://github.com/frontendbr/eventos

What's the problem?

**Comment by DavidStrada** [comment]
What would be the steps one has to follow in order to reproduce your error ? I'm seeing gulp-jspm error. so is it related to jspm or gulp task ?

**Comment by DavidStrada** [comment]
and it states that it can not find `Error on fetch for containers/app/index.js`

**Comment by BiggerNoise** [comment]
Hopefully this is more light than heat, but I think I am seeing the same issue.

I am bundling with jspm from a gulp task which looks something like:

```
gulp.task('build', function() {
	var dist = path.join(paths.dist + 'app.js');
	// Use JSPM to bundle our app
	return jspm.bundleSFX('client/app/**/*.js', dist, {
		mangle: false,
		minify: false
	})
```

I have an app.js file which includes other files in the client/app directory hierarchy

```
/* App */
import Common from './common/common';
```

With jspm at 0.16.38, I was receiving an error on the import line:

```
$ gulp build
[13:55:32] Using gulpfile ~\dev\Pioneer\HSE_Web\src\web\Gulpfile.js
[13:55:32] Starting 'build'...
[13:55:33] 'build' errored after 1.24 s
[13:55:33] Error on fetch for common/common.js at file:///C:/Users/adavis/dev/project/src/web/common/common.js
        Loading client\app\app.js
        Error: ENOENT: no such file or directory, open 'C:\Users\adavis\dev\project\src\web\common\common.js'
    at Error (native)
```

When I pinned jspm at 0.16.36 my gulp build started working again. I am on W10 x64.

The gulp file is located at C:\Users\adavis\dev\project\src\web

**Comment by guybedford** [comment]
Where is the `App` file located? In `client/app/app.js`? Do you have other configuration present?

I'm not aware of any windows-specific resolution issues at the moment, so a simple replication would be very welcome.

**Comment by LFeh** [comment]
I'll @fdaciuk to this issue...

**Comment by BiggerNoise** [comment]
I created a small repo that demonstrates the issue that I am having:
https://github.com/BiggerNoise/demonstrate-jspm-issue

@LFeh - Can you take a look and see if it is actually the same problem you are having? I don't want to muddy the water if we're actually seeing two separate things.

**Comment by fdaciuk** [comment]
Hi @guybedford! I've tried to help @LFeh on this issue, but no success :(
The same configuration works fine on Mac or Linux. The problem is just using Windows. We try to change `baseURL` on `package.json`, setting `src/js`, but the file cannot be imported properly.

At the first error line: `containers/app/index.js at file:///C:/Users/Felipe/Dropbox/Projects/Development/eventos/src/containers/app/index.js`

`containers/app/index.js` is located on `src/js/containers/app/index.js`. In the code, the call for this file is `./containers/app/index`: https://github.com/frontendbr/eventos/blob/develop/src/js/index.js#L6 (with "dot and slash" at the beginning).

I think (and don't know why), on Windows, `jspm` try to search this file in `src` directory, and not on `src/js` that is the right place.

**Comment by BiggerNoise** [comment]
Confirmed that my project does not exhibit the issue on OSX

**Comment by guybedford** [comment]
This is because bundling works in URL space. So adding `.replace(/\\/g, '.')` to the line at https://github.com/BiggerNoise/demonstrate-jspm-issue/blob/master/Gulpfile.js#L12 will fix the normalization.

This is tracking in https://github.com/systemjs/systemjs/issues/1317 though - I believe according to the URL spec, we should turn `\` into `/` anyway.

**Comment by BiggerNoise** [comment]
That doesn't seem to be helping. To guard against the possibility that I am misunderstanding your instructions, here's the function that I ended up with:

```
var resolveTo = function(resolvePath) {
	return function(glob) {
		glob = glob || '';
		return path.join(root, resolvePath, glob).replace(/\\/g, '.');
	}
};
```

Am I off in the weeds? Is there any other information that I can provide?

**Comment by guybedford** [comment]
Sorry that was a type - you've got it exactly right only it should be:

.replace(/\\/g, '/')

**Comment by BiggerNoise** [comment]
Yes. This works around the issue. I'll update the read me on my example.

Thank you very much for the help.
