### ISSUE TITLE
unable to install package due to array-find dependency

### ISSUE THREAD

**Issue by Mosho1** [jspm/jspm-cli#1925]
Using 0.16.33.

I'm getting this:

```
Package.json dependency array-find set to npm:array-find@^1.0.0, which is not a valid dependency format for npm.
     It's advisable to publish jspm-style packages to GitHub or another registry so conventions are clear.
```

And this is the relevant dependency from package.json:

```
"jspm": {
    "dependencies": {
      "array-find": "npm:array-find@^1.0.0",
    }
  }
```

**Comment by guybedford** [comment]
If installing the package from npm, you'd need to add `jspmNodeConversion: false` or `registry: 'jspm'` as the point is that the above is not a valid npm version style.

**Comment by Mosho1** [comment]
It looks the same as any other dependency in the package though

**Comment by guybedford** [comment]
You mean there are other dependencies like this that do work?

I'd really suggest adding `jspmNodeConversion: false`. Otherwise code on npm should follow npm conventions. See https://github.com/jspm/jspm-cli/blob/master/docs/publishing-packages.md#publishing-jspm-style-packages-to-npm for more info.
