### ISSUE TITLE
Recursive mappings created for some packages

### ISSUE THREAD

**Issue by graynorton** [jspm/jspm-cli#1959]
In JSPM 0.17.0-beta.18 and later, the auto-generated JSON config files for some packages contain recursive mappings. These recursive mappings cause errors when bundling.

To repro:

1. Create a new directory and `npm install jspm@beta`
2. `jspm install core-js` (for example). Follow prompts to create package.json and configure, accepting all defaults.
3. When installation is complete, inspect `jspm_packages/npm/core-js@2.4.0.json`

=> You'll see that `./library` maps to `./library/index.js` (for example)

**Comment by OrKoN** [comment]
@graynorton it seems to bundle fine for me with beta.22. As far as I know, the ./library mapped to ./library/index.js does not cause recursion - it simply saying that if ./library (exact match) is imported use ./library/index.js instead because the ./library is a directory.

Can you provide additional info how to reproduce the issue?

I have done the following in addition to your steps: `mkdir src; echo "import 'core-js';" > src/app.js; jspm bundle src/app.js` and got no errors.

**Comment by graynorton** [comment]
Thanks for the follow-up, @OrKoN.

I did a bit more digging, and it appears that the problem was due to an anomaly in my local setup (details below, if you're curious).

Sorry for the false alarm.

---

I'm working on an experimental package that treats JSPM as a peer dependency (a lightweight wrapper around JSPM's bundling functionality with a specific use case in mind). I'm testing my package against a few different projects, using `npm link` to include my package in each test project. I updated JSPM to beta.22 in one of my test projects, but (due to the way npm linking and peer dependencies interact) my package was still pulling in its JSPM dependencies from its locally installed copy of beta.17. As a result, I had an older (more restrictive) check for circular mappings running against newer package config files and bailing out.
