### ISSUE TITLE
Builder/text-plugin/CommonJS combination produces different results in development vs bundle

### ISSUE THREAD

**Issue by bkad** [jspm/jspm-cli#1973]
This is on version 0.17.0-beta.22

I'm using the CJS syntax in combination with the text-plugin and the behavior is different when developing versus the bundling. I've reduced it down to a [base case](https://github.com/bkad/text-build-bug). In development the `require("file!text")` returns a string whereas the bundle makes the require call the string wrapped in an object with a single property `default`.

**Comment by amenadiel** [comment]
it seems this is the expected behavior. If you look at the [translate hook](https://github.com/systemjs/plugin-text/blob/master/text.js) it states that, if we're in the build step, and there's a transpiler defined in our config, then it will assume format 'esm' and translate as

```js
'export default ' + JSON.stringify(load.source) + ';';
```

in other words, it exports the result as an ES6 module. Using cjs require or amd define on an ES6 module will give you an object whose default property is what would otherwise be the module itself.

You have two ways to go, here. First: since you're using a transpiler, then just treat everything as an ES6 module:

```js
import foo from "./input!text";
console.log(foo);
```

Second: a dirty reasignement:

```js
var foo = require("./input!text");
if(foo.default) {
  foo = foo.default;
}
console.log(foo);
```

**Comment by bkad** [comment]
This seems to be a regression from plugin-text@0.0.5 and onward. Thanks for pointing it out, I'll log the issue there.
