### ISSUE TITLE
jspm can't install system.js from github

### ISSUE THREAD

**Issue by simaodeveloper** [jspm/jspm-cli#2007]
Hey guys i got this problem:

```
$ jspm install

warn Running jspm globally, it is advisable to locally install jspm via npm install jspm --save-dev.
ok   Install tree has no forks.
     Looking up loader files...

warn Error on lookup for github:systemjs/systemjs, retrying (1).
     Error

warn Error on lookup for github:systemjs/systemjs, retrying (2).
     Error

warn Error on lookup for github:systemjs/systemjs, retrying (3).
     Error

warn Error on lookup for github:systemjs/systemjs
     Error

err

err  Error downloading loader files.

warn Installation changes not saved.
```

**Comment by guybedford** [comment]
Can you run `git ls-remote https://github.com/systemjs/systemjs` on your machine ok?

**Comment by clarenced** [comment]
I have the same problem and I can execute `git ls-remote https://github.com/systemjs/systemjs` with no error

**Comment by guybedford** [comment]
Is this with jspm 0.17?

**Comment by clarenced** [comment]
I finally find the solution to my problem. As explained in the [Controlling proxy behaviour using environment variables](https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables), you have to set the environment variables HTTP_PROXY and HTTPS_PROXY. Maybe you will have to put your credentials in the proxy in the form `http://username:password@host:port`

I was using `npm` behind a proxy but it seems that the proxy configuration in npm is unnecessary since jspm is basing on the env variable, so i removed the proxy key with `npm config rm proxy` and also set the `registry ` key to `http://registry.npmjs.org` instead of `https`. 

Maybe the last 2 steps are not necessary but this is what is working for me

**Comment by simaodeveloper** [comment]
Hey guys, I will test later and comeback with some log.

**Comment by tamird** [comment]
I am able to reproduce this with 0.17 when github authentication is set up.
