### ISSUE TITLE
Is it safe to cache JSPM_GLOBAL_PATH directory?

### ISSUE THREAD

**Issue by teohhanhui** [jspm/jspm-cli#2030]
e.g. for CI builds

**Comment by guybedford** [comment]
I'm not sure I completely follow. I think so?

**Comment by teohhanhui** [comment]
Well, I mean it wouldn't cause a problem even if something in there has become outdated, right? But I'm worried about the config... It'd be great if there can be a separation of cache and config etc., so that I can know for sure that there wouldn't be outdated config (persisted in a Docker volume, for example) that doesn't get overridden.

**Comment by guybedford** [comment]
If the config works to install from github or npm, there's nothing wrong with caching that too. If you're worried about it, reconfigure the github and npm registry configurations in each CI script to avoid that being cached by overwriting. But otherwise I think this is fine yes. We do need to hold config and registry caching together though because the registry cache is specific to the configuration used! For example if I configure github to refer to npm (I could do this if I really want).

But caching takes into account the registry instance used so it should be difficult to corrupt.
