### ISSUE TITLE
`jspm registry config github` doesn't work when entered access token.

### ISSUE THREAD

**Issue by d34th4ck3r** [jspm/jspm-cli#2078]
On using command `jspm registry config github`  We have following flow:
 `gautambajaj@Gautams-MacBook-Pro  ~/Codes/upstream   dev ●  jspm registry config github`
`Would you like to set up your GitHub credentials? [yes]:yes`
`     If using two-factor authentication or to avoid using your password you can generate an access token at https://github.com/settings/tokens.`

`Enter your GitHub username or access token:<my-token>` 
`Would you like to test these credentials? [yes]:yes`
`ok   GitHub authentication is working successfully.`
`ok   Registry github configured successfully.`

If we enter token when it ask `Enter your GitHub username or access token:` it fails later:
`gautambajaj@Gautams-MacBook-Pro  ~/Codes/upstream/wp-content/themes/upstream   dev ●  jspm install github:org/repo`
`     Looking up github:org/repo`
`Username for 'https://github.com': d34th4ck3r`
`Password for 'https://d34th4ck3r@github.com':`

`warn Error on lookup for github:wikia/ad-engine, retrying (1).`
`     Error: remote: Invalid username or password.`
`     fatal: Authentication failed for 'org/repo.git/'`

Btw, you might also want to  updated the strings from Password to Access Token. Because the way it worked for me was only when I use Access Token whenever it prompted to ask for password.

**Comment by guybedford** [comment]
//cc @tamird

**Comment by tamird** [comment]
I'm not sure what's going on here. Can you try clearing your jspm config and trying again? `rm ~/.jspm/config` should do it.

**Comment by dalemanthei** [comment]
I think the issue is between versions of jspm. 

Version 0.15.x has two prompts when creating a registry: First a user name, then a token (which doesn't display). Version 0.16.x has only one prompt for username or token. We found that installing jspm 0.15.x globally and using that to create the registry, but installing jspm 0.16.x in the local project works ok.

The auth key from `jspm registry export` on the 0.15.x created registry is a hash of some sort. The auth key from the 0.16.x created registry is exactly the same as the github token provided when configuring the registry.

**Comment by guybedford** [comment]
@dalemanthei are you saying for certain here that you are unable to create a key that works for you with 0.16.x?

**Comment by guybedford** [comment]
This should be working in the latest 0.16 release which reverts back to the old prompts. Just let me know if you are still having any issues with this at all.

**Comment by a-nasri** [comment]
Hello my actuall jspm version is 0.16.53 and i still have the same problem.

**Comment by a-nasri** [comment]
@guybedford  may reopen this issue please ?
