### ISSUE TITLE
Load file on demand

### ISSUE THREAD

**Issue by nlhkh** [jspm/jspm-cli#2113]
Perhaps I misunderstand the purpose of `jspm` and `systemjs`, but I get the impression that `systemjs` help building app that can load multiple javascript files on demand to take advantage of `HTTP/2`. When playing with `jspm`, I see there there is only an option to bundle everything into 1 big fat file, which is a traditional way. Is there a possibility that I can also bundle into multiple files, given that I am creating a ReactJS app with ES6 syntax?

**Comment by Nek-** [comment]
Hello,

It's all about configuration :) . Learn more in the documentation of [JSPM](http://jspm.io/docs/index.html) and the one of SystemJS (because it's a problem of [SystemJS configuration](https://github.com/systemjs/systemjs/tree/master/docs)).

You can discuss things with community on [gitter](https://gitter.im/jspm/jspm). Here is an issue tracker.

**Comment by nlhkh** [comment]
Thanks @Nek- :)
