### ISSUE TITLE
Setting up a Github repo as a JSPM dependency

### ISSUE THREAD

**Issue by matthew-dean** [jspm/jspm-cli#2122]
In http://jspm.io/0.17-beta-guide/publishing.html it mentions how to setup a component to include in a project. However, I can't reason out how you would:
- Set up component A in a Github repo, using JSPM as a package manager to install dependencies
- Set up site B, importing component A via JSPM, such that JSPM will install any JSPM dependencies listed in component A's `package.json` file.

In short: how do you use JSPM to replace NPM in terms of a dependency's dependencies? Is JSPM only equipped for / intended for use only on the website "endpoint" repo, and not used to manage any of the dependencies of components?

Is the proper way to format component A for/using NPM, and format site B for/using JSPM? Because, ideally, I'd like to be able to teach web devs to use JSPM as the primary package manager for the main project and custom dependencies.

**Comment by guybedford** [comment]
When the `registry` property is set in the package.json, that determines how the dependencies from the package.json are loaded. When installing from GitHub, jspm by default ignores dependencies unless the `registry` property is set because often they are unwanted in the GitHub context. A warning about this is shown in the install log, and it can be changed via an override - `jspm install github:some/pkg -o "{registry:'github'}"` (or `npm`).
