### ISSUE TITLE
Possible to install without version in folder name?

### ISSUE THREAD

**Issue by Izzmo** [jspm/jspm-cli#2124]
Is it possible to install a module without it including the version in the folder name? I understand the implications and know the reasoning behind this, but I'm attempting to use jspm a little differently for our setup.

We have multiple sites which use the same packages, but we don't really want to include the distribution JS compiled/transpiled files, but instead want to include the source TypeScript files when it downloads the package. Then we can just use them straight in our editor and then compile them all together.

For example, this works:

`import { someClass } from '../github/my-repo/my-class@1.0.0/my-class;`

But would be better to have:

`import { someClass } from '../github/my-repo/my-class/my-class;`

And ideally:

`import { someClass } from 'my-class/my-class;` (then have the option to include a version override if necessary)

As a follow up it looks like SystemJS supports the correct mapping from `jspm install` when I do 'my-class/my-class' in the import, but TypeScript throws a compilation error, preventing us from getting very far. Declaration files should not have to be used here either, in my opinion.

**Comment by jerryorta-dev** [comment]
I created a proof of concept which I believe addresses your request, or possibly comes close.

In [this repo](https://github.com/UIUXEngineering/uidk-ng-1x-src/tree/master/client/app/uidk/config.translation), I create an [npm module](https://www.npmjs.com/package/@uiuxengineering/uidk-ng-1x-translation) which has both [source](https://github.com/UIUXEngineering/uidk-ng-1x-src/blob/master/client/app/uidk/config.translation/src.js) and [compiled](https://github.com/UIUXEngineering/uidk-ng-1x-src/blob/master/client/app/uidk/config.translation/index.js) code. How you install it in a consuming app is configured in the [package.json](https://github.com/UIUXEngineering/uidk-ng-1x-src/blob/master/client/app/uidk/config.translation/package.json).

Then the consumption would like [this](https://github.com/UIUXEngineering/angular1-ES6-jspm-gulp-seed/blob/master/client/app/config/_ng.configs.js#L2) for compiled code if NOT using JSPM ( for people using browserify or straight systemjs without a transpiler ):

```js
    import configTranslate from '@uiuxengineering/uidk-ng-1x-translation';
```

or this for non-compile ( source ) code using jspm, the sytemjs will find the "src.js" file by default ( magic ! ) due to the jspm configuration in the package.json. But, you can also import source directly such as:

```js
    import configTranslate from '@uiuxengineering/uidk-ng-1x-translation/src';
```

This should all work with TypeScript as well as this is SystemJS / JSPM functionality, and not related to transpilation.

**Comment by Izzmo** [comment]
@jerryorta-dev interesting. I wonder if it's because I'm missing the src.js file in my repo. This is the repo in question I'm trying to integrate: https://github.com/gtmsportswear/js-local-storage-manager

1. Do you think that the fact you are using src.js instead of src.ts helps SystemJS pick up on that file?
2. Does using NPM instead of Github eliminate the versions in the URL?

Thanks again for taking the time to reply.
