### ISSUE TITLE
npm package works jspm does not

### ISSUE THREAD

**Issue by oppianmatt** [jspm/jspm-cli#2133]
For a particular module, `sw-offline-google-analytics`, trying to use jspm to handle the dependencies instead of npm. Did a `jspm install sw-offline-google-analytics --dev` but the file doesn't work. Yet use the same file in npm and it does work. Initially raised the issue on the javascript modules issue tracker but if it works in npm, then surely it's a jspm issue?

https://github.com/GoogleChrome/sw-helpers/issues/47

**Comment by aluanhaddad** [comment]
The error message we get from running jspm install tells us what our first problem is and how we might solve it:

```powershell
> jspm install sw-offline-google-analytics
     Updating registry cache...

err  Repo jspm:sw-offline-google-analytics not found. 
Perhaps try jspm install npm:sw-offline-google-analytics.
```

OK, so we try
```powershell
> jspm install npm:sw-offline-google-analytics
     Updating registry cache...
     Downloading npm:sw-offline-google-analytics@1.1.1

warn Package npm:sw-offline-google-analytics@1.1.1 has no "main" 
entry point set in its package config.
ok   Installed sw-offline-google-analytics to npm:sw-offline-google-analytics@^1.1.1 (1.1.1)
     Install tree has no forks.

ok   Install complete.
```
So now we have a bit of an issue. 
As per the warning, the package.json does not specify metadata about the a package entry point.
thusly, the following will fail:
_app.js_
```js
import 'sw-offline-google-analytics';
```
_index.html_
```html
<script>SystemJS.import('app').catch(function (e) { console.error(e); });</script>
```

To fix this we have a few options, we need to look in the repo and figure out the name of the primary file if applicable, in this case it is easy since there is only one `.js` file present. With this knowledge we can either run
  1. reinstall the package specifying the main explicitely

 ```powershell
    jspm install npm:sw-offline-google-analytics --override "{
      main: 'offline-google-analytics-import.js'
    }"
    ```

  2. alter _app.js_ to be
    ```js
    import 'sw-offline-google-analytics/offline-google-analytics-import';
    ```
Keep your GoogleChrome/sw-helpers#47 open and ask the maintainers to setup an entry point. This is important for lots of tools to work with it correctly.

One thing worth noting is that in spite of the lack of information jspm did in fact parse the package contents and determined it was not a module, despite being published into a _cjs_ environment. If the maintainers on not amenable to adding a main field for whatever reason, we can publish an override to the _jspm-registry_.

**Comment by aluanhaddad** [comment]
It is worth noting that their code examples run in webworkers and use a combination of require and import scripts to reference files above the package.json iteself. The actual file we want is imported as
```js
importScripts('../build/offline-google-analytics-import.js');
```
Which is not exactly saying it works out of the box with node's require.
The `build` directory is located _above_ the `package.json` that complicates things.
However, even if it were co-located, the build script is not specified in any npm publish or install scripts in the `package.json`. It won't be run automatically by npm or jspm and so the directory will never exist unless the push it to their repo.

If we look in the `package.json` in the root of //github.com/GoogleChrome/sw-helpers we see something a little worse. There is a main specified, but it points at a `gulpfile.babel.js`. That is not a good idea.

**Comment by DavidStrada** [comment]
I would say you have 2 options : 

1. would be like you mentioned before adding an overwrite and include the "main" entry point for the package.

2. would be creating a fork ( assuming it's on github ) and adding the main entry point there, then installing it via `jspm install github:xxx/yyy", perhaps send a PR to package maintainer ? .
