### ISSUE TITLE
Question: When will 0.17 be released? 

### ISSUE THREAD

**Issue by Martin-Andersen** [jspm/jspm-cli#2152]
I am a little nervous for the future of jspm. all the boys are moving to webpack or choosing webpack instead of jspm for new projects.

I don't know when 0.17 will be finished, but why not bump it up to version 1.0? I know semver is a b*tch if you plane on having many breaking changes, But a 1.0 version would be nice.

**Comment by aluanhaddad** [comment]
I second this. I'm not sure if a version bump is the right way to go, but everyone is jumping on the Webpack bandwagon as if it is the only option. 
When I explain what jspm offers, that it actually manages dependencies in a sound manner, and that it supports interop between multiple teams using multiple transpilers, workflows, and languages people get excited. I think jspm is getting overlooked by people who are suffering from the very problems it solves.

**Comment by Martin-Andersen** [comment]
The CLI for Ionic 2 is using webpack, the Angular CLI now have an option for using webpack instead of JSPM, and I think that the are dropping support for JSPM.
Not a good sign.
So get to work. I think that JSPM is the right tool for the job we just need more plugins for SASS and LESS

**Comment by aluanhaddad** [comment]
There are already plugins for loading LESS and SASS.

With respect to any angular 2, it doesn't really supported jspm. Rather, jspm supports angular 2.

Angular 2 does support SystemJS, and you're correct that they are leaning away from it. 

I think that largely has to do with their insistence on using npm. Their documentation states that "angular developers use npm", so people have to set up all their dependencies manually, which makes using SystemJS more complicated than it needs to be. Comparatively using webpack then appears much simpler because webpack doesn't manage packages. Of course later they find out that what pack is resolving modules 6 directories above the base URL and will happily do ridiculous things like bundle multiple versions of angular 2 because it inherits all of the issues which make node and npm problematic for client site development, the example not understanding peerDependencies.

**Comment by PWKad** [comment]
Is there a list anywhere of what needs to be completed for 0.17 release?  Perhaps if it's not too big of a list it's something we could help to finish up.

**Comment by guybedford** [comment]
@PWKad great point. I think the main things are only to update the docs folder in https://github.com/jspm/jspm-cli/tree/0.17/docs to reflect 0.17 and to properly test and fix the remaining bugs on the upgrade path for 0.16.

I don't think there's much else stopping 0.17 if we had the above together, it's mostly been a documentation problem that's been tricky to prioritize when I've been having to focus on architectural changes already for jspm 0.18+.

**Comment by amenadiel** [comment]
I'm usin v0.17 in most of my projects.

I'd gladly see it promoted to a stable status, even if it means fixing the documentation ex-post.

**Comment by unional** [comment]
@amenadiel , as much as I want 0.17 to release, releasing it without the doc would be a very bad idea.

It is a huge release (and should bump to 1.0). If people see it is finally released and jump on it only to find the doc is confusing, they will be quickly turn off by and move away.

**Comment by guybedford** [comment]
If anyone is interested in contributing to documentation please do get in touch. Otherwise I expect we'll be looking at Jan / Feb.

**Comment by OrKoN** [comment]
@guybedford I am interested and I think I have some spare time for this.

**Comment by OrKoN** [comment]
I have started here: https://github.com/OrKoN/jspm-cli/pull/1 Just updated the existing getting-started. The big problem is that I don't know what all the options mean :-D The default ones worked for me perfectly.

**Comment by amenadiel** [comment]
I am willing to contribute. How should we proceed? It would be cumbersome to use PR for documentation.

**Comment by OrKoN** [comment]
@amenadiel I can give you write access to my fork and then we will open a PR when the docs are ready.

**Comment by amenadiel** [comment]
I'm ok with that.

**Comment by guybedford** [comment]
@OrKoN @amenadiel thanks so much for offering to help here!! If you have any specific questions, just copy me into an issue and I will respond as best as I can.

**Comment by guybedford** [comment]
jspm 2.0 will be the first major, finally :)
