### ISSUE TITLE
Feature request: make install --quick the default

### ISSUE THREAD

**Issue by frederikschubert** [jspm/jspm-cli#2153]
For most cases we found `jspm install --quick` to be sufficient and by orders of magnitude faster. IMO it would make more sense to make it the default (at least for the 0.17 branch) and put the current behavior behind a flag.
Are there any fundamental arguments against this change?

**Comment by guybedford** [comment]
`jspm install --quick` doesn't verify the `jspm_packages` folder at all, it just assumes that what is installed is correct. So `jspm install` as the default is necessary for correctness, otherwise strange bugs will happen. Having a correct install is important. I think just documenting `quick` better would be the way to go, as then the user is assuming the risks of an incorrect install.

**Comment by frederikschubert** [comment]
I see. Yes then documenting the cases in which --quick is sufficient would be the way to go.
Where should such documentation issues be opened?

**Comment by guybedford** [comment]
Let's mark this as a documentation issue then. A PR for the docs or any
suggestions for where to better clarify this would be great.

**Comment by frederikschubert** [comment]
I am happy to contribute such a PR. I think what is missing the most right now is a thorough description of what each of the central commands really does (install, update, ...) and in which use cases they should be applied.

**Comment by frederikschubert** [comment]
Should I add the documentation to the beta guide at the jspm.io repo?

**Comment by guybedford** [comment]
The `docs` folder at https://github.com/jspm/jspm-cli/blob/0.17/docs/installing-packages.md is supposed to be the documentation, but that has to still be upgraded to 0.17. Help upgrading any parts of this to 0.17 would be amazing.

**Comment by frederikschubert** [comment]
Alright. I will try to document my understanding of the current process.

**Comment by guybedford** [comment]
Thanks! There are no obligations here of course. Just let me know if you have any questions.

**Comment by frederikschubert** [comment]
On another note. Why have all the packages be re-downloaded for verification of correctness? Wouldn't it suffice to hash them after installation and check the directories against this hash when calling `jspm install` again?

**Comment by guybedford** [comment]
@frederikschubert it does just do a hash comparison and doesn't redownload. But it will look up the hashes fresh each time from the source, although this could be skipped for npm since tags are immutable on npm. This shows from the list of `Looking up` messages in the log. Only explicit `Downloading` messages in the log indicate the hash mismatch. If you are getting `Downloading` always showing then that would be a bug that the local cache isn't working correctly, and is worth following up!

**Comment by frederikschubert** [comment]
I believe the algorithm is working correctly and the traffic and delay comes mainly from the re-downloaded hashes.

**Comment by guybedford** [comment]
@frederikschubert it would be a bit of a job actually because we currently fetch this file - https://registry.npmjs.org/lodash, which contains all the package.json and hash information for all version tags. This file itself is cached with an ETag, but we need to check that it is fresh each time, so still incur a request for each package installed. Once we know that file is up-to-date, we then know all the hashes by tag.

To optimize this we would want to adjust the [registryAPI `lookup` method](https://github.com/jspm/jspm-cli/blob/master/docs/registry-api.md#lookuppackagename) to take a version parameter to deal with these kinds of partial lookups for exact versions and partial ranges as opposed to returning everything, then add the ability to just have that version argument work something like:

```javascript
lookup(packageName, version) -> { versions: { [version]: { hash: '...', ... } } }
```

Where if the version is contained in the pre-cached version data, we don't need to make a fresh request to the npm registry.

Semver matching then needs to be reconsidered because usually it is assumed that the version list returned by `lookup` is comprehensive, so jspm uses the list of versions to resolve version ranges. We may then need to add a new registry API hook - `versionList` to return a pure array of versions.

In doing all those changes that then alters the way jspm caches the registry API calls. The registry API was originally designed around the principle that jspm can take care of hashing details, but this sort of change would then along with allowing the registry API to take on more responsibility for its own caching, and have those functions like `versionList` and `lookup` get called regularly under the assumption they provide their own internal caching, as opposed to having jspm cache them.

So yeah, it's not a small job, but it would definitely be nice to do. It would also reduce overhead as downloading all that package.json data in these huge blobs makes jspm much slower than it needs to be. This sort of work would open the door to much bigger optimizations.

Performance optimizations at this level of jspm is just not something I can personally prioritize though. Getting the architecture right must come first. But PRs here would be amazing if anyone wants to work on this, and I would gladly provide the necessary feedback.

**Comment by amenadiel** [comment]
> jspm install --quick doesn't verify the jspm_packages folder at all, it just assumes that what is installed is correct

@guybedford the above sentence in misleading. It actually does install any missing packages from `jspm_packages`. I guess it just trusts `.dependencies.json` and leaves it untouched. Is that so?
