### ISSUE TITLE
Resolver API

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#216]
It would be nice to make the resolver available through:

``` javascript
var jspmResolver = require('jspm').resolver;
var projectResolver = new jspmResolver(__dirname);
projectResolver.resolve('module/name.css') // outputs "jspm_packages/npm/module@1.2.3/name.css"
```

Also it would be nice to ensure the resolver can be sync too.

**Comment by nkoterba** [comment]
So I'm trying to to use the JSPM API `locate` method to find a SCSS file.

Here is my current code:
```javascript
var jspm = require('jspm');

jspm.locate('ns-popover/sass/ns-popover.scss').then(function (result) {
	console.log(result);
});
```

Since I couldn't find much documentation on the API `locate` method, I have a few questions:

1) Running the command above, I get the following output:
```javascript
/Volumes/C/webapp/jspm_packages/github/nohros/nsPopover@0.6.7/sass/ns-popover.scss.js
```
That's great....except it's appending the **.js** extension at the end of my .scss file :-(

I've noticed I can apply the SystemJS *text* plugin to get it to return the correct result:
```javascript
var jspm = require('jspm');

jspm.locate('ns-popover/sass/ns-popover.scss!text').then(function (normalized) {
	console.log(normalized);
});
```

Output:
```javascript
/Volumes/C/webapp/jspm_packages/github/nohros/nsPopover@0.6.7/sass/ns-popover.scss
```

Is this expected API behavior to require a SystemJS plugin if not trying to lookup a javascript file?

2) The `locate` and `normalize` API methods all return promises...which is generally good except that I'm trying to get an array of paths and set it to a variable that I pass to a function that is **not** setup to handle promises/async.  Is there any way to achieve this with the current `locate/normalize` API?

**Comment by guybedford** [comment]
@nkoterba 

1.  the plugin system just runs normalize and locate before removing the .js extension manually. Unfortunately this is a quirk of the design, but will be changing. You may as well just remove this yourself.
2. The hooks are there to be used in the loader pipeline primarily. The async nature is just a consequence of that.
3. The nature of a browser loader is that it needs to know direct paths.
