### ISSUE TITLE
Unable to install react redux react-redux

### ISSUE THREAD

**Issue by JoaoMosmann** [jspm/jspm-cli#2173]
When I run the command `jspm install react redux react-redux`  **jspm** throws the following exception

```Installing npm:react-redux@4.4.6, no version match for npm:react@^15.4.0```

However, if I use **npm** in the same way, it works normally `npm install react redux react-redux`

**react-redux** has these dependencies
```"peerDependencies": {
    "react": "^0.14.0 || ^15.0.0-0 || ^15.4.0-0",
    "redux": "^2.0.0 || ^3.0.0"
  }
```

I`m not sure if this is an issue with **jspm**, and what is the cause.

**Comment by guybedford** [comment]
It's trying to install the `^15.4.0-0` range here and failing. You can override this in jspm 0.17 with:

```
jspm install react-redux -o peerDependencies.react=^15.4.0-rc.1
```

We should properly support `||` in conditionals, this is https://github.com/jspm/jspm-cli/issues/1253.

**Comment by JoaoMosmann** [comment]
It worked. Thanks!

**Comment by bdwain** [comment]
is there any workaround for jspm 16 @guybedford

**Comment by guybedford** [comment]
@bdwain the same approach will work in jspm 0.16 but with 0.16-style overrides: `jspm install react-redux -o "{peerDependencies:{react:'^15.4.0-rc.1'}}"`. Note both of these overrides can be checked into the jspm registry so that they always apply and other users don't get these problems in future either.

**Comment by bdwain** [comment]
thanks @guybedford
