### ISSUE TITLE
Help requested: `TypeError: global.XMLHttpRequest is not a constructor`

### ISSUE THREAD

**Issue by jochenvanwylick** [jspm/jspm-cli#2193]
Hi guys - great stuff this JSPM. I'm looking for some guidance to help me fix this issue I'm getting with my `documentdb` dependency. I know it's not a problem with JSPM but I'm looking for guidance to work around it. 

Reproduction steps:
- Given empty folder
- `npm init`
- `npm install documentdb --save`
- `@echo var ddb = require('documentdb'); > app.js`
- `node app.js` - observe that it works

- `jspm init`
- `jspm install npm:documentdb`
- `jspm run app.js` - observe that this works

OK - all is good - now I want to bundle this up:

- `jspm build app.js`
- `node build.js`
- observe error: `var xhr = new global.XMLHttpRequest(); TypeError: global.XMLHttpRequest is not a constructor`

So this error is actually in the `stream-http@2.5.0` package - file `lib/capability.js`. 

I'm looking for some guidance on how to solve this issue. I get it: XMLHttRequest is not available when the code is running in Node not in the browser. But, why is this happening now - and not when I'm running app.js directly? Do I have to install something like `https://github.com/driverdan/node-XMLHttpRequest` - to overcome this issue?
 
I looked into the jspm override config bits - where I can ignore files, but that's probably not what I need to do. So how can I deal with this type of problem?

**Comment by joeldenning** [comment]
@jochenvanwylick sorry for the slow response, and thanks for the detailed explanation.

To fix your woes, try adding the `--node` flag.
```bash
jspm build app.js --node
```

I just tried out all of your steps and this fixed it for me.

The broader context here is that `jspm build` [defaults to a browser build](https://github.com/jspm/jspm-cli/blob/0.17/cli.js#L118), whereas `jspm run` [is always a nodejs thing](https://github.com/jspm/jspm-cli/blob/0.17/cli.js#L59).

Last thing -- and this wasn't obvious to me at first when I started using jspm -- but running `jspm help` is actually the best thing you can do to learn things like this. The documentation for the jspm cli is not complete anywhere on github or in wikis, so it is recommended to run `jspm help` because that is the most up-to-date documentation.
