### ISSUE TITLE
Wrong "jspm install npm:debug"

### ISSUE THREAD

**Issue by PavelPZ** [jspm/jspm-cli#2204]
Please see https://github.com/visionmedia/debug/issues/394.

Is it JSPM or DEBUG NPM package issue? I am using JSPM 0.17.0-beta.32.

**Comment by aluanhaddad** [comment]
I believe this is happening because this commit https://github.com/visionmedia/debug/commit/f42b9627922995561299b064fce56bd292abb030, which moved `browser.js` into `src`, puts the package out of sync with the  [existing override in the jspm registry](https://github.com/jspm/registry/blob/f6176cd967550fd3a9a0965c7a7ebb40d849d844/package-overrides/npm/debug%402.2.0.json).

@guybedford is this a roughly correct interpretation? If so would it make sense to create a new override?

**Comment by aluanhaddad** [comment]
I've merged the override provided by @frankwallis.
