### ISSUE TITLE
Allow symlink linking when no endpoint build present

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#222]

**Comment by guybedford** [comment]
Note that because configuration in the package.json affects the loading of code, a change in configuration requires a relink operation, regardless of whether the endpoint itself does builds.

Given the above, it may be worth reconsidering this approach.

**Comment by guybedford** [comment]
For the above reason, relinking will always be necessary unfortunately.

**Comment by subesokun** [comment]
@guybedford Sorry for bringing this topic up again. As a brief refresher why this would be really helpful for our development:

After working now with linking for a while we've end up creating for every package a dedicated watch task that relinks the package in case of changes. While working on a given feature it can happen that you need to link in couple packages at a time which then causes already a significant CPU overhead due to the watch tasks. Also after rebooting your machine it's very tedious to start the watch tasks over and over for all those packages again. Ideally you just want to open your editor and start coding.


 > Note that because configuration in the package.json affects the loading of code, a change in configuration requires a relink operation, regardless of whether the endpoint itself does builds.

This is true but you'll have this problem also if you don't use symlinks. Triggering a `jspm link ...` in case the `package.json` has been modified it will have the same effect as directly symlinking it, the `config.js` of the app that consumes this linked package will be invalid and has to be updated by calling `jspm install --link ...`.

So either if the symlink exists or our watch task triggers automatically the `jspm link ...` command this makes no difference. In the app you'd have to relink that package anyhow.

Furthermore it happened really seldom to us that we needed to modify the package.json of a linked package. In most cases we just fixed bugs or added new features in the JS files so symlinking won't cause any conflicts.

I hope that I'm not missing an important point. But it would really ease our life a lot if symlinking would be possible. It's also ok for me if it's some none documented experimental feature that can be activated per package via a `jspm link --sym ...` flag or something like that.

**Comment by guybedford** [comment]
Sure, I see your point. The issue remains that we can't promise a use case when edge cases apply. Will reopen for consideration though. Note that you can always create a manual symlink.

**Comment by subesokun** [comment]
Great, thanks for reconsidering this issue :) I've tried to create already manual symlinks but this is a very tedious task again. Also if there are really changes on the package.json you've to first use the jspm linking mechanism to update your config.js and then replace the created link again against your own one. So it was a bit confusing to explain this to others.

I'm sure you know many edge case which I even can't think of but would be such `--sym` flag be an option for those who are really sure about what they're doing?

**Comment by joezimjs** [comment]
Why does npm link work with symlinks, but not jspm link? Is it just not handling the issues you mentioned or is it because of the way the dependency structure works?

**Comment by guybedford** [comment]
It's entirely an architectural limitation at the moment. But considering making it possible in future.

**Comment by guybedford** [comment]
This is entirely planned for the new linking workflows, and will happen naturally with the architectural shifts. As such it doesn't need a dedicated issue.
