### ISSUE TITLE
Nesting exports of multiple umd static bundles into a common global namespace

### ISSUE THREAD

**Issue by GBarthos** [jspm/jspm-cli#2254]
Hi, I'm working on a react project using jspm 0.17-beta.32 .

The application is composed of multiple packages (defined in jspm.config file).
I want each package to be bundled independently, as static umd builds, and to export its value inside a same global namespace.

I want to include every build in script tags inside my html and be able to access myGlobal global which will hold each exported values.

---

If I try to build a package by passing the option `--global-name myGlobal`, then the value of `myGlobal` is overwritten by each package.

If I try to build a package by passing the option `--global-name myGlobal.<name>`, then in the console an error says: `myGlobal is not defined`.

---

What should be the proper way to do this ?

See this issue [systemjs/builder/issues/772](https://github.com/systemjs/builder/issues/772) or this [stackoverflow question](http://stackoverflow.com/questions/42280474/how-to-export-different-bundles-inside-a-same-global-namespace) for more details.

**Comment by guybedford** [comment]
Perhaps use `--global-name myGlobal<Name>` here.

**Comment by amenadiel** [comment]
@guybedford I've noticed that the UMD build is different when every included module is defined in ES6 syntax (and appears in bright cyan in the console as tree shaken by rollup) than the case when some of the modules use AMD or CJS syntax (and therefore appear in a darker color in the console) 

Take, for example a module in the form

`module1.es6.js`
```js
export var module1 = 'I am module 1';
```
Performing

```sh
jspm build module1.es6.js module1.umd.js --global-name myNamespace --format umd
```

Would result in a file whose UMD definition is on top:

```js
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
	typeof define === 'function' && define.amd ? define(['exports'], factory) :
	(factory((global.myNamespace = global.myNamespace || {})));
}(this, (function (exports) { 
...
})));
```

Take instead a module in the form of

`module1.amd.js`
```js
define(function () {
	var module1 = 'I am module 1';
	return module1;
});
```

Performing

```sh
jspm build module1.amd.js module1.umd.js --global-name myNamespace --format umd
```
would result in an UMD module whose umd definition is at the bottom

```js
!function(e){function t(e){Object.defineProperty(... ) } ...)

(["a"], [], true, function($__System) {
    var require = this.require, exports = this.exports, module = this.module;
    $__System.registerDynamic('a', [], false, function ($__require, $__exports, $__module) {
        ...
    });
})
(function(factory) {
  if (typeof define == 'function' && define.amd)
    define([], factory);
  else if (typeof module == 'object' && module.exports && typeof require == 'function')
    module.exports = factory();
  else
    myNamespace = factory();
});
```

When using those builds via a script tag, the first one will set `myNamespace` as an object:

```js
console.log({ myNamespace: window.myNamespace });
Object {myNamespace: {module1: "I am module 1", __esModule: true}}
```

whereas the second one will set the value of global `myNamespace` as the return value of module1:
```js
console.log({ myNamespace: window.myNamespace });
Object {myNamespace: "I am module 1"}
```

So it becomes apparent that, for @GBarthos use case, the first workflow would allow to build several modules using the same `myNamespace` namespace. Each of the built modules, when loaded with a script tag, would use or declare `window.myNamespace` when doing

```js
(factory((global.myNamespace = global.myNamespace || {})));
```
And **extend** said object with their named export.

Whereas, in the second workflow, each of them would instead **reset** the value of `window.myNamespace` when doing:

```js
myNamespace = factory();
```

So, **TL/DR;** the global export you get from a UMD build varies with the input, which might be the expected functionality after all, since there's only so much the builder can guess from its side.

**Comment by guybedford** [comment]
@amenadiel the ability to create namespaces like this with the UMD pattern perhaps shouldn't have been added. This is the template at https://github.com/systemjs/builder/blob/master/templates/sfx-umd.js. I guess I was following a common UMD pattern which seemed sensible, but perhaps the better and more consistent intention would be an overwrite like the other forms.

That said, it could certainly be a useful trick for this use case to do UMD builds to get the namespace functionality.

**Comment by amenadiel** [comment]
It is a useful trick, but still kind of a side effect.

However, this means static umd builds behave differently depending if they are built using 100% rollup vs jspm v0.16 style build. Some of them will return namespaced modules, others the module itself, others the module under the default property.

Do you think there could be a way to delegate static builds 100% to rollup? I know it has plugins to deal with cjs and amd modules, but I doubt it has a way to diagnose what kind of module are you feeding it. Anyway, it would take a big share of load off systemjs builder, making it focus mainly in bundles.

**Comment by GBarthos** [comment]
+1 for the investigation @amenadiel !
Thank you guys for the comments, it's helping.

This confirms the feeling I had that it somewhat worked at the start of my project but quickly stop after adding some dependencies on 3rd-party libraries. Probably that those dependencies weren't es6 modules...

I think that a consistent approach would be better.  

I didn't find a robust nor satisfying solution up to now.  
I'll dig this question when I will have more time
