### ISSUE TITLE
Updating to jspm 0.17.0-beta.40 causes our test to run out of memory

### ISSUE THREAD

**Issue by speigg** [jspm/jspm-cli#2258]
I get the following out of memory error when I try to run tests via `jspm run test/runner.js` in  https://github.com/argonjs/argon/tree/develop after updating to jspm v0.17.0-beta.40 (was previously using 0.17.0-beta.32, which worked). 
```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort()```

**Comment by amenadiel** [comment]
I had a similar problem. It turns out that configuring

```js
 meta: {
        '*.json': {
            'loader': 'json'
        },
        '*.ts': {
            'loader': 'ts'
        }
    },
```

in your jspm.config.js root meta, is making system.js go into an endless loop, because it tries to load package.json files with json plugin, which in turn has its own json definition file.

My solution was to move that meta to be under each package meta. (just like you have your *.ts meta in src package)

**Comment by speigg** [comment]
@amenadiel interesting! 
@guybedford Is this an intentional (by design) breaking change? If so, feel free to close this issue. Thanks!

**Comment by perrin4869** [comment]
hm... The fix seems to have landed, but it didn't fix the issue for me...
