### ISSUE TITLE
JSPM does not convert overridden sub-dependency to ES6

### ISSUE THREAD

**Issue by CxRes** [jspm/jspm-cli#2315]
I have a internal library that uses [fs-extra](https://github.com/jprichardson/node-fs-extra) which is written in ES6 style cjs. I have temporarily used `jspm install npm:fs-extra -o "{format:'es6'}"` to install this. When I build the library here all the files are transpiled as expected and I have no problems. (All the fs-extra installed files contain the string `"format esm;"`; package.json also contains the relevant override `{"format":"es6"}` property associated with fs-extra). But wait...

Now when I install this library in a larger project (in an unbuilt form) and then build that larger project, these files are no longer transpiled.  Peer into `jspm_packages` here and there is no  `"format esm;"` string.

I even tried adding `"format esm;"` by hand, in which case jspm/systemjs is unable process the file,  complaining that it does not understand `modules` as in `modules.exports`.

**Comment by guybedford** [comment]
If this is your own package, then include `"format": "esm"` in the original package.json file. This way whoever installs it should get the correct configuration.

**Comment by CxRes** [comment]
A. Do you mean in fs-extra (which I don't own) or lib that includes fs-extra (which I own).

B. If latter - do you mean: (1)
```
"format":"esm"
```
or (2)
```
"jspm": {
  "format":"esm"
}
``` 
or (3)
```
"jspm": {
  "overrides": {
     "npm:fs-extra@2.1.2": {
       "format":"esm"
    }
  }
}
```

Also, quite confusingly, the wiki page on [Configuring Packages](https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm) says that _"Module format esm (ECMAScript Module) currently isn't used in package.json"_.

**Comment by CxRes** [comment]
None of the above (alone and in combination) seem to work!!!!!!!?????

**Comment by CxRes** [comment]
I am closing this because it has to do with lack of Transitive Overrides support #854. Please see my comment in #854.

One point is in order - that systemjs checks import and export statements to determine whether transpilation is needed is severely problematic. A lot of modules are now being written in es6 style cjs which are then not transpiled when using JSPM. This pretty much defeats the intended universality of JSPM/SystemJS.  :(

**Comment by aluanhaddad** [comment]
Can you clarify a little more about what you mean by ES6 style CJS? Looking over the source code of that package it uses `require` and `module.exports` which is common and well handled by JSPM and Systemjs. That implies `"format": "cjs"` which will be automatically deduced for an npm package without the need for any overrides. If you specify `"format": "esm"` and it will indeed fail to transpile correctly because the CommonJS wrapper function will not be generated.

I'm curious what the initial problem was. Format only affects the module definition constructs such as `import`, `export`, `System.register`, `define`, and `require`.
