### ISSUE TITLE
0.17 beta 42 breaks 'browser' field support

### ISSUE THREAD

**Issue by TobyEalden** [jspm/jspm-cli#2326]
It seems that release beta 42 has broken the support for the 'browser' package.json field.

Specifically, I use the npm shortid package which has been working well up to and including beta 41. After installing beta 42 I get an error:

```
Uncaught TypeError: Cannot convert object to primitive value
    at encode (encode.js:12)
    at build (build.js:39)
    at Object.generate [as shortId] (index.js:55)
```

Tracking it down it looks like the file substitution specified [here](https://github.com/dylang/shortid/blob/master/package.json#L32) isn't being applied...

**Comment by adelespinasse** [comment]
I have a similar error that started in beta 42, although I can't tell for sure if it's the same bug. The stack trace looks like this, on trying to load the app in a browser:

```
Uncaught (in promise) Error: Cannot convert object to primitive value
  Evaluating http://localhost:5000/jspm_packages/npm/core-js@2.4.1/modules/es6.promise.js
  Evaluating http://localhost:5000/jspm_packages/npm/core-js@2.4.1/shim.js
  Evaluating http://localhost:5000/jspm_packages/npm/babel-polyfill@6.23.0/lib/index.js
  Evaluating http://localhost:5000/src/main.js
  Loading src/main.js
    at Object.eval (es6.promise.js:245)
    at eval (es6.promise.js:300)
    at eval (es6.promise.js:301)
    at eval (<anonymous>)
    at Re (system.js:4)
    at system.js:4
    at S (system.js:4)
    at E (system.js:4)
    at k (system.js:4)
    at system.js:4
    at Object.eval (shim.js:108)
    at eval (shim.js:177)
    at eval (shim.js:178)
    at eval (<anonymous>)
    at Re (system.js:4)
    at system.js:4
```
I don't get any error if I bundle the app to a standalone executable with `jspm build`. I have no idea how to debug this any further.

**Comment by guybedford** [comment]
@TobyEalden thanks for posting. Which version of jspm did this last work with for you?

**Comment by guybedford** [comment]
@TobyEalden this is an interesting edge case, I think I have a SystemJS fix for this, but the workaround would be to edit `shortid@2.2.8.json` setting the map to:

```js
    "./lib/random/random-byte": {
      "default": "./lib/random/random-byte-browser.js"
    },
    "./lib/util/cluster-worker-id": {
      "browser": "./lib/util/cluster-worker-id-browser.js"
    }
```

(ie removing the js extensions in the map)

**Comment by TobyEalden** [comment]
It was working fine on beta 41.

I can confirm your workaround works for me, although there's a slight typo in your example ("default" vs "browser"):

```
  "browser": {
    "./lib/util/cluster-worker-id": {
      "default": "./lib/util/cluster-worker-id-browser.js"
    },
    "./lib/random/random-byte": {
      "default": "./lib/random/random-byte-browser.js"
    }
  },
```

**Comment by TobyEalden** [comment]
Actually I'm talking rubbish - must have cached an old version after updating to beta 42. Removing the js extensions from shortid@2.2.8.json doesn't seem to be working for me now.

**Comment by adelespinasse** [comment]
I have a bit more information about this (or about the error I get, which I think probably is the same bug @TobyEalden found, but I can't be sure).

I get an error (see my previous comment) when loading my app in Chrome. I can prevent the error by removing this line from my main.js:
```
import "babel-polyfill";
```
The app then works fine in modern browsers, but of course it doesn't work in IE11, because Symbol isn't defined.

There's no error when building a bundle with `jspm build` for distribution. So I could potentially work around the bug by removing the above line during development, and adding it back in when building for distribution.

This didn't happen in beta..41, but that version works poorly for me because of [this](https://github.com/systemjs/babel-plugin-transform-cjs-system-wrapper/issues/12). I'm actually still using beta.32 for most of my development because of that, but would very much like to use an up-to-date version.

**Comment by aluanhaddad** [comment]
@adelespinasse 
You could use a contextual map to avoid having to modify `main.js` before you bundle for deployment.
```js
SystemJS.config({
packages: {
    "app": {
      "main": "main.js",
      "format": "esm",
      "map": {
        "babel-polyfill": {
          "~production": "@empty"
        }
      }
    }
  }
})
```
If you use a bundling workflow, you can toggle it on by running
```bash
$ jspm bundle --watch --inject
```
instead of
```bash
$ jspm bundle --watch --inject --dev
```
If you are not using a bundling workflow you can add
```js
SystemJS.config({production: false});
```
somewhere.

That doesn't resolve the issue, but it might make your workflow a little smoother.

**Comment by TobyEalden** [comment]
My original issue is fixed in beta 44.

**Comment by adelespinasse** [comment]
I'm pretty sure my issue is fixed too.

**Comment by guybedford** [comment]
Thanks for the updates, closing, but if this happens again please let me know.
