### ISSUE TITLE
Expose `-wid` as API

### ISSUE THREAD

**Issue by ArmorDarks** [jspm/jspm-cli#2344]
As for now, it isn't available to call via API.

There was https://github.com/jspm/jspm-cli/issues/1702, but it was slightly about other issue and closed without finally exposing `-wid` to API.

**Comment by guybedford** [comment]
We need a clearer separation here definitely. I'm thinking it may be time to separate the build parts into their own separate CLI tool that can come with jspm and be used independently of jspm and apply to plain SystemJS. Something like `sjs build` or `sjs bundle`, API backed.

Because this is future work, I will likely do it, but it's not a task so much as a plan :)

**Comment by ArmorDarks** [comment]
Well, can't tell will it be good solution or no. I have some concerns, but my lack of JSPM internals prevents me from given them in meaningful form. So far it seems to me that watcher, builder and JSPM itself are too coherent together...

However, since it is only planned, maybe we can after all expose API of watcher, as for now? Or it is that problematic?

I understand that means that in future such API will be taken away, but since you're talking about radical changes in design and taking builder and all related to it from JSPM anyway, it won't hurt anyway, but right now we'd be able to invoke JSPM watch directly from Node env.

**Comment by guybedford** [comment]
@ArmorDarks there was also this project previously worked on in this space - https://github.com/jackfranklin/jspm-dev-builder. Perhaps that might help here?

**Comment by ArmorDarks** [comment]
@guybedford thanks for reply!

Isn't `dev-builder` is the thing, that is now built in into JSPM directly?
