### ISSUE TITLE
Explanation of custom JSPM Init workflow

### ISSUE THREAD

**Issue by xperiandri** [jspm/jspm-cli#2348]
Is there a documentation about custom JSPM Init workflow?
How to use config split into `browser`, `dev` and `node`?
What does `Use package.json configfiles.jspm:node?` mean?

**Comment by donaldev** [comment]
This may help you
 - https://jspm.io/0.17-beta-guide/creating-a-project.html#

**Comment by xperiandri** [comment]
@donaldev thanks, but actually not. As it only explains `quick` initialization.
I'm setting up an enterprise project so I need to know how can I use specified features.

**Comment by aluanhaddad** [comment]
The options include setting the application package module format to `esm | cjs | register | amd | etc.` You are also given options for splitting your configuration file with varying levels of granularly. For example, if you indicate that you want a separate `jspm.browser.js` config file (the CLI will ask you) then your bundles will get injected into this file run you run `$ jspm bundle --inject` which is great for diffs. Also you can create a `jspm.dev.js` file which will contain all config related to `devDependencies`. Mine includes mostly testing related stuff (`npm:tape`, `npm:blue-tape,` and some transpilers). You also have the option of creating a `jspm.node.js` file if you are using jspm to build server side applications.

**Comment by xperiandri** [comment]
So, `browser.js` is like `config.js`, `dev.js` is for test packages installation and `node.js` will be only used if I use Node.js, correct?

How will I include them then? Which do I need to link from HTML and when?

**Comment by amenadiel** [comment]
@xperiandri 
For example, the way I use `jspm.browser.js` (this depends on the way you are displaying your front-end content)

If you're using just plain HTML, then you could have an `index.html` and an `index-dev.html`. Both would be the same, but `index.html` will  have

```html
<script src="/jspm_packages/system.js"></script>
<script src="/jspm.browser.js"></script>
<script src="/jspm.config.js"></script>
```

whereas `index-dev.html` would have

```html
<script src="/jspm_packages/system.js"></script>
<script src="/jspm.config.js"></script>
```

If you're using any kind of template mechanism, then you can achieve the same with just one file using template conditionals. For example, using [handlebars](http://handlebarsjs.com/builtin_helpers.html):

```hbs
<script src="/jspm_packages/system.js"></script>
{{#if production_mode}}
<script src="/jspm.browser.js"></script>
{{/if}}
<script src="/jspm.config.js"></script>
```

or using [twig](https://twig.symfony.com/doc/2.x/tags/if.html).

```twig
<script src="/jspm_packages/system.js"></script>
{% if production_mode %}
<script src="/jspm.browser.js"></script>
{% endif %}
<script src="/jspm.config.js"></script>
```

however, in my workflow I always call both config files. I just run `jspm bundle` on the deploy stage, whereas during development, my  `jspm.browser.js` is practically empty

```js
SystemJS.config({
  baseURL: "/",
  paths: {
    "locale/": "assets/locale/",
    "styles/": "assets/css/",
    "github:": "jspm_packages/github/",
    "npm:": "jspm_packages/npm/",
  }
});
```

I don't use a separate `jspm.dev.js` but I guess it would be about the same. On production environment, you wouldn't need dev dependencies for example to load `.less` or  `.css` files, because they would be already bundled with `register` format. Therefore, using the same conditionals you could leave that config file aside safely.

Workflow to use SystemJS on node environment is different. I have never installed a dependency with `--node` mode.

**Comment by xperiandri** [comment]
@amenadiel, but there is no `jspm.config.js` created by 0.17 wizard, only `jspm.browser.js`, `jspm.dev.js` and `jspm.node.js`

**Comment by xperiandri** [comment]
> this depends on the way you are displaying your front-end content

Thanks for detailed explanation. I will use ASP.NET Core Razor Pages.

**Comment by xperiandri** [comment]
> however, in my workflow I always call both config files. I just run jspm bundle on the deploy stage, whereas during development, my jspm.browser.js is practically empty

So what will be the benefit of separating configs if `jspm bundle` is used for production?

**Comment by amenadiel** [comment]
> So what will be the benefit of separating configs if jspm bundle is used for production?

@xperiandri just unclutter the config file, which can get really hard to read if multipe dependencies and bundles are crammed in a single file.
