### ISSUE TITLE
EPERM : operation not permitted ... when installing @angular/core etc.

### ISSUE THREAD

**Issue by rahuldmistry** [jspm/jspm-cli#2414]
**JSPM Version:** `$ jspm --version`

**Transpiler Plugin(s):** babel / traceur / typescript / I do not use a transpiler

**Details:**
I have wasted 12 hours for this simple library install via jspm but jspm won't get permission for the folder that it itself creates.

Below is the sample copy paste from console:
cmdPrompt> jspm install npm:@angular/core@6.0.2
     Looking up npm:@angular/core
     Updating registry cache...
     Downloading npm:@angular/core@6.0.2
     Looking up npm:tslib
     Looking up npm:rxjs
     Looking up npm:zone.js
     Downloading npm:rxjs@6.3.2
ok   Installed npm:tslib@^1.9.0 (1.9.3)
ok   Installed npm:zone.js@~0.8.26 (0.8.26)
     Looking up github:jspm/nodelibs-fs
     Looking up github:jspm/nodelibs-crypto
     Looking up github:jspm/nodelibs-timers
     Looking up github:jspm/nodelibs-process
     Looking up github:jspm/nodelibs-events
     Downloading github:jspm/nodelibs-crypto@0.1.0

warn Error on build
     Error: EPERM: operation not permitted, open 'D:\pg\RDMAppData\.jspm\packages\npm\@angular\core@6.0.2\bundles\core-testing.umd.min.js'

err  Error building package npm:@angular/core.

warn Installation changes not saved.

cmdPrompt>

I've also tried changing the install directory via editing config.js to have the first environment variables as exports.HOME = process.env.MYAPPDATA which is now pointing to local D: drive's simple folder on windows.

However running "jspm install jquery" simple works with no permission errors.

Please suggest a solution to this.

**Comment by danielpcampagna** [comment]
I have the same issue. Did you find some final solution or workaround?

**Comment by guybedford** [comment]
I'm wondering if this may be due to the permissions in the actual tar archive being extracted here - https://github.com/jspm/npm/blob/master/lib/npm.js#L405. I see there are `gid`, `uid` and `umask` options for the Extract method (https://www.npmjs.com/package/tar#tarxoptions-filelist-callback-alias-tarextract), that might be able to correct such a permissions case.

Perhaps someone can stat the file and share the ownership / file mode so we can diagnose if that is the case?

Is so, a combination of the above mentioned options should be able to fix it.
