### ISSUE TITLE
jspm 0.16 depends on tar@1.0.3 which has a known security flaw

### ISSUE THREAD

**Issue by gavinaiken** [jspm/jspm-cli#2422]
**JSPM Version:** 0.16.53

**Transpiler Plugin(s):** babel

**Details:**
Latest `0.16.x` version of `jspm` (`0.16.53`) [depends on](https://github.com/jspm/jspm-cli/blob/0.16.53/package.json#L13) `0.26.x` version of `jspm-npm` which [depends on](https://github.com/jspm/npm/blob/0.26.13/package.json#L29) `tar` `1.x` which `npm audit` warns has a security flaw.
 
After https://github.com/jspm/npm/issues/114 `jspm-npm` was updated so the `0.30.x` series which `jspm` `0.17.x` [depends on](https://github.com/jspm/jspm-cli/blob/0.17.0-beta.49/package.json#L14) does not use `tar` directly at all: https://github.com/jspm/npm/blob/0.30.4/package.json

Is it possible for the `0.16` version to use `0.30` of `jspm-npm` in order to resolve the warning for that version, or did the api change and make that difficult?

**Comment by guybedford** [comment]
@gavinaiken sorry for the looong delay here. jspm 0.16 can't use the same jspm-npm as the 0.17.x versions due to the API being slightly different. If you want to provide PRs for any of these upgrades that would be super welcome and I would be glad to release those. Committing to maintaining all these upgrades indefinitely is not something I can personally commit to though as my current energies are going into 2.0.

**Comment by gavinaiken** [comment]
Sorry for slow reply. I was just going to take a look at trying to put a PR together today, but it seems you've already handled it with the release of 0.16.54 and the bump to the tar dependency. Thanks!
