### ISSUE TITLE
what's the best practice for referencing resource files

### ISSUE THREAD

**Issue by pigcan** [jspm/jspm-cli#2461]
It is a fresh idea that it is can help us to build a future without webpack just as `@pika/web` does. 

Flowing the guide I understood  your ideas and proposals. As a font-end solution, maybe the guide missed something.Yes they are resource files styles, images etc. As webpack treats all types of files as a module, we can easily import a non-JS file into our JS files. There seems to be no way out under this structure unless we introduce `loader` again.

I appreciate your hard work and this project inspires me a lot!

**Comment by guybedford** [comment]
Glad to hear you're finding the approaches interesting.

At the time Webpack and jspm 1 were created, we thought we were going to have loader hooks in the browser that would support the use cases of importing assets.

Instead, it looks like we will be getting support for specific web assets as their own web specs. Eg importing CSS files is a current spec. Importing JSON files is its own spec. And similarly for importing HTML and WASM.

Currently both JSON and WASM imports are moving very fast in their support and may even be supported in Node and browsers by the end of the year.

So we would definitely support these cases when that is clear.

For assets that don't have any spec proposal, the workflow that would be advised is instead a file load.

So eg:

```js
import fetch from 'universal-fetch';
fetch(new URL('./file.anytype', import.meta.url));
```

The build tooling would then detect the use of `import.meta.url` and see that it is referencing a real file, and copy that file to the build folder.

The action items there are thus - JSON imports (tracking issue - https://github.com/jspm/jspm-cli/issues/2443), WASM imports (just landing into Node.js master right now! https://github.com/jspm/jspm-cli/issues/2465), and asset emission from `import.meta.url` analysis (https://github.com/jspm/rollup-plugin-jspm/issues/6).

CSS imports and HTML imports are a little ways off though still due to their specs being very early.

Hope that gives some ideas, and do let me know what you are interested in further here.

**Comment by pigcan** [comment]
Thanks so much for your reply.

In my opinion 

```js
import fetch from 'universal-fetch';
fetch(new URL('./file.anytype', import.meta.url));
```

it is a little bit unfriendly to UX/DX. For the loading of other files, we all need to implement it ourselves. As you said CSS imports and HTML imports are a little ways off though still due to their specs being very early. 

At the same time, I feel that in the real cases we usually need to process this file (e.g. transform) instead of simply copying it.

So my proposal is  back the concept of `loader` but in different ways.

----- It is my raw idea. -----

I think we can make a step forward based on `fetch` to introduce a more high level API.

`development`:

So eg:

```js
import { use } from '@jspm/xxx';

import React from 'react';
import ReactDOM from 'react-dom';

use('style-loader!postcss-loader!./index.css');
use('file-loader!./index.png');

```

I think it is more friendly than before. And we could implement a plugin-in system to support this chain calls.


`production`:

'Cause we have rollup-plugin system, I think it is not a difficult issue to solve, even though I'm not familiar with rollup.

**Comment by pigcan** [comment]
Another interesting idea: https://github.com/lukejacksonn/csz

**Comment by pigcan** [comment]
@guybedford What's your opinion? Please let me if I'm wrong.

The reason I do this is because we currently have thousands of projects based on code organization similar to CRA. My idea is to try to get these projects to the new  architecture with the lowest cost. This will also be more conducive to the promotion of the solution.

**Comment by guybedford** [comment]
csz also looks good indeed.

As mentioned I do like to consider builds as two-phase for the caching and optimization benefits. See also https://github.com/jspm/jspm-cli/issues/2454#issuecomment-493656490.

Certainly you don't have to agree with me though, but if doing custom stuff don't expect it to work in a browser without a build step.
