### ISSUE TITLE
Support aliases that contain a version

### ISSUE THREAD

**Issue by Hypercubed** [jspm/jspm-cli#2479]
I have a need to support multiple top-level versions of the same module.  For example, suppose I want to be able to use both lit-element v1 and v2.  I would like to be able to alias each version to the major version like so:

```sh
jspm install lit-element@1=lit-element@1
jspm install lit-element@2=lit-element@2
```

Current an alias of that type is invalid.  I propose relaxing the alias naming in jspm.

I'm willing to submit a PR if this proposal has support.

**Comment by guybedford** [comment]
I think it might well be possible to relax the aliasing rules to allow this. There are a few places in the code where `@` disambiguation is important for versioning and determining scoped packages, but I think we should be able to separate that disambiguation handling for aliases.

Does it not work entirely because of this code path - https://github.com/jspm/jspm-cli/blob/master/src/cli.ts#L36?

One thing to test as well would be to manually modify the `jspm.json` file to use a `pkg@v` alias, and see if that is properly supported in jspm-resolve (https://github.com/jspm/jspm-resolve/).

Happy to work through this one, provided we don't hit any specific disambiguation blockers.

**Comment by guybedford** [comment]
I just tested adding this into the jspm.json file and it definitely works there fine so we can support this for sure.

**Comment by guybedford** [comment]
Fixed in https://github.com/jspm/jspm-cli/pull/2480.
