### ISSUE TITLE
Support full use in Node

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#248]
This is pending https://github.com/jspm/npm/issues/21 and https://github.com/jspm/nodelibs/issues/2.

**Comment by subesokun** [comment]
@guybedford Recently I came across [electron](https://github.com/atom/electron) (formerly atom-shell) which is a very interesting Node.js based environment that comes along with an integrated Chrome browser. Inside of this browser you've full access to the Node.js environment. This sounds very appealing for writing desktop applications just as the [Atom](https://atom.io) text editor. Now I was playing a bit around with the [quick start guide](https://github.com/atom/electron/blob/master/docs/tutorial/quick-start.md) and an application could look like the following:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Hello World!</title>
  </head>
  <body>
    <script>document.write(process.version)</script>
  </body>
</html>
```

but also that works out-of-the box:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Hello World!</title>
  </head>
  <body>
    <script>var fs = require('fs')</script>
  </body>
</html>
```

Now I was wondering if it would be possible to use jspm in this environment but as SystemJS will then process all `require` calls I'm wondering if this cause conflicts. Also I fear that I would loose the ability to use a package like `nodegit` as it requires a C compile step due to `libgit2`. Would it be possible to tell jspm to ignore the `require` calls so that they're getting process by Node.js instead of SystemJS?

Just asked out of curiosity.

**Comment by guybedford** [comment]
That looks interesting. SystemJS does store the environment require at `System._nodeRequire`, which would be possible to use here. Better though would be to install `fs` with jspm, which internally references that anyway for package consistency and code portability.

If there are any environment issues at all with SystemJS in this type of environment I'd be happy to look at them - we're aiming to make it run in as many environments as possible.

**Comment by subesokun** [comment]
I made some more tests and let the [Angular Material Start app](https://github.com/angular/material-start/tree/es6) (which interestingly uses jspm :) run within electron and it works as expected :+1:

Using `System._nodeRequire` sounds interesting. This way you could install packages whose child dependencies or itself depends on binaries via npm and then require them out of SystemJS. I'm wondering if the SystemJS loader could possible detect if a `require` call references a package installed in the node_modules folder and if that's the case use `System._nodeRequire` in order to load it. But this sounds a bit hacky. Would this trick with `System._nodeRequire` also work in case the Browser correctly implements system imports natively?

**Comment by guybedford** [comment]
It's best to avoid it if you can. `jspm install fs` with `import fs from 'fs'` will automatically use that require, but in a way that keeps your code portable. It will match the require you would have got globally, so should give the benefits you're after.

**Comment by subesokun** [comment]
Sure, I'd fallback only to `System._nodeRequire` in case it's really unavoidable. If I've something interesting to report I'll let you know :)

**Comment by BrandonSmith** [comment]
@subesokun Unless I'm missing something, accessing the electron API from renderer JS can only be accessed through `System._nodeRequire`, right?

**Comment by subesokun** [comment]
@BrandonSmith Sorry I didn't have had time recently to look deeper into this but you need `System._nodeRequire` only in case you're trying to import modules directly via node and not jspm. But node environment variables like `process.version` can be accessed directly from renderer JS but not sure if also the electron API will be accessible.

Without jspm, would you need to `require` some module in order to access the electron API from renderer JS?

**Comment by BrandonSmith** [comment]
Normally renderer JS (within the Chromium process) does `require('ipc')` etc. in order to access the electron API that is made available. As a result `System._nodeRequire` is necessary. I created a stub to keep it pretty:

    "use strict";
    
    let ipc = System._nodeRequire('ipc')
    let remote = System._nodeRequire('remote')
    let webFrame = System._nodeRequire('web-frame')
    
    let clipboard = System._nodeRequire('clipboard')
    let crashReporter = System._nodeRequire('crash-reporter')
    let nativeImage = System._nodeRequire('native-image')
    let electronScreen = System._nodeRequire('screen')
    let shell = System._nodeRequire('shell')
    
    export {
        ipc,
        remote,
        webFrame,
        clipboard,
        crashReporter,
        nativeImage,
        electronScreen,
        shell
    }

**Comment by subesokun** [comment]
Awesome! Thanks for sharing it :)

**Comment by gautamsi** [comment]
I am also stuck with this stub to use electron node packages, I have some other node package which I want to use in electron and have to make this stub. 
Is it possible to use config and map to tell systemjs load it using System._nodeRequire? this way I don't have to write individual shims.

my large lib has 750+ class objects being exported to consume with Typescript. it will be tedious to export them using stub file.

**Comment by gautamsi** [comment]
Any ways to use TypeScript type system when using _noderequire.  When I tried stub module, it did not use correct Type. it is only saying "any" as type of exported class.

**Comment by jaroslavrehorka** [comment]
+1 for electron support

**Comment by gautamsi** [comment]
update: This is how I fixed/shim this.

shim file.ts
````ts
declare var System;
export = System._nodeRequire('module name')
````
in config.js map
````js
"map": {
    "node module name": "module shim file - path relative to * in config.js>paths",
    "aurelia-bootstrapper": "npm:aurelia-bootstrapper@1.0.0-beta.1",
//..............................
},
````
use the modules as usual in ts file.
````ts
import {object} from 'module name';
````

**Comment by jaroslavrehorka** [comment]
Thanks! I've created a package https://github.com/jaroslavrehorka/electron-jspm
