### ISSUE TITLE
Twitter bootstrap without css

### ISSUE THREAD

**Issue by abasak** [jspm/jspm-cli#393]
Is it possible to use twitter bootstrap without the css file (or any other package containing css files) from the registry? The registry [entry](https://github.com/jspm/registry/blob/master/package-overrides/github/twbs/bootstrap%403.1.0.json) has the css file set as a dependency, but since I am using sass I don't need the css to be automatically injected. Is there any config option I am missing?

**Comment by abasak** [comment]
Forgot to mention that I have checked the `-o` switch but not sure if this is the right option since it does not persist the local override.

**Comment by guybedford** [comment]
How are you using the sass from bootstrap? To selectively include just the CSS you need, or are you modifying the bootstrap css?

**Comment by abasak** [comment]
For now I am just using bower to install bootstrap-sass. I know it's not ideal :)

**Comment by guybedford** [comment]
I'd be interested to know why you are using the sass version specifically - there are a few reasons, which would imply different workflows from a jspm perspective.

**Comment by abasak** [comment]
It's just a personal preference. Mostly because of the possibility of using mixins, variables, nesting etc which is not possible in plain css.

**Comment by capaj** [comment]
@abasak If you need just the bootstrap.js file, you can point to it directly, so instead of 
```
require('bootstrap');
```
You can do:
```
require('bootstrap/dist/js/bootstrap.js'); //haven't tested that path, just guessing
```

**Comment by abasak** [comment]
@capaj Is `require` supported out of the box? I am getting `ReferenceError: require is not defined` error.

Tried using `import 'bootstrap/js/bootstrap';` but still the css is injected into the document.

**Comment by guybedford** [comment]
@abasak I've created an issue at https://github.com/jspm/jspm-cli/issues/396 for how we might support this, but in the mean time the best option would be to use your own custom version of bootstrap. Sorry I can't be more help than that.

**Comment by capaj** [comment]
@abasak yeah, you're right, jspm currently adds:
```
"format global";
"deps jquery";
"deps ../css/bootstrap.css!";
"exports $";
```
To the top of bootstrap.js, so that is why my proposed solution did not help. You could just erase "deps ../css/bootstrap.css!"; by hand and that will help, but obviously it is just a crude hack.

**Comment by abasak** [comment]
@guybedford @capaj Appreciate the help. I'll probably stick to the regular bootstrap version until #396 is implemented. For me being able to use all the modern js features are more enjoyable than using sass :smiley: Thanks for this great tool.

**Comment by danharper** [comment]
For anyone finding this via search, I was having a similar problem with Ionic. This is how I worked around it:

* Add `separateCSS: true` to `config.js`
* Create a bundle just for Ionic, `jspm bundle ionic ionic.js`
* Include that pre-built JS file in the HTML first before `System.import()`

The bundler will bundle the JS and  CSS separately as `ionic.js` and `ionic.css`. Just don't use the CSS output and you're good.

**Comment by zeeshanjan82** [comment]
I am facing a similar issue and would really appreciate if you guys could assist. I am able to get the materialize css library imported inside my jspm project and can reference. However I would like to use the sass version of the library instead of the css version as I believe that gives more control to me. My question is how can I reference the sass version which is inside the jspm package into my application in the gulp file so that it gets converted into css and that is something which I can use.

**Comment by mvolkmann** [comment]
In my case I want the bootstrap css, but I don't seem to get it with just
import 'bootstrap';
Should that give me the css?

**Comment by guybedford** [comment]
The CSS can be included via `import "bootstrap/css/bootstrap.css!"` where the css plugin has been installed via `jspm install css`.

**Comment by RobinBuschmann** [comment]
@guybedford Is there a way to prevent jspm from adding the  `"deps ...css!";` dependencies of a library to the top of a file? Or is it possible to override this configuration through systemjs?

I have a similar problem with **ionic**. I want to use sass instead of css to customize the ionic styles. But systemjs adds the css styles of ionic from `"deps ../css/ionic.css!";` into the head tag and of course overrides all my customization.

I'm just wondering why this behavior is the default one. As long as I don't use the css plugin for jspm, I'll expect jspm to handle my js dependencies only. Of course ionic forces the css plugin to be installed. But I would like to manage my styles separately from jspm.

thanks in advance

**Comment by guybedford** [comment]
@RobinBuschmann the only way to avoid this is to use jspm 0.17.

**Comment by guybedford** [comment]
@RobinBuschmann alternatively you can use an override to remove the CSS dependency, by overriding the override.

**Comment by guybedford** [comment]
The exact override to do this would be something like:

```
jspm install ionic -o "{shim:{'js/ionic/angular': {deps:["./ionic","angular","angular-animate","angular-sanitize","angular-ui-router"]}}}"
```

**Comment by RobinBuschmann** [comment]
@guybedford that worked, thanks
