### ISSUE TITLE
add version check for jspm-cli

### ISSUE THREAD

**Issue by djindjic** [jspm/jspm-cli#407]
Does it make sense to add version checking when we run cli? For example I've just got this idea after running my outdated travis cli:
```bash
Outdated CLI version, run `gem install travis` or use --skip-version-check.
```

**Comment by bcjordan** [comment]
What would be the rule for considering a version "outdated"? Not latest stable?

**Comment by guybedford** [comment]
I guess we could just always show a message informing if a patch or minor update (or both) is available.

**Comment by jimthedev** [comment]
This would be really helpful as it allows for the ability to grep for the string before continuing. 

I think this brings up question of log levels and what is the expected behavior.  Some projects have opted to be verbose by default while others have implemented log levels. Is jspm verbose in the cli by default?

**Comment by guybedford** [comment]
@jimthedev I suppose we are verbose by default - we could add an option for a quieter mode. Created https://github.com/jspm/jspm-cli/issues/528.

**Comment by screendriver** [comment]
+1 for an `outdated` flag like `jspm outdated`

**Comment by elwynelwyn** [comment]
Also +1 for a `jspm outdated` style command.
Would love to see similar output to `npm outdated`, e.g.:

```
Package                Current   Wanted   Latest  Location
bluebird                2.9.25   2.9.25   2.10.2  bluebird
```

An optional format flag similar to `npm outdated --json` would be great also:
```
{
"bluebird": {
    "current": "2.9.25",
    "wanted": "2.9.25",
    "latest": "2.10.2",
    "location": "node_modules\\bluebird"
  }
}
```

**Comment by jackfranklin** [comment]
@guybedford how can I get a list of installed jspm packages and their versions? I'm trying to work on a small CLI tool to do this:

![screen shot 2015-11-27 at 13 51 25](https://cloud.githubusercontent.com/assets/193238/11442527/fcecb4e6-950d-11e5-9d1e-9aded5b88689.png)

However, rather than just parsing out the semver range from the jspm part of `package.json`, I'd much rather be able to get the explicit version that jspm has installed. How's best to do that?

**Comment by guybedford** [comment]
@jackfranklin `jspm inspect` gives versions. `jspm inspect npm:whatwg-fetch` gives the constraints of the given package name. Happy to consider adding additional flags / adjustments to that output.

**Comment by jackfranklin** [comment]
@guybedford can I get that info programatically? I'd like to do that rather than parse out the CLI result. I had a look through the code but it's quite tricky. It would be awesome if alongside `install.showVersions()` there was a `listVersions` fn that returned the same data in a JS array for things to use programatically.

**Comment by guybedford** [comment]
Certainly an API equivalent could be useful.

**Comment by jackfranklin** [comment]
@guybedford I'll see if I can get a PR in! ;)

**Comment by jackfranklin** [comment]
@guybedford took a stab in 1325

**Comment by guybedford** [comment]
Tracking in https://github.com/jspm/jspm-cli/issues/471.
