### ISSUE TITLE
npm package dependencies resolved from npm rather than jspm

### ISSUE THREAD

**Issue by theefer** [jspm/jspm-cli#411]
With the latest jspm (0.10.6), jspm dependencies of a package fetched from npm are resolved against the npm registry, not the jspm one.

For example:
```
$ jspm install npm:pandular
```

where pandular [has a `jspm.dependencies` on `angular`](https://github.com/guardian/pandular/blob/master/package.json#L19) installs `angular` from `npm:angular`, rather than from `github:angular/bower-angular` [as per the jspm registry](https://github.com/jspm/registry/blob/master/registry.json#L13).

This causes issues as the rest of our app, which depends on `pandular`, itself depends on `angular` but this time it is fetched from `github` as expected.

I would expect that dependencies should always be resolved against the jspm registry, especially if found under the `jspm` section of `package.json`?

**Comment by theefer** [comment]
I think this is a regression as we didn't have this issue previously (0.10.3).

**Comment by guybedford** [comment]
@theefer this is actually correct behaviour - by default the registry of an npm dependency is taken to be the npm registry. This bug shows now because previously the above wouldn't have detected those as dependencies at all since there is no `registry` property.

The fix here is to add `registry: 'jspm'` to the package.json.

**Comment by theefer** [comment]
That worked, thanks.
