### ISSUE TITLE
different module exporting for npm vs github instaled modules

### ISSUE THREAD

**Issue by djindjic** [jspm/jspm-cli#415]
I have lib with same version deployed on github and npm, but there is some difference in installed packages. My npm package is recognized as commonjs but github is es6 as it should be. Here is `forwardablejs@0.1.44.js` for npm:
```js
module.exports = require("npm:forwardablejs@0.1.44/lib/index");
```
and github:
```js
export * from "github:djindjic/forwardablejs@0.1.44/lib/index"; 
```

After changing my lib endoint to npm I had to change my import statements because npm commonjs like installed package cannot be imported as:
```js
import {Forwardable}     from 'forwardablejs';
```

Is it a bug?

**Comment by theefer** [comment]
I stumbled upon the same issue.

For es6 modules installed via the npm endpoint, you need to explicitly specify `"format": "es6"` in your `package.json` (either at the root or within the `"jspm"` section if you have one).

@guybedford Maybe there needs to be more docs or CLI warnings about this?

**Comment by theefer** [comment]
@guybedford Is there a particular reason why we couldn't or shouldn't dynamically detect the module format even when fetched via npm? Is it an antipattern to distribute ES6 code rather than CJS via npm? (I have read but personally don't really buy the argument that it's the author's responsibility to transpile to the various formats and only expose that to the public.)

**Comment by guybedford** [comment]
@theefer yes this is a docs issue - currently this is noted at https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#npm. We always treat npm code as CommonJS because we have to provide exactly the same interface to code on npm. For example, UMD patterns should detect as CommonJS.

Even when Node (eventually, one day) supports ES6 modules, it will do so with its own resolution algorithm, so we will need to still give ES6 modules special remapping treatment on npm.

**Comment by djindjic** [comment]
I have missed it in docs, thanks!
