### ISSUE TITLE
install package as link

### ISSUE THREAD

**Issue by Aaike** [jspm/jspm-cli#417]
Is there currently a way to install packages as symlinks ?
i do not mean linking a local directory and then installing that as a symlink.
i mean something like

    npm link package

which would create a symlink to the globally installed package.

I think in case of jspm this would work out very nicely as every package version is cached.
so creating symlinks to them wouldnt result in version conflicts as it would with npm.

It would just be nice to save some space if you have many projects going on.

**Comment by guybedford** [comment]
@Aaike `jspm install --link` creates a symlink to the global link cache. `jspm link` copies the contents to the global link cache for that version.

I'm not sure how that differs from what you are describing as I don't see how space is being wasted in the above?

**Comment by Aaike** [comment]
if i run the following command i won't work
    
    jspm install --link bootstrap

i get a TypeError: Cannot read property 'copy' of undefined

i can only install --link packages that have been created using jspm link.
but i want to install vendor packages as a symlink , or am i using an older version again ? i have 0.10.6 
now

**Comment by Aaike** [comment]
sry , it seems it works if i try other libraries

    jspm install --link npm:sugar

but for some reason bootstrap is failing , the same happens if i pass the full package name like : 

    jspm install --link github:twbs/bootstrap

i get the same error when trying to link to angular.
so it seems like it only works with some libraries for me

**Comment by guybedford** [comment]
@Aaike right, interesting I see what you mean. `link` is meant to mean just packages that are locally linked specifically, as these are separated from the normal global cache.

Installing symlinks to the global cache could be an option. Some http servers don't follow symlinks though, and users can want to run compile options like minify etc on jspm_packages. Also for debugging.

The benefits of having a copy outweigh the savings of duplication mostly - is space really an issue? I'm not sure what it is solving?

**Comment by Aaike** [comment]
most packages are really small , so copying them is not a problem.

it is just something i would like to do for some libraries , for example with github:components/jquery-ui
that is is actually pretty big because it contains all the themes as well.
there are other libraries too that have some size to them but i cannot think up anymore examples right now. Oh yeh maybe ace :)

so linking to those would be nice. and i always minify files into a temp directory , not straight back into the node packages.

anyway i am not planning on using the symlinks on a production environment , it is purely for local development of stuff.
i actually created a custom cli command that does exactly what i am saying. it works out nicely.
anyway was just a question/suggestion , i know it might now be really useful to everybody :)

**Comment by guybedford** [comment]
@Aaike ok sure that makes sense. I would rather not implement this in jspm, mainly because the global cache can be transformed by custom overrides which may incorrectly interfere with other installs. It opens up problems, so would rather not give users the option.

**Comment by Aaike** [comment]
i understand, thanks for the clarification !

**Comment by Aaike** [comment]
how about adding a user friendly error message though ?
if someone tries to link something that cannot be found in the link cache then it can say

This package has not been linked yet locally using jspm link
or something like that.

it would at least make someone understand faster that the --install option should only be used with locally linked packages.

**Comment by guybedford** [comment]
@Aaike yes that would be great - I've created an issue at https://github.com/jspm/jspm-cli/issues/425.

**Comment by geelen** [comment]
Hey, just want to get some clarification here — I thought the point of `npm link` was to enable local development, so you could work on multiple interrelated projects at once. In which case changes are reflected immediately across all linked projects. Making a local copy means you constantly have to re-link your changes.

In the end I just 

```sh
rm -rf ~/.jspm/linked/npm/DEP@x.x.x
ln -s ~/path/to/DEP ~/.jspm/linked/npm/DEP@x.x.x
```

(replaced the copy with a symlink to my source) and JSPM was fine with it. So that's ok for me for now, but it might be good to mirror NPM's behaviour by default? I could probably make the change and PR it if you think it's a good idea.

**Comment by Aaike** [comment]
I think the idea is a linking a packaged is essentially like publishing a package with a version, so the contents should only change on a per version basis. You should execute the link command again to bump a new version or update the contents of the current version.

I also think it is a good idea to have an option to allow the content inside ~/.jspm/linked to be symlinks straight to the original development directory instead of copies of it so you dont need to relink it everytime.
I also created manual symlinks just like you did.

I dont think there is currently an option to do that using the jspm-cli, although i am :+1: for it.

**Comment by guybedford** [comment]
We rerun link each time because of the fact that endpoints can apply arbitrary post-processing operations on packages, which we need to also apply to our local package when linking.

This allows the linking of npm packages locally through jspm for example, if they correspond to a name in the npm registry or have `registry: npm` set in their package.json, even though they are written natively as npm/Node modules.

Ideally we could have an exception for "jspm-native" packages where no build operations would need to happen so that we can just symlink the folder directly, but even then processing operations are needed for all of the following:

* applying shim configuration involves adding meta syntax to a file
* setting the module format involves adding meta syntax to all files not usually detected as that module format
* setting the main entry point
* changing `directories.lib` or `directories.dist`

As well as the above, the next version of SystemJS will also have even more use of meta syntax.

So as long as we're not using any meta configuration options like shim or format, we can get away with not needing to relink, but this is a very narrow scenario unfortunately.

So what I suggest is linking into a dev branch, and continuing to link over into that same branch name with a watcher for changes. If it's a candidate release, use an exact version name to test the version resolutions. But link is effectively still a _local publish_ operation which must be run.

**Comment by geelen** [comment]
Gotcha. Well I'm pretty happy with leaving it as-is & then replacing the
copy with a symlink manually for my own devving. :+1:

**Comment by guybedford** [comment]
Yes exactly - there is nothing wrong with custom symlinks in jspm_packages.
