### ISSUE TITLE
Don't modify package.json properties

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#428]
1. Retain properties if users want to use their own formatting.
2. Don't remove properties that match defaults if users want them in.

Contributions welcome.

**Comment by sochka** [comment]
+1

**Comment by subesokun** [comment]
When moving to version `0.15.0` the `devDependency` property is getting inserted when running `jspm install`. There was one more other issue I can't remember at the moment. I'll try figure it out again next week.

**Comment by guybedford** [comment]
Adding `devDependencies` is necssary for jspm to work.

**Comment by subesokun** [comment]
Right but I was wondering if it would make sense to fail the installation before manipulating the package.json and print an error like "Please run jspm install -f" to fix your package.json".

Also if you use an older version of jspm it will revert these changes again (e.g. another developer didn't update jspm yet). So it's a bit like a ping pong game. Well this can't be avoided by using the `-f` flag but maybe some useful informations could be given to the user so that he's aware what he's doing. In worst case he pushes this falsely modified package.json back into the repository.

**Comment by guybedford** [comment]
Because the package.json is in version control, the author should be able to revert this themselves.

If you want to avoid your developers falling into this though, then make sure jspm is always installed into a project as an npm devDependency to avoid it.

**Comment by subesokun** [comment]
Right that makes sense, sorry for causing confusion and thanks again for your quick reply :)

**Comment by guybedford** [comment]
Thanks @subesokun. I guess it would be possible to leave out the transpilers from `devDependencies` in the package.json if this is annoying.

**Comment by subesokun** [comment]
Actually it's nice to see which version range for traceur or babel gets used but is it safe to alter them and what will happen if the version definition in the `core.js` changes for them? This seems to be a bit more critical for traceur than for babel as for traceur a fixed version number gets used instead of a rang. In case they shouldn't get manually modified maybe hiding them as before might be less error prone.

**Comment by guybedford** [comment]
@subesokun I may be warming to removing them actually. The key point here is that one doesn't want to have to version the transpilers - there is only one ES. I've created https://github.com/jspm/jspm-cli/issues/637.

**Comment by zhhz** [comment]
We have the same issue, but this only happens on Mac, not on Windows machine.

**Comment by guybedford** [comment]
@zhhz what issue is that?

**Comment by zhhz** [comment]
@guybedford sorry for the confusing. My issue is the same as you described here. But the wierd thing is my colleague who is using a Windows machine, his package.json is not modified( at least when you do git status, it is not marked as changed)

**Comment by guybedford** [comment]
Fixed in jspm 0.17 beta.
