### ISSUE TITLE
Contributors guide

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#461]
A guide for contributors to include:

* how to clone and run the project in development
* how to run tests
* roadmap for the project
* link to issues where contributions are welcome
* contributors.md / list of contributors in readme.

Any other ideas on how to make the project more welcoming to contributions would be appreciated.

**Comment by SekibOmazic** [comment]
@guybedford Take angular.js for example. Nicely described, clear and easy to understand - even for not native speakers like me :-)

**Comment by subesokun** [comment]
I think it would help contributors to maintain a common coding style if a `.editorconfig` (http://editorconfig.org/) and a `.jshintrc` (http://jshint.com/) file gets added to the project. This way it's possible to get warnings immediately in the editor in case something is wrong with the coding style. This might also reduce unnecessary changes in a git commit due to inconsistent coding style (e.g. extra spaces at the end of a line)

**Comment by guybedford** [comment]
I've put a contributors guide together at - https://github.com/jspm/jspm-cli/wiki/Contributors-Guide. Feedback welcome.
