### ISSUE TITLE
`jspm link --watch`

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#481]
It would be nice to have a built-in watcher for linking that would relink on file changes.

**Comment by guybedford** [comment]
This should use https://github.com/facebook/watchman.

**Comment by chrismcv** [comment]
I think I've just encountered this - I was expecting `--link` to be "live."

Is there a reason `src -> .jspm` can't just be a symlink as well as `.jspm -> jpsm_packages/src`?

**Comment by guybedford** [comment]
I've just updated this information about linking in https://github.com/jspm/jspm-cli/wiki/Linking#1-use-jspm-link-to-add-a-package-to-the-global-link-cache

**Comment by chrismcv** [comment]
OK - thanks for that.... My plan had been to modularise quite heavily, and to have lots of link type modules making up a project. e.g. if my app has 10 functional areas, I'd have 10 modules + other modules for core-features like auth and infrastructure...  If each of these sub-modules is going to need a `watch` command run on them, that seems like it could be heavy. (I'm assuming your watcher runs on the originating folder, not the consuming.)

Don't suppose you can you recommend a way to not use `--link` based on following structure:
(Some of my modules I will need to pull out into other projects)
```
config.js
lib
   index.js
jspm_packages
modules
    moduleA
        config.js
        lib
           index.js
        jspm_packages
    moduleB
        config.js
        lib
           index.js
        jspm_packages

```

**Comment by meenie** [comment]
For anyone running into this now that wants to get around it, I've added a new task to my grunt config called `grunt-exec`.  This just lets you exec command line functions.  So I just do `jspm link <endpoint>:<repo-name>@<current-version> --force`

**Comment by djindjic** [comment]
I do it also with gulp exec, it relly meets my needs. I understand it as job of dev utils not part of jspm. Just my opinion.

**Comment by guybedford** [comment]
I tend to agree with @djindjic that this is out of the scope of jspm. A gulp-jspm task etc could take this role rather, will be interesting to see what jspm gulp support develops. Closing for now, but happy to discuss further.

**Comment by djindjic** [comment]
[This](https://github.com/djindjic/generator-jspm-lib/blob/702949c7b036ea4d9b671dfccabb9133835132d8/app/templates/gulpfile.js#L24) is template file in my jspm-lib yo generator. I'm doing this like that, but it was faster before a couple of months for me. I'm not sure is it just mine local problem, but after reinstating ubuntu 14.04 I'm still having some performance  issue with linking, it takes more then 10 seconds to refresh my original project which is linked to. I found as a more productive to use git submodules currently.

**Comment by guybedford** [comment]
The speed issue will be fixed by https://github.com/jspm/jspm-cli/issues/345.

**Comment by edrex** [comment]
for my own reference:

```
brew install watchman --HEAD
watchman watch .
watchman -- trigger . link 'lib/*' -- `which jspm` link -y
watchman trigger-del . link
watchman watch-del .
watchman shutdown-server
```

**Comment by skosno** [comment]
Is there any reason for not directly creating symlink to target location? I believe both bower and npm just create a symlink to directory that was registered as local linkable package (so after jspm link repo:something@version jspm just stores information where on drive this package is and under what name should it be registered) .Then whenever someone wants to use this linked package using e.g. "jspm install --link repo:something@version" it just links to the location previously stored. All the updates are automatically there, no need to relink or anything.

This issue makes iterative module development a real pain. I am actively developing applicaiton that is split into multiple repositories (with many "common" components developed as standalone repos) and this issue is a showstopper at the moment for migration to jspm. It adds a lot of overhead to constantly watch all linked repositories to update linked copy.

**Comment by meenie** [comment]
@skosno: I believe the issue is that JSPM needs to do some pre-processing of the assets before they get linked over.  So it can't just link directly to the directory.

**Comment by skosno** [comment]
@meenie the question is what pre-processing is really needed here that prevents us from linking. Those additional watchers really feel like overkill - we have additional watchers that will trigger after linked repositories update.
Just as a try went with simple direct symlink in jspm_packages/... and seemed to work fine but of course this was just for a try. Not sure what logic is out there but maybe it is possible to have just simple symlink mode unless developer know that re-linking need to be done (so that jspm can process things - probably e.g. when directories settings are changed etc.)

@guybedford I see that there is a topic for "new linking workflow" that seems to follow this direction - what I want to know is what can be done in the meantime. Is manual symlink basically enough (once you know stuff like directory setting etc?)

I seem to have hard time introducing jspm to our workflow (it is a big app with a lot of modules) and linking seems to be one of the major blockers for our team.

**Comment by meenie** [comment]
@skosno Thanks for looking into that.  I really have no other information to provide around this :-/.  I feel your pain around trying to introduce JSPM though!

**Comment by guybedford** [comment]
@skosno where manual symlinking works for you, that is certainly advisable. Build operations during link are only needed for npm packages and shims in the package.json.

**Comment by skosno** [comment]
@guybedford Could this be an option to add something like "-direct" flag when setting up a link:
```
jspm link github:my/repo@dev -direct
```
So in this case what it would do is just create a symlink from JSPM cache to the selected directory. In such case when you install this package, symlink is created to cache while cache points with symlink to local directory. In such case it is easy to switch between build/copy and "direct link".

What do you think about such option?

**Comment by guybedford** [comment]
@skosno at the moment it's suggested to do it manually - we are going to be providing full symlinks for jspm 0.17 - so I'm focusing on getting that out at the moment.
