### ISSUE TITLE
Support peerDependencies

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#490]
Frameworks would be the example here - `react`, `ember`, `aurelia` etc.

One strict definition of a peerDependency might be any dependency which uses a mutable factory pattern to store state that would need to be shared.

* When finding a peerDependency it immediately gets added as a primary install.
* The peerDependency is not listed within the map for the package it is a dependency of (unfortunately this will require some refactoring in the version resolution algorithm)
* When the name the peerDependency is installing is already a primary install, we immediately aim to consolidate between the two. If the installed package it is matched to satisfy both of eachother's ranges then its fine. If the range of one is invalidated, we will then provide a prompt to the user asking them to pick which range to use / break. Then we can also potentially show a warning everytime we re-check this during installs, but will allow operation to continue. This will assist with resolving cases where the same package might be used from two separate registries as well, as we can pick the range to break easily here.
* When a peerDependency resolves to a dependency (a unique `registry:package` combination) that is already installed to some version, we again seek to consolidate the other version to the same version as the peer dependency. Again, if a range is broken we prompt and warn, but allow operation. In this way, one package might depend on `jquery` by a custom install name like `jquery-custom: 'github:components/jquery'`, while another has it as a `peerDependency` on `github:components/jquery`, this will immediately turn the `github:components/jquery` dependency into a peer dependency for the whole project.
* We should allow peerDependencies in global map to resolve to local paths as well if the user wants a locally downloaded version instead as well.

A lot to take in, and it will be a moderately complex feature to integrate into the version resolution algorithms, which are already one of the the most complex parts of the project, but I think this could be very useful if done well.

**Comment by guybedford** [comment]
Here's a `peerDependencies` idea:

* When finding a `peerDependency` it immediately gets added as a primary install.
* If a primary install by that name exists, and doesn't resolve to the same range, we throw the entire install.
* If a primary install by that name exists, we intersect the resolution ranges, and update the primary install range to that.

**Comment by lookfirst** [comment]
I don't know if it is worth supporting peerDependencies, they seem to be on the the outs with npm.

That said, I do agree with your approach.

**Comment by ThomasBurleson** [comment]
@guybedford - :+1: for  **peerDependencies** support.
Consider [Angular Material](https://github.com/angular/bower-material/blob/master/package.json) where I want to enable the use to use:

```terminal
jspm install angular-material
```

Now my main entry point (index.js) uses this:

```js

// Should already be required, here for clarity
require('angular');

// Load Angular and dependent libs
require('angular-animate');
require('angular-aria');

// Now load Angular Material
require('./angular-material');

// Export namespace
module.exports = 'ngMaterial';
```

Ideally, the developer will not have to manually install all the peer libraries. So the above **single** command will install all the required libraries.

**Comment by EisenbergEffect** [comment]
:+1: We definitely could use this for Aurelia.

**Comment by guybedford** [comment]
Rather than throwing for version constraints that don't match up, we should simply warn. For example, https://github.com/pedronauck/react-simpletabs/blob/master/package.json#L48.

**Comment by stooboo** [comment]
When installing react-dnd 
I think this "err No version match found for npm:react@~0.14.0"
https://github.com/gaearon/react-dnd/issues/162 
probably relates to 
https://github.com/jspm/jspm-cli/issues/728

( I 'fixed' using an 'overrides' )

cheers

**Comment by guybedford** [comment]
I've updated the description of the feature above. It's describing the details from a version-resolution perspective, so may not be that clear, but please let me know if anyone has any questions or suggestions about this at all. //cc @EisenbergEffect

**Comment by EisenbergEffect** [comment]
It seems to make sense to me.

**Comment by u9520107** [comment]
@guybedford not sure if this is the place.. but recently i am finding dependencies defined like this:
Taken from reaction-motion's package.json
```
  "peerDependencies": {
    "react": ">=0.13.2 || ^0.14.0-beta1"
  },

```
Even though I've installed react 0.13.3, jspm would still fetch react 0.14.0-beta1 and let the lib use that instead of 0.13.3.
Is overriding the config the only way to solve this issue?

**Comment by guybedford** [comment]
@u9520107 yes these cases require an override currently, but will improve with peerDependency handling here.

**Comment by EisenbergEffect** [comment]
Ok, I've been thinking a bit about this. From Aurelia's perspective, we really have two use-cases:

1. We want people to be able to install `aurelia-framework` or `aurelia-bootstrapper` as a single line jspm install for our framework. Each of these have dependencies on a bunch of other modules though. Accessing those modules is usually necessary when doing development, but they are unaccessible due to the way that jspm writes out the map config.
2. We want people to be able to write plugins for Aurelia that are compatible with a certain version range of our framework. Installing the plugin should not affect the framework installation in any way. JSPM should just assert that the plugin is compatible with the current framework that the user has.

So, I'm not sure that peerDependencies as described above captures this exactly. Here's my own take on the way I would like to see things work:

1. JSPM currently keeps a flat directory structure when creating packages, however it creates a nested mapping structure. This seems inconsistent. I think that the default should be to write both a flat directory structure and a flat mapping structure (top level modules by default). The nested mappings should only be written out when there are multiple incompatible versions of a library in the same app. Usually, this type of conflict doesn't happen in most apps. At least, it's not desired in most apps, so most developers would rather resolve these conflicts at dev time. There is only a small set of apps that truly need multiple versions to co-exist. Making this change would certainly solve the issues that Aurelia has with installation and use. It would also make jspm work more similarly to other module loaders like require.js and I believe it would make the overall behavior less surprising for the developer. Indeed, it is very strange, and difficult to explain to someone, why they can't actually use a library they have installed, simply because it isn't mapped as a primary dependency...so they have to install the already installed library. I don't think that's intuitive and the feedback we have received from our community validates that perspective. (Also, making this change would reduce the size of config.js, which is important, and would dramatically reduce duplication in that file.)

2. With the above change, peerDependencies could be designed to work like NPM3..which is more or less what I describe above. Simply specifying a set of existing requirements that need to be validated when installing a plugin compatible with certain ranges of other libraries.

**Comment by guybedford** [comment]
@EisenbergEffect thanks for this feedback. Your use cases in (1) and (2) are exactly what the proposal above is designed to handle. That is, (1) peerDependencies install flat and are available globally, and (2) plugins would have a peerDependency range on the framework, which would need to have a solution just like NPM3 does as you say in suggestion (2). Note that I think that NPM3's workflow for peerDependencies isn't ideal - we would aim not to fail the install but allow immediate conflict resolution when peerDependencies ranges aren't being met, sort of like Bower does.

For your suggestion (1), this is a great suggestion, and I understand users may feel like they can't load their own dependencies. Effectively its an optimization to the config file format, where dependencies are pushed up to the global scope as much as possible.

My worry about this though is that it makes it possible for any package to import any other package, which may lead to users writing non-portable code because it is working for them locally.

These sorts of version conflict problems when they do happen can be very tricky to trace down. By stopping users from being able to require anything they haven't explicitly installed we ensure that they are writing code that is _publishable_ and _upgradable_. That is their package is guaranteed to work for others when they publish it, and when they run `jspm update` they can be sure they are getting the latest version of everything they explicitly require.

Perhaps we can tackle the config file size problem in other ways rather as well, including splitting it up into two config files, say a `jspm.manifest.js` and a `jspm.config.js`. If the problem is the size of config loaded in production, note that the redundancy we remove by _flattening_ the config file as you suggest wouldn't actually provide any file size gains over gzip as it already does redundancy removal.

So while tempting, I'm not completely sure it's worth giving up these properties for the gain being reducing the config file size, since peerDependencies already solves the global dependency problem, and there may be other ways to tackle these problems.

Either way peerDependencies seems needed though, so I'm happy to press ahead with that in the mean time. Most of the points at the top of this issue are handling the conflict resolution process, but I can assure you all the other properties you mention are included as well.

**Comment by EisenbergEffect** [comment]
Ok, sounds good :)

**Comment by unional** [comment]
I'm not very familiar to how peerDependencies work in NPM3 and will work in jspm.

I have a specific need (detail below), and wonder will peerDependencies the right way to solve it:

It is basically an abstract factory pattern, but on the module level.
I have a `ModuleX`, which depends on `Factory`.
`ApplicationA` install `ModuleX` and `FactoryA`, and map `FactoryA` to `Factory` in config.js:

```
map: {
   "Factory": "FactoryA",
   "FactoryA": "github://...."
}
```

`ApplicationB` install `ModuleX and `FactoryB`, and map `FactoryB` to `Factory` in config.js:

```
map: {
   "Factory": "FactoryB",
   "FactoryB": "github://..."
}
```

In order to support this, is it the right approach to set `Factory` as a peerDependencies in `ModuleX`?

or, if possible to being lazy, this:

```
map: {
   "Factory": "FactoryA",
   "FactoryA": "github://...." // FactoryA as peerDependencies
}
```
so I don't have to create the abstract `Factory`. :D

**Comment by guybedford** [comment]
Released in jspm 0.17 beta.

**Comment by guybedford** [comment]
@dteirney unfortunately not, the new focus is towards a 2.0.

**Comment by dteirney** [comment]
@guybedford OK, makes sense. Thanks. Is there a way to test out what's coming with 2.0? We tried moving to 0.17 beta but had a number of challenges with the bundling differences and some general areas of instability so we stuck with 0.16 with some local package override management (better the devil you know). Dynamic import is key to the apps we deliver and SystemJS and JSPM 0.16 is working so far for that but there are other solutions in the market now that we're looking to move to if we can't get any visibility into where JSPM is heading. Other solutions also support other key features, e.g. tree shaking of dependent libraries to reduce download size and associated CPU burn for eval.

**Comment by guybedford** [comment]
@dteirney the beta invites were just sent out. If you're still interested in testing the beta just let me know.
