### ISSUE TITLE
Allow commit SHAs

### ISSUE THREAD

**Issue by OliverJAsh** [jspm/jspm-cli#52]
I wish to access commits on GitHub, not just releases (tags).

Is this possible?

**Comment by polyclick** [comment]
I was in need of this today. This was my use case:

I was using the library `geelen/x-gif`, and installed it via jspm like this:
`jspm install github:geelen/x-gif`

Then I decided to fork `geelen/x-gif` into my own `polyclick/x-gif` for adding some extra features. But reinstalling my fork via `jspm` kept on installing the `geelen/x-gif repo`.

I then realised `jspm` was downloading the latest tag it found so, I then had to make my own custom tag for my latest commit and point to that:
`jspm install github:geelen/x-gif@tagname`

After doing this jspm installed my fork instead of the base.

Maybe something like @latest or @master would be awesome for easier forking.

**Comment by lookfirst** [comment]
It sounds like it was downloading what was in your config.js.

**Comment by polyclick** [comment]
It indeed was at first, that was my mistake. 
But the last few times I tried; I removed the line that was in the config.js file and installed the package via jspm cli:
`jspm install github:polyclick/x-gif`

It then kept installing the last (most recent?) tag it could find. 
Which I didn't really want.  I was hoping there was an easy way to tell jspm to install the last commit/head of my master branch.

**Comment by guybedford** [comment]
Branches are permitted so you can use `jspm install github:polyclick/x-gif@master` here.

**Comment by lookfirst** [comment]
:+1: @guybedford ! =)

**Comment by polyclick** [comment]
Tried with the branch name today, works great! Thanks!

`jspm install github:polyclick/x-gif@gh-pages`
