### ISSUE TITLE
config.js changes during build

### ISSUE THREAD

**Issue by joezimjs** [jspm/jspm-cli#537]
During the bundle-sfx operation, it makes updates to config.js, even though it isn't actually making any changes as far as I can see. This is an issue since I am watching my js directory where the file resides, and when a file changes, it runs the build process. This causes my watcher to continually fire every time the build is done and then have it build again in an infinite loop. Is there a way for to it not to make any writes to the config file if there are no changes to make?

**Comment by guybedford** [comment]
Sure, we could add a check to https://github.com/jspm/jspm-cli/blob/master/lib/config/loader.js#L349 and https://github.com/jspm/jspm-cli/blob/master/lib/config/package.js#L209 to see if the contents match, and if so then we don't need to actually do the save operation.

PRs welcome.

**Comment by jimthedev** [comment]
Would it be worthwhile just to remove the config.save from the sfxbundle promises chain? It looks like there is no code path that actually leads to the config needing to be saved in the case of sfx. It seems like when you call Config.write you want to mean it, whereas with sfx, we can probably safely assume that we never want to write the log because an sfx already has an output defined. We'd just do this:

https://github.com/jimthedev/jspm-cli/commit/aa07265d7e7c9596c85cdeeac04462a14a636749

Alternative are to include this behind a flag or to actually do checking as you suggested. Is there a case where bundling an sfx should actually change the config?

**Comment by guybedford** [comment]
Ah yes you're right - that would be the better fix!
