### ISSUE TITLE
jspm bundle still requires files of excluded modules

### ISSUE THREAD

**Issue by sochka** [jspm/jspm-cli#573]
Hi, I run the following command:
```
jspm bundle app-list - app-list/list
```
And receive this error:

```
     Building the bundle tree for app-list - app-list/list...

err  Error: Error loading "app-list/list" at file:/home/oleksandr/Projects/wdc/.tmp/public/app-list/list.js
     Error loading "app-list/list" from "app-list" at file:/home/oleksandr/Projects/wdc/.tmp/public/js/app-list.js
     ENOENT, open '/home/oleksandr/Projects/wdc/.tmp/public/app-list/list.js'
         at Error (native)

```
app-list is a "virtual" module, generated by back-end, so there is no physical file for it. Why would jspm try to load it?

**Comment by sochka** [comment]
Ok, solved this with


```
System.config({
  "meta": {
    "app-config": {
      "build": false
    },
    "author": {
      "build": false
    },
    "user": {
      "build": false
    },
    "app-list/list": {
      "build": false
    },
    "info": {
      "build": false
    }
  }
}
```

I found the relevant info here https://github.com/systemjs/builder - it might have some sense to duplicate some part of it in this repo.

**Comment by guybedford** [comment]
Glad you found a solution. The reason is that it has to trace the tree to remove the module and all its dependencies, as it doesn't just mean removing that one module I'm actually considering adding a syntax for this:

```
jspm bundle A - (B)
```

Where the brackets would indicate just the module B and not its dependencies as well. In this case we'd be able to avoid the need to process the module on the server entirely here.
