### ISSUE TITLE
Dealing with dynamic require()s?

### ISSUE THREAD

**Issue by lewisl9029** [jspm/jspm-cli#590]
I just tried loading the remoteStorage.js library from npm instead of github: https://www.npmjs.com/package/remotestoragejs

And got the following error:
```
error loading ./src/util.js:  TypeError: Module ./src/util.js not declared as a dependency.
```

This seems to be caused by the following code in node-main.js that tries to load each module dynamically from a filenames array:
https://github.com/remotestorage/remotestorage.js/blob/f41c71bdc0dca329ceb5fb75ada3336310860485/node-main.js#L9-L38

Is it even possible to support this kind of dynamic usage of require() through jspm? 

If not, any ideas on how I should best work around it? At the moment I'm overriding the library to change main to the pre-built version under /release/version/, but it seems a bit clunky to have an override that's version specific.

**Comment by guybedford** [comment]
Yes this isn't possible as requires need to be statically analyzable in order to load dependencies asynchronously before execution.

That said, it is possible to use meta syntax to declare additional dependencies:

```javascript
"deps a";
"deps b";
var files = ['a', 'b'];
files.forEach(require);
```

The `"deps"` syntax is picked up by the static analysis process and those dependencies are then loaded before execution so that they are properly declared.

Let me know if something along those lines helps.

**Comment by guybedford** [comment]
Closing for now, but do please let me know if the above suggestion is not working for you.

**Comment by glen-84** [comment]
@guybedford,

If you need to do dynamic loading, like:

```js
const mod = require(`./mods/${name}`);
```

Would you use `System.import(...)` (browser & node), or is there another solution?

**Comment by guybedford** [comment]
Yes System.import is the right approach here.
