### ISSUE TITLE
Hide devDependencies on Traceur and Babel from package.json

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#637]
And rather have these part of an internal implementation.

**Comment by Zoltu** [comment]
This was closed but in the latest version of JSPM (0.15.4) the behavior remains.  When I do `jspm install --yes` on a clean checkout of my repository, the following is added to my `package.json`:
```
{
	"jspm": {
		"devDependencies": {
			"traceur": "github:jmcriffey/bower-traceur@0.0.88",
			"traceur-runtime": "github:jmcriffey/bower-traceur-runtime@0.0.88"
		}
	}
}
```

I am confused why, if JSPM can figure out that they are necessary, it is putting them into package.json.  In general, I only commit code to my repo that cannot be derived from other information.  This can be derived from other information (not sure what) since `jspm install` adds it, so it should not be committed to my repository.

Right now I am just manually reverting the change every time it happens which is quite a nuisance.

**Comment by guybedford** [comment]
It might be worth reconsidering this again.

**Comment by guybedford** [comment]
Explicit is good!
