### ISSUE TITLE
bundle workflow

### ISSUE THREAD

**Issue by 2fd** [jspm/jspm-cli#639]
think it would be good to add functionality to the bundle command to have a more fluid work with them

```bash
jspm bundle moduleA + module/b [outfile] [--minify] [--no-mangle] [--inject] [--skip-source-maps]
```

### Compile
```bash
jspm bundle [--options]
```
this command it should read the system config and generate the bundles
* would be easier to manage the content of bandles
* divide the work when working in teams

### Arithmetic addition

```bash
jspm bundle + module/b [outfile]
```
if the first module is a plus should add the following modules to existing bundle

### flags negation
```bash
jspm bundle moduleA + module/b [outfile] [--no-mangle|--no-minify] [--no-inject] [--skip-source-maps]
```
*this is more a personal opinion,*
would be good to support a workflow with bundles and from this point, the injection and minification should be enabled by default

what do you think?

**Comment by guybedford** [comment]
For advanced / shared optimizations the recommended approach is:

build.js
```javascript
var builder = new require('jspm').Builder();
builder.bundle('some/module', 'build.js', {options}).then(function() {
  console.log('done');
});
```

I'd rather use the above than storing bundle configuration inside config.js or the package.json.

As for the options, the above also gives flexibility here.

The CLI bundling is more of a convenience to the above (think of it like a repl?).

**Comment by capaj** [comment]
@guybedford :+1: nice example

**Comment by capaj** [comment]
@2fd I love the idea of `jspm bundle [--options]` command. 
Because the problem I am trying to solve, is that with aurelia, the app doesn't really have a 'main' file.
So when bundling, I don't have anything to point to. I need it to go trough whole top level of config.js map and bundle every single top level package. I could create a simple NPM package to do that, but I think this should be in the core, not just userland.

Please @guybedford, do you think it could go into the core? I can prepare a PR in 48 hours or so...

**Comment by guybedford** [comment]
@capaj there is wildcard bundling for this - `jspm bundle app/*` or `jspm bundle app/**/*` for example.

**Comment by capaj** [comment]
@guybedford that won't help at all, because I need to bundle jspm dependencies. And I can't just run `jspm bundle jspm_packages/*`, builder breaks on the first package if I do.

Having it parse config.js would basically solve Aurelia's bundling problem. If you're not convinced, I will gladly make it an NPM module, no problem there.

**Comment by guybedford** [comment]
@2fd sorry for the delay on this, to go over the points above in more detail here:

**Compile**
It sounds like this feature is for argumentless `jspm bundle` to bundle everything in the config.js / package.json that was installed, just like @capaj is asking? If so, it's worth refining the proposal. Perhaps also having a special symbol `jspm bundle $` where "$" refers to all modules installed.

**Arithmetic addition**
This sounds like you want the ability to reference a bundle itself when bundling? Does that sound right?

**Flags negation**
Injection is a convenience and not really a recommended workflow which is why it isn't on by default (including the script tag on the server is the recommended workflow, with injection only used for bundles loaded dynamically after the initial page load).

Minification is disabled by default to ensure that bundling without any options happens the quickest.

Further feedback on the above welcome, and thanks for the suggestions.
