### ISSUE TITLE
`jspm install` adds all my npm dependencies as jspm dependencies

### ISSUE THREAD

**Issue by metamatt** [jspm/jspm-cli#683]
If I start with a package.json file I've been using with `npm` and not `jspm`, and start using `jspm`, the first `jspm install` command tends to duplicate the entire toplevel dependencies (for my backend) into the jspm dependencies.

Example:

1. initialize npm with brand new package.json file:

```
% npm init
[ accept all defaults ]
% cat package.json
{
  "name": "demo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

2. install jspm (so we can use it, and also so there's something in package.dependencies):

```
% npm install --save jspm
% cat package.json
{
  "name": "demo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "jspm": "^0.15.3"
  }
}
```

3. initialize jspm:

```
% ./node_modules/.bin/jspm init
[ accept all defaults ]
% cat package.json
{
  "name": "demo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "jspm": "^0.15.3"
  },
  "jspm": {
    "directories": {},
    "devDependencies": {
      "traceur": "github:jmcriffey/bower-traceur@0.0.87",
      "traceur-runtime": "github:jmcriffey/bower-traceur-runtime@0.0.87"
    }
  }
}
```

4. install something with jspm:

```
% ./node_modules/.bin/jspm install text
% cat package.json
{
  "name": "demo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "jspm": "^0.15.3"
  },
  "jspm": {
    "directories": {},
    "dependencies": {
      "jspm": "jspm:jspm@^0.15.3",
      "text": "github:systemjs/plugin-text@^0.0.2"
    },
    "devDependencies": {
      "traceur": "github:jmcriffey/bower-traceur@0.0.87",
      "traceur-runtime": "github:jmcriffey/bower-traceur-runtime@0.0.87"
    }
  }
}
```

Note in step 4, "jspm" is listed in package.jspm.dependencies, because it was in package.dependencies.

(This is a lot worse if the package.json had a lot of existing npm dependencies, not in this toy example.)

This doesn't happen once package.jspm.dependencies exists. That is, in my real use, the first `jspm install` command spams all the npm dependencies into the jspm section, but if I remove them manually, they don't come back.

However, a better way is to create `package.jspm.dependencies={}` before the first `jspm install` command. Maybe `jspm init` should do that? Or maybe it shouldn't treat "no jspm.dependencies" to mean "populate it by hoisting all the npm dependencies in".

**Comment by metamatt** [comment]
(You get 4 step 1's because Markdown. They're actually 1., 2., 3., 4., in the markdown source!)

**Comment by aams** [comment]
@metamatt use --save-dev rather than --save for jspm.

I usually split my apps into separate client and server directories, each with a package.json. That way, server side modules do not complicate the jspm space.

**Comment by clintwood** [comment]
I'm experiencing same as OP.  I.e. all top level `{dependencies: {<from here>}}` from existing `package.json` get copied into `{jspm: {dependencies: {<to here>}}}`.

My workaround is to not merge with existing `package.json` packages but create a `jspm` specific `package.json`.

**Comment by guybedford** [comment]
Sure this makes complete sense.

I've added an adjustment to ignore existing dependencies on init when not already a jspm package.json.

Will post out a patch soon.

**Comment by metamatt** [comment]
@aams:

> use --save-dev rather than --save for jspm.

Sure, that's the right way to install jspm in a real project. The example above is intended as a minimal example of the bug I'm trying to report. If you want an example that's closer to real-world use that models the bug,

```
% npm init
% npm install --save express
% npm install --save-dev jspm
% jspm init
% jspm install text
```

will get you there, and you'll find express in jspm's dependencies.

> I usually split my apps into separate client and server directories, each with a package.json. That way, server side modules do not complicate the jspm space.

Yes, that would avoid this bug. But it's not the only way people organize their projects, or the only way we're allowed to use jspm.

**Comment by richardharrington** [comment]
Hello @guybedford, thank you for creating this tool. I just started using it last week, and it's really amazing.

I'm still having the exact issue described in the first post above. Not sure what the issue-tracking etiquette is, so I'm attaching a comment to this closed one.

In my case, it's actually throwing an error when trying to pull in the npm dependencies, because the version names are in npm format -- no registry names or package names, just version numbers.

Here's (the relevant parts of) my package.json file (this is after I've run both `npm init` and `jspm init`:

```JSON
{
  "devDependencies": {
    "jspm": "~0.15.7"
  },
  "jspm": {
    "devDependencies": {
      "babel": "npm:babel-core@^5.1.13",
      "babel-runtime": "npm:babel-runtime@^5.1.13",
      "core-js": "npm:core-js@^0.9.4"
    }
  },
  "dependencies": {
    "express": "~4.12.4",
    "body-parser": "~1.12.4"
  }
}
```
Then I run `jspm install npm:lodash` and I get the following error:
```
err  TypeError: Install of express to ~4.12.4 has no registry property provided.
         at /Users/richardharrington/dev/movie-info-app/jspm_and_es6/node_modules/jspm/lib/package.js:280:13
```
from this section of the code (lib/package.js):
```JavaScript
if (dep.indexOf(':') !== -1)
  outPackage = dep;

else if (!registry)
  throw new TypeError('Install of %' + p + '% to `' + dep + '` has no registry property provided.');
```
It appears that when it's pulling in the npm packages and finding them not to be in the format it expects (for instance, no colon), it's throwing an error.

I think this error is probably a side issue, helpful only in diagnosing the real problem, which is that it's still trying to pull in the npm packages when you install any new jspm packages. I notice from one of the comments above that a change was made to ignore existing npm packages when running `jspm init` -- I assume that's [dba4c47](https://github.com/jspm/jspm-cli/commit/dba4c47e13a788dfb090f8441eb2287ae667beab) -- but that fix doesn't address the issue of projects that already have jspm. In fact, in the relevant section of code (lib/config/package.js):

```JavaScript
// not already jspm-configured
if (!_pjson.jspm && !_pjson.registry) {
  prompts = true;
  // dont read dependencies or devDependencies in this case
  delete pjson.dependencies;
  delete pjson.devDependencies;
  // if dependencies already existing, override with empty dependencies
  if (self.originalPjson.dependencies)
    pjson.dependencies = {};
  if (self.originalPjson.devDependencies)
    pjson.devDependencies = {};
}
```
I took the the fix -- the `if dependencies already existing` comment and the four lines after it -- out of the main `if` block to make them run whether or not we're running `jspm init`, and it installed my new jspm package just fine. But there's a whole lot going on here that I don't understand. I'd be happy to take a closer look at the code and make a pull request, but I don't yet get what the expected behavior is supposed to be. Is there any circumstance under which we *would* want to copy the top-level npm dependencies into jspm?

**Comment by guybedford** [comment]
@richardharrington glad to hear you're enjoying the project. It seems this is an edge case behaviour of the adjustment.

Basically you want your package.json to look like

```json
{
  "devDependencies": {
    "jspm": "~0.15.7"
  },
  "jspm": {
    "dependencies": {},
    "devDependencies": {
      "babel": "npm:babel-core@^5.1.13",
      "babel-runtime": "npm:babel-runtime@^5.1.13",
      "core-js": "npm:core-js@^0.9.4"
    }
  },
  "dependencies": {
    "express": "~4.12.4",
    "body-parser": "~1.12.4"
  }
}
```

As the `jspm` part is an override of the base package.json.

I've added a fix in https://github.com/jspm/jspm-cli/commit/95c2472b64546c518aa26d92816e155dae8fbfc1 which should catch this case in future.

**Comment by f15gdsy** [comment]
@guybedford, so in this case, if I want to use es6 syntax in the backend side, how do I refer use babel to compile it? I don't want to install another babel using npm again as jspm already has it.

**Comment by guybedford** [comment]
@f15gdsy it is advisable to install Babel twice to do precompilation until we can provide that workflow.
