### ISSUE TITLE
err  Repo github:rase-/node-XMLHttpRequest@add/ssl-support not found!

### ISSUE THREAD

**Issue by djupudga** [jspm/jspm-cli#685]
Trying to install socket.io-client and I am getting this error. From what I can see, there is a branch called add/ssl-support for node-XMLHttpRequest. Any ideas how to get around this problem?

just doing:
> jspm install npm:socket.io-client --save

**Comment by guybedford** [comment]
This is fixed in jspm master with https://github.com/jspm/jspm-cli/commit/1d6ac38afef88cad65107928a90a54370951f3be.

I'll aim to post the patch out soon.

**Comment by djupudga** [comment]
Thanks.

**Comment by OliverJAsh** [comment]
:+1:

**Comment by tauren** [comment]
Is this actually fixed? I've tried using the latest release version of jspm (`0.15.6`) as well as installing directly from master (`npm install git+https://github.com/jspm/jspm-cli.git -g`). But both ways I get this error when installing `socket.io-client`:

```
err  Dependency https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz not supported by jspm
```

**Comment by guybedford** [comment]
@tauren thanks for following up - there was a minor issue there I've fixed in https://github.com/jspm/npm/commit/ccfa2b75206d3c55bd25d3ee0d7110610b4ecd73, will release shortly.

With that fix though, it will then give an error that it can't find `github:rase-/node-XMLHttpRequest@a6b6f2` since we don't support commit reference installs. @capaj may be able to clarify here. It may be necessary to add an override that replaces this dependency with the version on GitHub.
