### ISSUE TITLE
Auto configure registries

### ISSUE THREAD

**Issue by OliverJAsh** [jspm/jspm-cli#687]
We are using the [`jspm-bower-endpoint`](https://github.com/2fd/jspm-bower-endpoint) in our project. After checking out the project and running `jspm install`, developers must run `jspm registry create bower jspm-bower-endpoint`.

Is there no way to have registries automatically configure themselves? Ideally, `jspm install` would suffice.

**Comment by guybedford** [comment]
Something like this can be handled via a local jspm config, which is being tracked in https://github.com/jspm/jspm-cli/issues/190.

Out of interest - what was the primary motivation for using jspm-bower-endpoint over GitHub?

**Comment by OliverJAsh** [comment]
The Bower plugin can read and use the `main` property from the Bower
manifest.

**Comment by guybedford** [comment]
@OliverJAsh thanks, we did add this functionality into the GitHub endpoint in https://github.com/jspm/github/blob/master/github.js#L639. If there are other Bower features that are necessary for the GitHub endpoint I'm happy to consider them.

**Comment by brianfeister** [comment]
@guybedford Problem on my end is that we are hitting alot of rate limits going through github with our continuous integration, piggy backing on bower would help address this issue.

**Comment by guybedford** [comment]
@brianfeister have you tried following the steps in https://github.com/jspm/jspm-cli/wiki/Registries#auto-configuring-registries?

Relying on the Bower servers to be working as well as GitHub and whatever custom archives are being referenced, is less reliable than just relying on the GitHub registry itself.

**Comment by brianfeister** [comment]
Thanks for that @guybedford, unfortunately we've already set that up and we are still hitting rate limits because our team size (about 12 people).  So when we all provision our Vagrant VM's we smash that rate limit at the same time and end up hitting the ceiling.  Is there a way to make that permanent auth token have a truly unlimited download rate ceiling?  The token is shared inside of Vagrant inside of Docker and all of it's provision stuff is pertinent to both our continuous integration and our local Vagrant VM's.

**Comment by guybedford** [comment]
@brianfeister do you know which rate limit you're hitting? If you're able to share the message that would help a lot to know. If it's the one I suspect it is, there is a minor rearchitecting that could help avoid this.

**Comment by brianfeister** [comment]
@jordanambra can you chime in here? Jordan is our dev ops guy - I've been working with him to configure jspm to use npm or the [jspm-bower-endpoint](https://github.com/2fd/jspm-bower-endpoint) project to bypass the github lookups and either go to npm or sort of faux-proxy through that extension.

**Comment by guybedford** [comment]
Any further update here?

**Comment by brianfeister** [comment]
Inside of Vagrant, I am running: `jspm config endpoints.github.auth c2NhbGFjaTpjMmYzMDU5MTA4Y2EyNmU3OWQzNjU1ZmQzNjcxOGFkNjg4ZTlhMDlk && jspm install`

```
==> default: 
==> default:      GitHub rate limit reached. To increase the limit use GitHub authentication.
==> default:      Run jspm registry config github to set this up.
==> default: 
```

Isn't the whole point of `jspm config endpoints.github.auth` to bypass this?

I'm wondering if the CLI changed and we are no longer actually using it properly. Thoughts?

**Comment by guybedford** [comment]
@brianfeister yes the API changed here in 0.15 - this is now `jspm config registries.github.auth`. If you were authenticated and hitting the ratelimit, the error message explicitly says that the rate limit has been hit despite authentication being enabled.

**Comment by brianfeister** [comment]
Thanks for that!  Sorry for the false alarm, all seems to be well now.  Do you know of those auth tokens have an upper limit? In our case it was user error, but curious what you had in mind about potential issue and possible fix.

**Comment by trusktr** [comment]
I'm getting

```js
warn Error on download for github:MikeMcl/bignumber.js
     Error: GitHub rate limit reached.

err  Error downloading github:MikeMcl/bignumber.js.
```

which doesn't even show a hint about what to do about it.

@guybedford When will this abomination be fixed? Do you even care about the *very poor* user experience that this causes? Here's [proof of the poor user experience](https://www.google.com/search?q=jspm%20github%20rate%20limit%20reached), right on Google. Is it your goal to have less users than you could have? Do you think everyone wants to create a GitHub account just so they can use a tool like JSPM? No!

It's been over a year since we've been having this problem (yes, it is a problem, not a feature).

I know as well as you do that you don't need to use api.github.com by default, so that we can avoid this problem altogether, and that you can simply just clone a repo or grab releases from the regular HTTP endpoint (f.e. with URLs like "https://github.com/infamous/motor/archive/v0.0.2.zip") instead of fetching release archives through the API (which hardly anyone uses anyways!!!). I know there's no rate limit because I can run `wget` in a while loop and download the release from https://github.com/infamous/motor/archive/v0.0.2.zip over and over and over with no problems. Every once in a blue moon I'll get `ERROR 429: Too Many Requests.`, but at least it won't be blocked like with GitHub API rate limits.

The most disappointing feeling when trying to work on something is when using a tool (like JSPM) that seems really awesome (because it is in many respects), then encountering such a crap error. I'm sorry, but this is a horrible design *bug* that you've made and that you refuse to acknowledge for whatever personal reasons you may have.

I'm sorry if I come off upset, angry, or rude, but it's been over a year since I've been aware of people complaining about this issue, and you just don't care to fix it.

I'm switching any of my projects that use JSPM away from JSPM today, right now, because I don't want to waste any more valuable time with JSPM. JSPM is the only package manager / build system that I've ever wasted *so much time* with, (I'm not exaggerating).

@EisenbergEffect If I were you I'd consider taking `Aurelia` to a different build system for the sake of attracting more users.

**Comment by brianfeister** [comment]
Sooooo... JSPM is used as per if the skeleton for new Angular 2 apps. Sorry but I don't put much stock in developers who don't use GitHub and leaving a comment is proof that you have what you need to fix the issue. Granted I still would love a proxy API built into the the ecosystem that could make these calls and not have to worry about the annoying extra step. Also, the system is more complex but also more powerful. Other languages aren't compiled to so many alternate syntaxes like JavaScript.

**Comment by guybedford** [comment]
@trusktr posting this comment once was more than enough. My response is at https://github.com/aurelia/skeleton-navigation/issues/38#issuecomment-169019572.
