### ISSUE TITLE
Source Not Transpiled

### ISSUE THREAD

**Issue by AutoSponge** [jspm/jspm-cli#724]
I setup 2 projects with identical code (except 1 line and an empty file) then ran the bundler. When there is no import statement at the top, jspm doesn't run the file through babel. This causes a problem for a file with no deps and no 'side-effects'.

https://gist.github.com/AutoSponge/75e9c1c1a2a73ecdf7e5

I made a gist with the relevant files. If you add a blank file called fake.js and import that, jspm will pass the file through babel. It will also work if you add `export {};` to the end of the index file.

When it's not working, you see this error in Chrome:

```
Uncaught SyntaxError: Unexpected token =>
es6-module-loader.src.js:140 Potentially unhandled rejection [2] Error loading "src/index" at http://localhost:63342/experiments/src/index.js
Error evaluating http://localhost:63342/experiments/src/index.js
Uncaught SyntaxError: Unexpected token => (WARNING: non-Error used)
```

**Comment by guybedford** [comment]
@AutoSponge yes, SystemJS detects the module format as ES6 only when there is import or export syntax present. Otherwise it treats it as a standard ES5 global. The reason is that it tries not to run ES6 transpilation on every file unnecessarily. You can enforce a file as ES6 via meta-syntax if it is not containing import or export statements:

```javascript
"format es6";
```

Or: `System.meta['some/module'] = {format: 'es6'}`

**Comment by AutoSponge** [comment]
Good tips.
