### ISSUE TITLE
import destructuring not working with cjs module

### ISSUE THREAD

**Issue by falafel99** [jspm/jspm-cli#736]
I have a `baz` cjs module that exports an object with functions. With jspm this won't work:

```javascript
import {foo} from 'baz'
console.log(foo) // undefined
```

While this does:

```javascript
import baz from 'baz'
var {foo} = baz
console.log(foo) // [function]
```

I am using Babel with jspm to test the code above, but if I use Babel alone (without jspm) then it works fine.

 Any ideas?

**Comment by OrKoN** [comment]
`import {foo} from 'baz'` is a named import. It means that baz has to `export var foo` in order for this to work. But it seems it acts as a default export (`export default baz`) because it's cjs module. I may be mistaken but I think in the case of `import {foo} from 'baz'` not destructuring happens at all and therefore it does not work.

**Comment by guybedford** [comment]
This will be supported in the next SystemJS with https://github.com/systemjs/systemjs/issues/334.

**Comment by guybedford** [comment]
This should be working on the beta release now.
