### ISSUE TITLE
Consider adding linked packages to package.json

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#737]

**Comment by devmondo** [comment]
:+1:

**Comment by guybedford** [comment]
```json
{
  "link": {
    "github:components/jquery@1.2.3": "./local-jquery.zip"
  }
}
```

or it can be a URL etc etc.

Note that just like overrides this would not act transitively through installed libraries, but only within the application itself.

**Comment by glen-84** [comment]
@guybedford I think that you should specify an option (like --persist) when linking, to have it stored in package.json, since this file is committed to VC and the file path or URL of the link may not be accessible to all devs. If the assumption is the opposite (i.e. most often the path *will* be accessible), then it could persist by default and you could opt-out with --temp (i.e. the link is temporary, don't store it in package.json).

**Comment by devmondo** [comment]
love what @glen-84 said, if we can make the linked package permanent, specially that sometimes i have local packages that i dont want to upload to a repo.

@guybedford , could you please rethink the transitively decision? because sometimes we have a linked package in a linked package.

i really feel there should be an option to merge any config for any package with main website, some scenarios really require it.

**Comment by guybedford** [comment]
With `link` moving to becoming a full symlink in jspm 0.17 (not soon, but eventually), this feature wouldn't be necessary. It has no value for local links as we don't want to assume folder structures. For network links that need a `relink` to refresh, a `.link` file in the generated linked package folder would handle this fine.
