### ISSUE TITLE
GitHub rate limiter resolution

### ISSUE THREAD

**Issue by admwx7** [jspm/jspm-cli#756]
Right now if you have an application with a large number of dependencies you'll run into the GitHub API rate limiter rather quickly, this can be fixed by using your GitHub credentials, however when it comes to using `jspm install` as part of your CI it's a bit harder to resolve the issue.  Any CI box would then need a token created and a command run to add the GitHub user to JSPM, not complex but if you then do a clean build on your CI every time it would mean dirtying up your CI build, it would be nice if JSPM could instead default back to an application level token if a user level token wasn't provided.  I'm not up-to-date on the terms for application level tokens so this may not be feasible, figure it's worth discussing at least.

**Comment by calebboyd** [comment]
You may have already seen this. But its possible to export the configuration for simple scripting.
https://github.com/jspm/jspm-cli/wiki/Registries#auto-configuring-registries

**Comment by admwx7** [comment]
I had actually read that already, just been a while and forgot about it!  Thanks, that solves our problem is a much cleaner way.

**Comment by trusktr** [comment]
I'm getting

```js
warn Error on download for github:MikeMcl/bignumber.js
     Error: GitHub rate limit reached.

err  Error downloading github:MikeMcl/bignumber.js.
```

which doesn't even show a hint about what to do about it.

@guybedford When will this abomination be fixed? Do you even care about the *very poor* user experience that this causes? Here's [proof of the poor user experience](https://www.google.com/search?q=jspm%20github%20rate%20limit%20reached), right on Google. Is it your goal to have less users than you could have? Do you think everyone wants to create a GitHub account just so they can use a tool like JSPM? No!

It's been over a year since we've been having this problem (yes, it is a problem, not a feature).

I know as well as you do that you don't need to use api.github.com by default, so that we can avoid this problem altogether, and that you can simply just clone a repo or grab releases from the regular HTTP endpoint (f.e. with URLs like "https://github.com/infamous/motor/archive/v0.0.2.zip") instead of fetching release archives through the API (which hardly anyone uses anyways!!!). I know there's no rate limit because I can run `wget` in a while loop and download the release from https://github.com/infamous/motor/archive/v0.0.2.zip over and over and over with no problems. Every once in a blue moon I'll get `ERROR 429: Too Many Requests.`, but at least it won't be blocked like with GitHub API rate limits.

The most disappointing feeling when trying to work on something is when using a tool (like JSPM) that seems really awesome (because it is in many respects), then encountering such a crap error. I'm sorry, but this is a horrible design *bug* that you've made and that you refuse to acknowledge for whatever personal reasons you may have.

I'm sorry if I come off upset, angry, or rude, but it's been over a year since I've been aware of people complaining about this issue, and you just don't care to fix it.

I'm switching any of my projects that use JSPM away from JSPM today, right now, because I don't want to waste any more valuable time with JSPM. JSPM is the only package manager / build system that I've ever wasted *so much time* with, (I'm not exaggerating).

@EisenbergEffect If I were you I'd consider taking `Aurelia` to a different build system for the sake of attracting more users.

**Comment by guybedford** [comment]
@trusktr posting this comment once was more than enough. My response is at https://github.com/aurelia/skeleton-navigation/issues/38#issuecomment-169019572.
