### ISSUE TITLE
repeated init prompt when opting out of jspm package.json prefix

### ISSUE THREAD

**Issue by edrex** [jspm/jspm-cli#782]
The `package.json` created by jspm init when responding `No` to `Would you like jspm to prefix the jspm package.json properties under jspm?` has neither `jspm` nor `registry` key, causing `prompt = true` on next run.

Not sure `init` or the heuristic needs changing.

**Comment by crisptrutski** [comment]
Thanks for pointing this out, looks like this has been happening since `0.15.4`. 

Updating the heuristic does not seem to be an option, it's possible to generate a super minimal `package.json` with only `devDependencies`.

@guybedford is there a strong reason not to save the "default" `registry` key? Should we perhaps also check whether `config.js` can be resolved before prompting?

**Comment by guybedford** [comment]
@crisptrutski the default `"registry": "jspm"` thing was removed because I didn't want users assuming it was the default registry. But its value in being the indicator that a package.json is "jspm-aware" was overlooked at that point apparently.

`jspm install` should be able to work fine with no `config.js` present so I don't think that can be the indicator unfortunately.

Maybe we should just introduce a `"jspm": true` or `"jspm": {}` package.json property here?

**Comment by crisptrutski** [comment]
Would need to update https://github.com/jspm/jspm-cli/blob/master/lib/config/package.js#L69-L71 then - store `{"jspm": {"prefix": "true"}}` option?

**Comment by guybedford** [comment]
That variable `jspmPrefix` indicates if we are sub-propertying under `jspm`. I guess it is if `jspmPrefix` is false and there is no registry property, that we set `jspm: true` in write?

**Comment by crisptrutski** [comment]
Either or. Slightly prefer getting rid of heuristic for `jspmPrefix`, rather than updating it to have a type check.

**Comment by guybedford** [comment]
Still not sure I understand the proposal - are you saying you'd want a `jspm.prefix` as a property in the package.json itself?

**Comment by crisptrutski** [comment]
Yeah. Let's chew the cud

**Comment by guybedford** [comment]
Fixed in https://github.com/jspm/jspm-cli/commit/ceb678ce8b84494b77789a90d49f555d5a72b8fd.
