### ISSUE TITLE
Questions regarding configuration of existing packages

### ISSUE THREAD

**Issue by glen-84** [jspm/jspm-cli#790]
I have three questions regarding configuration of existing packages:

1. Should the CSS be included/depended on? We did so for [Semantic-UI](https://github.com/jspm/registry/blob/master/package-overrides/github/Semantic-Org/Semantic-UI%401.11.8.json), but it's not done for [Bootstrap](https://github.com/jspm/registry/blob/master/package-overrides/github/twbs/bootstrap%403.3.4.json) – why is this, and which is "correct"?

2. Is it best to reference the minified dependency, if available? Most modern browsers include the option to "pretty print" source, and developers can use an override if they absolutely must use the non-minified version of the file.

3. Should PRs be sent to source repos with the appropriate JSPM config, or is the JSPM registry being used until there is a 1.0 release, in case any large changes occur (like moving to a [separate config file](https://github.com/jspm/jspm-cli/issues/190#issuecomment-105008143))?

If a package-override file is required for every version of a package, it's soon going to become a nightmare to manage all the PRs and issues for the registry (if it isn't already).

**Comment by guybedford** [comment]
1. I would advocate always having CSS as a dependency. Currently we don't easily have a fallback for disabling CSS auto-inclusion though. The plan is to make this use cases easier, and then advise always making CSS a dependency so that it can be opted-out. Currently because we don't have an easy opt-out it is a per-project decision. Bootstrap really should have it, this was an oversight on my part in changing that.
2. It's best to reference the unminified dependency for development. Minification should always be a production step, at least until source maps become better supported in development in browsers, since there are still issues.
3. Yes PRs with jspm should be sent to the original project for management. Only where there is friction from the maintainers, or while waiting for it to land, is the jspm registry designed to be used.
4. The override service applies to all future versions semver compatible with the override version.

**Comment by lookfirst** [comment]
I disagree that the CSS should be included. I may want a dependency on the JS, but will load the CSS from a CDN. By including it, you don't allow me to make that decision myself.

**Comment by glen-84** [comment]
1. Would changing the Bootstrap config be a BC break now? Will you wait for the opt-out feature before changing it? Is there an issue ticket for this feature? Will the opt-out be generic like "load related resources" or something, in cases where you may use SASS or depend on other non-CSS files? (or something like `--excludeDeps=*.css,*.png`)

2. What about the HTTP/2 scenario? I didn't think that we would still need to bundle/prep in these cases. It would be nice if we could just serve directly from `jspm_packages`.

3. Okay.

4. I guess that helps a bit. :smile:

@lookfirst,

Read again, there will be an opt-out mechanism.

**Comment by guybedford** [comment]
1. Yes at this point bootstrap will need to be upgraded with CSS functionality again when we can do it in a backwards compatible way.
2. Yes one does just serve directly from jspm_packages for HTTP/2, basically you would run a minification step over the entire jspm_packages folder (or serve it from a server that automatically minifies on-demand, like the jspm CDN).

**Comment by glen-84** [comment]
1. I'm probably going to be submitting a PR for JSPM config in Semantic-UI within the next few days – should I also omit the CSS dependency for now? (what is the issue number that tracks this CSS opt-out functionality?)

2. That makes sense. Thanks.

**Comment by guybedford** [comment]
Great to hear! Would you use the CSS yourself? If so I'd suggest including it if you'd want that yourself.

**Comment by glen-84** [comment]
@guybedford,

I don't want to make the decision based on my own personal requirements. It's quite possible that I may even end up not installing SUI via JSPM, since I might need to use the LESS source files.

If I include the CSS, the only way to undo that would be to use an override. Perhaps I should rather wait until https://github.com/jspm/jspm-cli/issues/791 (?) is implemented.

**Comment by guybedford** [comment]
Yes that makes sense. Closing as I think we've answered everything here. Thanks for your questions and input!
