### ISSUE TITLE
CSS as optional

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#791]
We need a clear workflow for skipping CSS require support. Map the CSS plugin to the empty plugin?

Perhaps during the init prompts we allow users to do plugin setup - use CSS requires? etc etc

It could be possible a user would want to use CSS requires though, but just not for specific installed packages, so we need to be able to opt-out per package too.

A custom map for the package would be the solution here (`jspm install x -o "{map: {css: 'empty-plugin'}}"`), but again, how to optimize the workflow? Also should the empty plugin be a concept supported in SystemJS just like `@empty`?

**Comment by glen-84** [comment]
It definitely needs to be on a per-package basis.

It may also make sense to generalize this, so that you can opt-out of other dependencies as well.

What about a basic globbing syntax? That would even allow you to prevent specific dependencies from loading.

Something like: `jspm install semantic-ui --exclude=jquery,css --disable-imports=*.css`

`--exclude` would prevent the listed dependencies from being downloaded. The user would be responsible for loading them separately (from a CDN perhaps).
`--disable-imports` would prevent specific dependencies from being loaded (globbing syntax). f.e. Don't import anything ending with `.css`.

**Comment by guybedford** [comment]
The large number of dependencies for the css plugin was previously the issue here, but since we've separated the build dependencies with a separate command, having the plugin installed when not necessary no longer seems such a big issue.

By creating a module without css imports, and a separate module wrapper with the css import, publishers can manage this separation for their users.

**Comment by guybedford** [comment]
There may be some value to having a prompted optional dependency system in future - 

```
  Package github:some/package@1.2.3 has the following optional dependencies:
  * css@^1.2.3
  * asdf@^1.2.3
  Would you like to install these [y/n]
```

Perhaps even with a `jspm install x --optional` flag as well to auto-confirm. No need to track that in an issue just yet.
