### ISSUE TITLE
migration for components and component user

### ISSUE THREAD

**Issue by timaschew** [jspm/jspm-cli#841]
jspm is really awesome, thanks for this tool.

I'm maintaining component and we use it at our company, but it has so many issues.
I tried out some experiments with component and jspm and I think it could be a drop in replacement.

I started to write a tool which helps to do a migration: https://github.com/componentjs/component2jspm

I need to know some stuffs, how jspm is working internally, maybe we can put this information into the docs later.

I would like to know:

so jspm is not using the lookup strategy when requiring a path: looking into a file with the .js extension, looking into a directory with a index.js file; or the same for a .json file. so what strategy it use?

in the config.js you can define kind of a lookup path, right?
```
  "paths": {
    "*": "*.js",
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js"
  }
```

How the rules/pattern do work, how they are applied, like iptables?
Can I define multiple lookup paths for my local modules (not in jspm_packages)
Given this directory structure:
```
- lib/
    - boot/
        - index.js
    - sub1/
        - a/
            - index.js
        - b/
            - index.js
    - sub2/
        - x/
            - index.js
        - y/
            - index.js
```

So is it possible to define these lookup paths: __boot__, __sub1__ and __sub2__, so
that regardless in which module I am, I can write `require('x')`  and `require('boot')`

If I run `jspm install` several times, it doesn't recognize that everything is installed already, so it installs everything again. How I can avoid this?

**Comment by guybedford** [comment]
Really glad to hear you're liking the project! That's awesome you're working on this tooling.

SystemJS resolution algorithm is a 1 - 1 mapping process. The rules of map and paths apply to get from an abstract name (`jquery`) into a canonical name (`github:components/jquery@1.2.3`) and finally into a URL (`https://site.com/jspm_packages/github/components/jquery@1.2.3.js`). Map is the first stage, paths is the second stage. Then there are other normalizations as well, but that's the main parts.

To make jspm work with a custom lookup like you have, means statically resolving the lookup beforehand, and injecting the resolved lookup via map config or code rewriting. This is exactly what we do when converting npm packages for jspm by rewriting the require statements.

`jspm install` is always guaranteed to do a full verification of the dependency tree (it will guarantee everything is correct). there is `jspm install -q` which may save time as it only guarantees the first-level of dependencies.

**Comment by timaschew** [comment]
> means statically resolving the lookup beforehand, and injecting the resolved lookup via map config or code rewriting.

can I use something different than to use an explicit map for the lookup?
for instance a convention, that should try to lookup first for a `client.js` and if it doesn't exist, it should try the next one: `index.js`?

**Comment by guybedford** [comment]
Is this for code that has different entry points between client and server?

The goal is to handle these cases via conditional loading, although the feature isn't stable yet.

It is something like - 

```javascript

**Comment by timaschew** [comment]
yes, that's right, it's for client and shared code. 

Our idea was to use client.js for client side entry points and index.js for both (client and server)

**Comment by guybedford** [comment]
@timaschew I've been thinking about this some more and we're still not optimized to this use case unfortunately.

Configuration is definitely the way to handle the main entry point branching between environments though.

What are your thoughts on something like - 

```javascript
System.config({
  packages: {
    'some/package': {
      main: '@browser#?browser.js#:index.js'
    }
  }
});
```

Where `@browser` is a global module returning a boolean value for the environment.

It's syntax yes but within the configs so that code remains portable (although the syntax would also be supported within code). The benefit of this approach is that it is easy to optimize in builds which is the goal (eventually).

I know something like:

```javascript
System.config({
  packages: {
    'some/package': {
      main: 'index.js',
      browser: {
        main: 'browser.js'
      }
    }
  }
});
```

May feel more intuitive, but I'm trying to keep the flexibility of builds and environment as a module in mind (as well as synchronous normalization).

I'd be interested to hear your thoughts on the above. It would be nice to get something in SystemJS very soon, but it would still be a month or so to see that reflected in jspm unfortunately. It's annoying we're still not quite there yet on this use case, but I'm keen to continue pushing forward on this quite hard.

**Comment by guybedford** [comment]
The syntax is so ugly though... I've gone ahead and implemented the latter example experimentally in master at https://github.com/systemjs/systemjs/commit/329b4e2531a7c58a3d8072431d2d7efb776d77f5, this may well make it into jspm in due course.

**Comment by guybedford** [comment]
(SystemJS package config is designed exactly to be the jspm package.json config)
