### ISSUE TITLE
Nested dependencies not getting mapped to `config.js`

### ISSUE THREAD

**Issue by timbur** [jspm/jspm-cli#849]
`ModuleA` has roughly 20 dependencies defined within the `jspm` section of its `package.json`.  `ModuleB` wants to use `ModuleA`.  Using `jspm install ModuleA=github:timbur/ModuleA`, `ModuleB`'s `config.js` doesn't get updated with the proper `map` configuration so that `ModuleB`'s `System` will know where to find `ModuleA`'s dependencies.  I've tried everything I could think of, other than starting completely from scratch.

I also tried reproducing the issue (see [`timbur/systemjs-test-c`](https://github.com/timbur/systemjs-test-c)) but that one works correctly.

`ModuleA` in the above description is actually [`loggur/web-tedit`](https://github.com/loggur/web-tedit).

**Comment by guybedford** [comment]
You need to set the `registry` property in the package.json for dependencies to be read.

This is documented in https://github.com/jspm/jspm-cli/wiki/Publishing-Packages#writing-a-library-or-application-for-usage-just-with-jspm and https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#package-dependencies and this is also mentioned on the website when describing the registry. 

How could this be clearer?

**Comment by timbur** [comment]
Ah, man.  I don't know how I overlooked that.  When I saw the "registry" header, I must have skipped over it, assuming it was only related to publishing to jspm's registry list.  I didn't make the connection between that and how jspm might handle dependencies, despite looking for the "dependencies" keyword.

> How could this be clearer?

I think in most cases it would be safe to assume that if something is being pulled from GitHub and includes `jspm.dependencies` within its `package.json`, those dependencies should be automatically configured (mapped), as they seem to be getting downloaded anyway.  Either that or add an input to the `jspm init` process that asks for the registry.

It was confusing to me that `jspm` would install all of those nested dependencies and add them to `config.js` under the package's `map` object without actually mapping each nested dependency as well.  Even more confusing: [`systemjs-test-c`](https://github.com/timbur/systemjs-test-c) seemed to map the nested dependencies without the registry property.  I had also assumed that since nearly everything else was performed via command line, I wouldn't have to update `package.json` manually.  I figured there was maybe some unseen compatibility issue when upgrading jspm to 0.16-beta.  That was my thought process anyway.  Sorry to be a nuisance.  :)

Also, my apologies for bombarding you with so many issues lately, especially when a lot of this stuff is already documented.  I know how annoying that can be.

**Comment by timbur** [comment]
So, I've added `"registry": "jspm"` to [`package.json`](https://github.com/loggur/web-tedit/blob/master/package.json), performed `jspm remove web-tedit` and then `jspm install web-tedit=github:loggur/web-tedit`, and the nested dependencies are still not being added.  Am I just being really stupid or...?

This is all that gets added to `config.js`:

```js
System.config({
  "map": {
    ...
    "web-tedit": "github:loggur/web-tedit@master",
    ...
    "github:loggur/web-tedit@master": {
      "ace": "github:ajaxorg/ace-builds@1.1.9",
      "babel": "npm:babel-core@5.5.8",
      "babel-runtime": "npm:babel-runtime@5.5.8",
      "bodec": "github:timbur/bodec@1.1.1",
      "buffer": "npm:buffer@3.2.2",
      "carallel": "github:creationix/carallel@master",
      "core-js": "npm:core-js@0.9.17",
      "css": "github:reworkcss/css@2.2.0",
      "dombuilder": "github:loggur/dombuilder@master",
      "gen-run": "github:creationix/gen-run@0.1.2",
      "git-sha1": "github:creationix/git-sha1@0.1.2",
      "git-tree": "github:creationix/git-tree@master",
      "jon-parse": "github:creationix/jon-parse@master",
      "js-git": "github:timbur/js-git@0.7.11",
      "js-github": "github:creationix/js-github@1.0.0",
      "mine": "github:creationix/mine@0.1.0",
      "pako": "github:nodeca/pako@0.2.7",
      "pathjoin": "github:creationix/pathjoin@0.1.0",
      "systemjs-reload": "github:loggur/systemjs-reload@master",
      "tedit-regenerator": "github:creationix/tedit-regenerator@master"
    },
    ...
});
```

**Comment by timbur** [comment]
Upon further inspection, I think that might be all `config.js` needs, but if that's the case, why is `SystemJS` not looking in the right place for those packages?

**Comment by timbur** [comment]
Alright well, I'm not going to waste another entire day trying to debug this shit so I guess I'll just explicitly map each nested package.

**Comment by guybedford** [comment]
I'm really not following, you have a package with dependencies - tedit. When you install the package, the dependency maps are exactly appearing in the config file as you say - 

```
      "ace": "github:ajaxorg/ace-builds@1.1.9",
      "babel": "npm:babel-core@5.5.8",
      "babel-runtime": "npm:babel-runtime@5.5.8",
      "bodec": "github:timbur/bodec@1.1.1",
      "buffer": "npm:buffer@3.2.2",
      "carallel": "github:creationix/carallel@master",
      "core-js": "npm:core-js@0.9.17",
      "css": "github:reworkcss/css@2.2.0",
      "dombuilder": "github:loggur/dombuilder@master",
      "gen-run": "github:creationix/gen-run@0.1.2",
      "git-sha1": "github:creationix/git-sha1@0.1.2",
      "git-tree": "github:creationix/git-tree@master",
      "jon-parse": "github:creationix/jon-parse@master",
      "js-git": "github:timbur/js-git@0.7.11",
      "js-github": "github:creationix/js-github@1.0.0",
      "mine": "github:creationix/mine@0.1.0",
      "pako": "github:nodeca/pako@0.2.7",
      "pathjoin": "github:creationix/pathjoin@0.1.0",
      "systemjs-reload": "github:loggur/systemjs-reload@master",
      "tedit-regenerator": "github:creationix/tedit-regenerator@master"
```

What more were you expecting than the above?

**Comment by guybedford** [comment]
Also why are you getting a 404 for things like `git-sha1.js` when that is clearly in the installed map?

**Comment by guybedford** [comment]
Which version of jspm / SystemJS are you using here?

**Comment by timbur** [comment]
> Also why are you getting a 404 for things like git-sha1.js when that is clearly in the installed map?

That's what I'm wondering.  I'm using jspm 0.16 beta and whatever SystemJS is included with that.  I also tried `jspm dl-loader --edge` today but every file for the `web-tedit` package 404s.  I had also tried `jspm install web-tedit=github:loggur/web-tedit` within a brand new project and tried `System.import('web-tedit')` to see if it would work but the same thing happens.  If there's an issue with `web-tedit`'s config, I can't find it.  It works by itself.

**Comment by timbur** [comment]
If you could point me towards the `systemjs` code responsible for locating the files based on the dependency map, I should be able to figure out either what I'm doing wrong or if there's an obscure bug with the locator.

**Comment by guybedford** [comment]
Would I be able to replicate this with `jspm install github:loggur/web-tedit@master`?

Dependency map doesn't do anything strange - it does what it says.

Note that there is an issue if code does say `require('git-sha1.js)` where the package name is `git-sha1` then it won't detect it.

Otherwise make sure you upgrade to the latest beta (beta.2) as well, this may be beta issues.

**Comment by timbur** [comment]
> Would I be able to replicate this with jspm install github:loggur/web-tedit@master?

Yes, I believe so.

**Comment by guybedford** [comment]
Oh man this is a mess, I can see your frustration.

I think the reason is that these are sets of dependencies written in the NodeJS-style based on NodeJS assumptions - is there a reason you're loading everything from GitHub instead of npm through the conversion layer?

**Comment by guybedford** [comment]
Or are the resolutions working for your in the local testing?

**Comment by guybedford** [comment]
Have you tried `jspm install npm:js-git`?

**Comment by timbur** [comment]
I believe @creationix (Tim Caswell) designed the original tedit to be almost entirely based on git repos.  Tedit is a git repo editor that is capable of creating/modifying/building itself.  I don't think Tim Caswell had npm in mind, or at least not for most things.  Plus, I think an ideal development environment deals entirely with git repos anyway, as opposed to npm packages.

**Comment by timbur** [comment]
I'll try that now.

**Comment by guybedford** [comment]
Btw if you want to install a project from GitHub that was written with "Node / npm" conventions the way to do this would be:

```
  jspm install github:creationix/js-git@x.y.z -o "{registry:'npm'}"
```

jspm then hands over conversion of the package to the npm registry conversion layer even though github was used for transport.

**Comment by timbur** [comment]
Also, on a semi-related note while I'm thinking about it, I noticed that the `overrides` section doesn't transfer to the install.  Should I elaborate or do you get what I'm saying?

**Comment by timbur** [comment]
Okay I'll try that before continuing with `npm:js-git`.

**Comment by guybedford** [comment]
Note the js-git repo depends on `github:creationix/pathjoin` so you'd need to first install that with the npm registry override.

Exactly - `overrides` aren't transitive yes so that's why you need the above.

**Comment by timbur** [comment]
About the `overrides`, what I mean is... `web-tedit` has a `directory.lib` override for `ace`, so wouldn't it make sense that when installing `web-tedit` and the `ace` dependency along with it, it uses the override specified by `web-tedit`?  Or at least if `ace` isn't already installed by the top package?

**Comment by guybedford** [comment]
No, because if we allowed that everyone would post custom overrides on all packages, and dependency sharing breaks down. That's why we have the registry to battle out overrides in PRs. If you think the Ace override is incorrect, do post an issue.

**Comment by creationix** [comment]
Right, the idea with tedit's package system is to use vanilla git submodules.  They actually have really good properties for dependency management.  You get shrinkwrap by default since the tree entries are literally hashes to commits.  The `.gitmodules` file is basically ini format and can be extended with extra metadata like a semver range.

The grand plan that never happened (yet) was to have a package manager in tedit that could read this extra metadata in .gitmodules and periodically check the submodules for compatible updates and prompt the user if they want to update their submodules.

**Comment by creationix** [comment]
Also, the only reason that git submodules generally get a bad name is because the git cli tool has terrible UX around them.  The core data model is very nice, we just need some UX that not so user-hostile and half-baked.

**Comment by timbur** [comment]
@guybedford I see.  There's no way to associate the override with that particular dependency then?

**Comment by timbur** [comment]
Hey @creationix!  Thanks for the clarification.  Tedit is awesome.  You and I actually haven't talked much about it but I think we're on the same exact page with regards to the submodules and UX improvements.  As I mentioned before, I think there's a ton of potential there, and I'd love to hear anymore of your thoughts on it.  You could probably even give me a todo list and I'll see what I can do to implement certain features, since you're busy with other things these days.  :D

**Comment by creationix** [comment]
@timbur sounds great.  Let's create a new thread on the tedit repo so as to not hijack this conversation.

**Comment by timbur** [comment]
Also, @guybedford I'm still getting 404s when using the registry overrides.  Are you sure they're necessary in this case?  I must not understand how the overrides affect the dependency map, because `web-tedit` works on its own without any overrides other than for `ace`.

You should be able to:
```
git clone git@github.com:loggur/web-tedit.git
cd web-tedit
npm install
npm start
open http://localhost:8080
```

**Comment by timbur** [comment]
Updated last comment to include `jspm install`.

I have to head out for a bit but @guybedford can you point me towards a good section of code for me to start within `systemjs` so that I can figure out what the problem is?  It would probably help me out a lot if I understood its internals, or at the very least, I could track down the root cause of my particular issue.  I would assume one of the `locate` hooks is a good place to start?

**Comment by guybedford** [comment]
@creationix I see what you mean yes we don't currently handle submodules when installing from github. It could definitely be worth considering.

@timbur so are you saying it works on its own, but just not when installed as a dependency itself? For Ace, I'm still not sure why you need a custom override for that. It could be worth having a discussion about that at the registry at https://github.com/jspm/registry. Am I right in following that submodules support a blocker here then when installing? I have very limited time to help, so the more you can assist to isolate and clearly explain the issue the more I can help - I must admit I still don't follow at all what your actual issue is here.

**Comment by timbur** [comment]
@guybedford I really appreciate the help.

> so are you saying it works on its own, but just not when installed as a dependency itself?

Correct.

> Am I right in following that submodules support a blocker here then when installing?

I'm not sure what you mean.  `web-tedit` doesn't use submodules.  @creationix's original `tedit` does, however.

**Comment by guybedford** [comment]
@timbur thanks that makes sense - sorry for the running around on this one. Right in that case the explanation would be that you have a dependency that has a dependency on a primary dependency of your project, so the dependency seems fine when running locally, but actually it's not properly declared in the consumer.

So for example here, one of your dependencies is requiring `bodec`, but it wasn't defined as a dependency of that dependency. Because you've installed it directly into your project it finds it, but that won't apply when installing the project.

The way to fix this is unfortunately to go through the dependencies carefully ensuring overrides explicitly declare them as package dependencies.

This is a catch though I can see. In future the working project the goal is for the current project to be a package itself then hopefully we can warn about this sooner.

**Comment by timbur** [comment]
Okay I think I see what you're saying.  Interesting.  That makes sense.  I'll try a few things shortly to see if I'm on the right track.

Oh I forgot to mention, I noticed the `npm` dependencies were missing (from when I set `registry` to `jspm`), so if you tried the installation I outlined before, it of course didn't work correctly at the `npm install` step.  It should work now though.

**Comment by timbur** [comment]
Hmmm... Would it work to fork everything and add `"registry": "npm"` to each `package.json`?  And if so, maybe it would make more sense for `jspm-cpi` to assume the `registry` is `npm` if none provided or at the very least, if the none of dependencies` values match `jspm`'s format - e.g., registry:user/repo@etc.?

**Comment by guybedford** [comment]
@timbur you're best off doing this via having overrides for everything in your package.json. In terms of offering this transitively, you can check them into the jspm registry, or even host your own override registry if you prefer.

**Comment by timbur** [comment]
@guybedford The overrides work, but I feel like the issues I experienced could be avoided if `jspm` defaulted to `npm` if no jspm-style dependencies are found within the `package.json` (and no registry provided of course).  I think something along these lines would work:
```js
if (_pjson.registry === undefined && !_pjson.jspm && !hasJspmDep(_pjson.dependencies) && !hasJspmDep(_pjson.devDependencies)) {
  self.jspmPrefix = false;
  _pjson.registry = 'npm';
}

var jspmTest = /\w+:[\w\/]+@\w/;
function hasJspmDep (deps) {
  for (var key in deps) {
    if (jspmTest.test(deps[key])) {
      return true;
    }
  }
  return false;
}
```

It would also avoid having to use a ton of overrides like I'm doing here:
```json
    "overrides": {
      "github:ajaxorg/ace-builds@1.1.9": {
        "directories": {
          "lib": "src-min-noconflict"
        }
      },
      "github:loggur/bodec@master": {
        "registry": "npm"
      },
      "github:creationix/carallel@master": {
        "registry": "npm"
      },
      "github:loggur/dombuilder@master": {
        "registry": "npm"
      },
      "github:creationix/gen-run@0.1.2": {
        "registry": "npm"
      },
      "github:creationix/git-sha1@0.1.2": {
        "registry": "npm"
      },
      "github:loggur/git-tree@master": {
        "registry": "npm"
      },
      "github:loggur/jon-parse@master": {
        "registry": "npm"
      },
      "github:loggur/js-git@master": {
        "registry": "npm"
      },
      "github:loggur/js-github@master": {
        "registry": "npm"
      },
      "github:creationix/mine@0.1.0": {
        "registry": "npm"
      },
      "github:nodeca/pako@0.2.7": {
        "registry": "npm"
      },
      "github:creationix/pathjoin@0.1.0": {
        "registry": "npm"
      },
      "github:reworkcss/css@2.2.0": {
        "registry": "npm"
      },
      "github:loggur/systemjs-reload@master": {
        "registry": "npm"
      },
      "github:creationix/tedit-regenerator@master": {
        "registry": "npm"
      }
    }
```

**Comment by guybedford** [comment]
Thanks for the suggestion. The issue here is the when adding `registry: 'npm'` we no longer run scripts the same way they run in the browser. And this can break a lot of projects that provide browser globals as well as publishing to npm. By not interpreting by default, those browser builds can be loaded as globals or AMD and work fine as an alternative to the version of the same package on npm.

So there's no easy rule here unfortunately, although suggestions are always welcome to discuss for these behaviours, where we can draw the careful line between predictable to the user, and a smart system.

The way that may be nice to approach this is via "hints" and "queries".

Perhaps something like - "Package github:creationix/tedit-regenerator has no registry set, but the dependencies look they they are for npm, would you like to treat this as an npm package? [y/n]".

The goal was always to provided a guided override process mode with things like the above. It avoids the confusion factor of too many rules to keep track of in handling (trying to keep it simple and very easy to explain) It's just a matter of resources.

**Comment by timbur** [comment]
> Perhaps something like - "Package github:creationix/tedit-regenerator has no registry set, but the dependencies look they they are for npm, would you like to treat this as an npm package? [y/n]".

Yeah that does seem like it would be the best solution.  :)  Thanks again for all the hard work and the feedback!

**Comment by AckerApple** [comment]
Hello from over a year later. I've been crawling the web on how to make my jspm projects satisfy sub-dependencies across other jspm projects with their own dependencies BECAUSE I see the sub-dependencies are installed BUT I get errors that a package in jspm_packages cannot find some dependency of it's... I see this conversation just ended in an agreement that something could be modified. I'm going to try the overrides suggested here in the above conversations..... MY Question, beyond my observations, is has their been more advancements in sub-jspm dependency injection? If so, can I guided to more links or any projects that have satisfied this need (again, I have not tried the overrides for every packages with registry data, going to try now).

**Comment by AckerApple** [comment]
It would seem, the overrides with registry "npm" for github packages, works! I haven't overly confirmed this but off the cuff and on the surface, it seems to be working (specifically: using overrides with registry=npm).
