### ISSUE TITLE
Transitive overrides

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#854]
Perhaps it is time to actually reconsider this.

If we allow overrides in a package.json of a package installed to apply, the issue becomes the possibility of dependency override collisions.

But 90% of the time users won't hit those collisions, and feel that this is an artificial constraint.

So we could allow overrides, but as soon as there is a collision, then we error out and inform the user they need to resolve the override collision. This process of resolution is then the best place for the registry override to come in too (finally an event with enough force to drive users to use it!).

Then override sharing is entirely optional for users.

The other benefit here is that when installing packages from npm that have dependencies on GitHub we can automatically apply the `registry: 'npm'` property from the npm registry endpoint itself via such an override.

**Comment by guybedford** [comment]
It's immediately a collision for a package with an override of its dependency to install that dependency against another package that has that dependency without an override. That is this would only apply to dependencies that are never shared. Building a complex feature with non-shared dependencies as the premise is just not a good idea.

**Comment by niieani** [comment]
I understand the reasoning, however in relation to https://github.com/jspm/registry/issues/645 what is the best way to solve this problem? Asking the user to manually add the `overrides` entry to the package.json is quite cumbersome, especially since it involves targeting a specific version, thus the user needs to manually edit the config after every update of the package being overwritten.

**Comment by CxRes** [comment]
@guybedford Please reconsider opening this - in a large project it is impossible to track transitive dependencies (especially in my usecase where I am dealing with multiple es6 style cjs projects, a common case in npm while we are stuck in this transition period, which all need to be transpiled)! 

You can always install a fork as `repo/package@version-x` where `x` indicates an override (I think it is a good practice to explicitly mark out overrides anyway, so that uses looking at config know what they are dealing with). This can be tracked easily in `maps`.

Checking in such a setting to [jspm/registry](https://github.com/jspm/registry) might not be a good idea as other may still want to treat these packages with es6 style cjs code "as is" (such as running it inside a node runtime or using a polyfill in the browser)

**Comment by guybedford** [comment]
I'm currently considering adding transitive overrides for jspm 2.
