### ISSUE TITLE
Redundancy support & timeout option

### ISSUE THREAD

**Issue by ffffranklin** [jspm/jspm-cli#857]
Would it make since if jspm -or- System took a timeout option and supported redundancy for targets that don't resolve?  Currently on jspm.io the `showdown` github target doesn't resolve (see jspm/jspm.io#26) so it hangs forever. It would be nice if it could be set to timeout after 10s and automagically fallback to the npm target `npm:showdown`, of which does resolve.   IDK

**Comment by guybedford** [comment]
I don't like paths fallbacks because they are incredibly inefficient as a method of flexible transfer.

There are so many ways of approaching the problem of transport consistency at the loader level (think service worker, parallel requests, test requests) that are much better ways to tackle this problem that anything we implement will be bad in comparison to what could be done.

So I wouldn't really want to dictate anything here.

**Comment by ffffranklin** [comment]
Got it.  Agreed.  Closing
