### ISSUE TITLE
Use single quotes in jspm-generated config file.

### ISSUE THREAD

**Issue by VasilioRuzanni** [jspm/jspm-cli#860]
Now it makes JSHint complain about double-quotes all over `config.js` file that represents SystemJS configuration.

Also:
- Is there any reason to wrap everything in quotes? Like top-level options, etc. It just makes file much less readable because everything is highlighted as a string and is not idiomatic JS anyway. Is there any way to leave keys quoted only inside `paths`, `map`, `meta` or wherever we might have some paths/URLs/module names?

- Any reason to overwrite the SystemJS config on each `jspm install`? Is there an option to make it optional? Would really like to keep my own `map`/`paths config intact and formatted appropriately, possibly avoiding using 2 config files side by side.

- Just curious: Any reason why jspm generates SystemJS configuration split into several `System.config(...)` calls as opposed to just having everything under one?

**Comment by guybedford** [comment]
I'd be happy to consider specific minor style adjustments. At the moment it is double quotes simply as the output of JSON.stringify.

The config calls are separated for readability. It does write on every op because it is a formatting operation. It is jspm's configuration file, not the users'. How is your map or paths config being changed?

**Comment by VasilioRuzanni** [comment]
Well, its not changing much, mostly just simple `meta` adjustments or paths to some modules that I need explicit file set for. I used to perceive this config file as the users' indeed.

Would you advise to use a separate one for the part I want to have developer control (as opposed to jspm) over? Looks redundant to me from one side but might be justified for "jspm" vs "user" control balance.

**Comment by guybedford** [comment]
Meta is kept intact and not changed, paths are only altered if they are the registry paths themselves. So I'm not sure how it is interfering with your workflow here?

**Comment by VasilioRuzanni** [comment]
@guybedford Just to clarify - nothing is broken from functioning standpoint, the data itself is not changed, that works just fine.

Its purely a formatting concern and a wish to keep the code that needs to be maintained manually from time to time is not overwritten by the package manager (we keep some whitespaces and different/no quoting for readability and to keep JSHint happy).

**Comment by guybedford** [comment]
Yeah then this is a problem with no solution - everyone has different code style requirements the jspm style will always be different to someones style.

As far as there are standard style considerations though, happy to consider:

* Single over double quotes
* Removing quotes on configuration property names

**Comment by VasilioRuzanni** [comment]
@guybedford Yeah, these two are actually main ones. Would be awesome if they're generated that way!

I can live with workarounds for everything else (either having a separate file for user config or having to cope with semi-automatically formatted parts of config file), unless a better solution bubbles up at some point (like splitting the "jspm" concerns from the user config and keep it hidden somewhere behind the scenes, but its actually out of the scope of this issue request).

**Comment by laurentdesmet** [comment]
I was wondering if there is a specific reason why jspm uses a `config.js` file instead of a `config.json` file. It seems weird to me to use a programming language for a configuration file instead of a data formatting language like JSON but maybe there is something that I miss here. For example: I'm wondering what happens if I add some extra lines of code before and after the contents of this config file: how can you properly parse the contents out of it when the configuration file needs to be updated?

Wouldn't it be an option to also support a `config.json` file, which is exactly the same as the current config.js file but without the wrapping `System.config()` call?

It would also solve the issue with people having all kinds of different linter settings.

**Comment by doctyper** [comment]
I have to agree with @laurentdesmet, there are some spots in my server set up where I would love to ingest the current config, but I am unable to due to the wrapper call.

+1 JSON-compliant config.

**Comment by guybedford** [comment]
The reason for a wrapper is to allow the config to be loaded by a `<script>` tag without this adding unnecessary latency to the page load.

**Comment by laurentdesmet** [comment]
Ok, but the conversion of the JSON structure to a JS-file that can be loaded as a script tag could easily be done using a build step. For me this reason doesn't seem to justify the need for a wrapping call, because semantically we're talking about configuring something, and a declarative structure seems more appropriate for this of use case.

**Comment by guybedford** [comment]
Supported in jspm 0.17 beta.

**Comment by cchamberlain** [comment]
Not sure what is supported in the beta (quote style or JSON config), but I've been using the beta and am still getting double quote generated files.

My easy fix has been to run `eslint --fix jspm.config.js jspm.browser.js` post regeneration.

My .eslintrc:

```json
{
  "ecmaFeatures": {
    "jsx": true,
    "modules": true,
    "blockBindings": true,
    "defaultParams": true,
    "forOf": true,
    "generators": true,
    "objectLiteralComputedProperties": true,
    "objectLiteralDuplicateProperties": false,
    "objectLiteralShorthandMethods": true,
    "objectLiteralShorthandProperties": true,
    "templateStrings": true
  },
  "env": {
    "browser": true,
    "node": true
  },
  "parser": "babel-eslint",
  "rules": {
    "quotes": [2, "single"],
    "strict": [2, "never"],
    "semi": [2, "never"],
    "brace-style": [2, "1tbs", {
      "allowSingleLine": true
    }],
    "comma-dangle": [2, "never"],
    "no-dupe-keys": 2,
    "no-ex-assign": 2,
    "no-extra-semi": 2,
    "valid-typeof": 2,
    "generator-star-spacing": [2, {"before": false, "after": true}],
    "react/jsx-uses-react": 2,
    "react/jsx-uses-vars": 2,
    "react/react-in-jsx-scope": 2
  },
  "plugins": ["react"]
}
```

**Comment by ciel** [comment]
This is marked as _fixed_, but I cannot find any documentation talking about how to set this functionality.
