### ISSUE TITLE
Bower dependencies

### ISSUE THREAD

**Issue by techniq** [jspm/jspm-cli#866]
I was looking to use jspm to install all of the Polymer iron-elements using `jspm install github:PolymerElements/iron-elements` but it appears jspm does not read the `dependencies` of `bower.json`.

Is the recommended way to install Polymer elements with jspm to use the [jspm-bower-endpoint](https://github.com/2fd/jspm-bower-endpoint) or install each individually (`jspm install github:PolymerElements/iron-ajax github:PolymerElements/iron-ajax ...`)  ?

**Comment by guybedford** [comment]
Having the dependencies being automatically installed would only be useful as peerDependencies since each package has its own dependency namespace to avoid conflicts for normal dependencies.

I'm hoping to add the peerDependencies feature really soon, but in the mean time I guess individual installs would be the way to go here.

There isn't anything in the registry currently at https://github.com/jspm/registry/ for these, so let me know how they work out and if we need to do any overrides I can help. I'd also suggest looking at other registry entries by example to see how they work.

**Comment by techniq** [comment]
@guybedford I'll experiment and let you know.  Not sure I'll have much success due to Polymer's reliance on HTML imports

**Comment by myuseringithub** [comment]
@techniq Old question, but did you succeed with installing the all elements with one command ? thanks

**Comment by techniq** [comment]
@myuseringithub  I was not and last I looked it still wasn't possible. 

https://github.com/Polymer/polymer/issues/1133
