### ISSUE TITLE
Can not install cyclejs using jspm

### ISSUE THREAD

**Issue by tautvilas** [jspm/jspm-cli#899]
jspm install npm:@cycle/core

Looking up npm:@cycle/core
err  Repo npm:@cycle/core not found!
warn Installation changes not saved.

Actual npm repo: https://www.npmjs.com/package/@cycle/core

**Comment by guybedford** [comment]
Scoped packages in npm are only supported in the new beta accessible via `npm install -g jspm@beta`. It's a stable beta so encouraged to use.

**Comment by tautvilas** [comment]
thx!

**Comment by Thiemo-Mueller** [comment]
I just ran into a few hours of debugging why I received an "Repo npm:@angular/core not found!" error even when using the new beta. It turned out that my .npmrc had saved old authentication data for npmjs.org and weirdly their registry returns a 404 status code if you provide wrong credentials, even if the package is actually visible to the public like @angular is. Just to let future Googlers know..
